### ISSUE TITLE
Invalid Table Name on App Service deploy

### ISSUE THREAD

**Issue by jsacapdev** [Azure/azure-functions-durable-extension#976] opened 2019-10-17 16:39 UTC
### Description

If my durable function is deployed to an app service i get this error:

```
The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.DurableTask: Task hub name 'dash-breaks-this' should contain only alphanumeric characters excluding '-' and have length up to 50. Microsoft.WindowsAzure.Storage: Invalid table name. Check MSDN for more information about valid table naming.
```

### Expected behavior

I should see the function app is running page.

### Actual behavior

I get the error above. Also trying to hit the app service I get:

`Function host is not running.`

### Relevant source code snippets

See the following respository for the code, and also how the resources were created (using the AZ CLI)

https://github.com/jsacapdev/dashbreaks

### Known workarounds

This seems to indicate it was a problem before and it was fixed:

https://github.com/Azure/azure-functions-durable-extension/issues/505

### App Details

See repository above.

### Screenshots

![image](https://user-images.githubusercontent.com/10151920/67029372-128ef500-f105-11e9-8c74-999d50d1c49e.png)

### If deployed to Azure

See repository for how to create.

**Comment by cgillum** [comment] 2019-10-17 17:21
@ConnorMcMahon can you take a look at this? I suspect it's caused by the new logic which derives the task hub name from the site name. We'll need to do some sanitization to avoid this kind of problem.

@jsacapdev You should be able to work around this by defining a task hub name in your host.json file:

```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "MyTaskHub"
    }
  }
}
```

**Comment by rouafi** [comment] 2019-10-25 09:25
@cgillum hi, thanks for the workaround but I am still not able to make it work.
Any idea ? 
My function is using the package : Microsoft.Azure.WebJobs.Extensions.DurableTask version : 2.0.0-beta3

**Comment by cgillum** [comment] 2019-11-01 05:48
Fixed with https://github.com/Azure/azure-functions-durable-extension/pull/1010

**Closed by cgillum** 2019-11-01 05:48 UTC
Labels: bug, fix-ready
