### ISSUE TITLE
DurableFunctionsHubHistory null input on activities

### ISSUE THREAD

**Issue by mark-r-cullen** [Azure/azure-functions-durable-extension#595] opened 2019-02-01 15:51 UTC
I'm not sure if this is a bug or we're just missing something, but it seems like in this table the input to an activity is always null. We can see the result of an activity but not the input. Orchestrator inputs seem fine. Is there some config option to enable logging of activity inputs that we have missed?

This came up as we were trying to diagnose an issue yesterday / earlier today where the only thing we could think that happened, was that the durable function / task framework somehow hadn't serialized / deserialized a result properly. 

e.g the code below is basically what we're doing. Nothing special. It looked like activity 2 received just a new SomeResultModel() rather than... the actual result. Without being able to see the input to the activity it's difficult to confirm that this is what happened though.

// Also independently writes some values of this result to table storage
SomeResultModel result = await context.CallActivityAsync("Activity1", new Activity1Input());

// Activity 2 threw an exception as a value on activity 1 result was <= 0, however we can see in table storage it was > 0 ... (and less than int.MaxValue etc)
await context.CallActivityAsync("Activity2", new Activity2Input { Activity1Result = result });

**Comment by cgillum** [comment] 2019-02-01 15:58
This is by design. The activity input does not need to be recorded in the history table for durability (it's already stored in the queue messages), which is why it was excluded. You should be able to get more information from Application Insights traces, however. By default AI will show your the number of bytes in the payload. There is host.json setting you can apply to log the actual serialized input json.

**Comment by mark-r-cullen** [comment] 2019-02-01 16:01
Aha, brill thank you! I figured we were probably missing something obvious. Will take a look at that. Hopefully this will give us more of an idea of what's going on... if we can reproduce it.

**Comment by cgillum** [comment] 2019-02-01 20:49
Sounds good. I'll close this for now. Let us know if you run into anything else that you think might be an issue with the extension.

**Closed by cgillum** 2019-02-01 20:49 UTC
