### ISSUE TITLE
JSON Parsing Exception Occurs When Replaying Completed Function

### ISSUE THREAD

**Issue by kaftw** [Azure/azure-functions-durable-extension#93] opened 2017-11-16 02:59 UTC
It appears I've gotten into a situation where my orchestrator function throws an exception when replaying an awaited function call that succeeded previously.  The exception it throws is: 
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {.
```

I'm not even sure exactly why this is happening, but it happens consistently for this particular function call.  The arguments passed to this function is a class with the following layout:

```csharp
public class PublisherFilterArgs
{
    public int AdvertiserId { get; set; }
    public AdvertiserObjectTypeEnum AdvertiserType { get; set; }
    public string Description { get; set; }
    public ListFilterTypeEnum FilterType { get; set; }
    public int PublisherId { get; set; }
    public PublisherObjectTypeEnum PublisherType { get; set; }
}
```

The enumeration types are attributed to use the Newtonsoft `StringEnumConverter`.  After the initial call to the function that accepts this argument, a timer is created and puts the orchestrator to sleep for ten minutes.

Here is the function call from the orchestrator:

```csharp
await UpdatePublisherFilter(
    context,
    PublisherObjectTypeEnum.company,
    company.ID,
    ListFilterTypeEnum.exclude,
    AdvertiserObjectTypeEnum.company,
    2,
    "exclude company 2");
```

Here is the implementation of the `UpdatePublisherFilter` method:

```csharp
private static async Task UpdatePublisherFilter(DurableOrchestrationContext context, PublisherObjectTypeEnum pubType, int pubId, ListFilterTypeEnum filterType, AdvertiserObjectTypeEnum advType, int advId, string description)
{
    var filterArgs = new PublisherFilterArgs
    {
        PublisherType = pubType,
        PublisherId = pubId,
        FilterType = filterType,
        AdvertiserType = advType,
        AdvertiserId = advId,
        Description = description
    };

    await context.CallActivityAsync("UpdatePublisherFilter", filterArgs);
    await context.CreateTimer(context.CurrentUtcDateTime.AddMinutes(10), new CancellationToken());
}
```

The exception is thrown after the `await context.CallActivityAsync("UpdatePublisherFilter", filterArgs);` call is executed the second time during replay.  I apologize if this is unclear.  Please let me know if you need anything further.

**Comment by cgillum** [comment] 2017-11-16 16:09
I think I understand what you're saying. This is odd because your `CallActivityAsync` call doesn't actually return a value, so I would expect it to be doing any deserialization.

Did you start an instance of this orchestration and then make changes to the code before the instance completed? Code changes can break existing instances in unexpected ways as described in the [versioning documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-versioning). I'm not sure whether that could be the case here.

Are you able to reproduce the problem locally? If so, is it possible to get a full callstack? If not, are you able to get more information from [Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-diagnostics#application-insights)? Having a callstack would make it much easier to track down the problem.

**Comment by kaftw** [comment] 2017-11-16 16:14
That function _does_ return a value, but it's being ignored.

**Comment by kaftw** [comment] 2017-11-16 16:38
It seems like that resolves my issue.

**Comment by kaftw** [comment] 2017-11-16 18:46
While my issue is fixed, there may still be a bug here, so I'm posting the stack trace just in case it's found to be useful.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1. at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType) at Newtonsoft.Json.JsonTextReader.ReadAsString() at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType) at DurableTask.Core.Serializing.JsonDataConverter.Deserialize(String data, Type objectType) at DurableTask.Core.TaskOrchestrationContext.d__14.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at DurableTask.Core.TaskOrchestrationContext.d__13`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at DurableTask.Core.TaskOrchestrationContext.d__12`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.Azure.WebJobs.DurableOrchestrationContext.d__52`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Microsoft.Azure.WebJobs.DurableOrchestrationContext.d__44`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at PI.CS.PublisherFilterTests.TestManager.d__2.MoveNext() in C:\Source\cs-asynchronous-workflow-tests\PI.CS.PublisherFilterTests\PI.CS.PublisherFilterTests\TestManager.cs:line 170 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at PI.CS.PublisherFilterTests.TestManager.d__0.MoveNext() in C:\Source\cs-asynchronous-workflow-tests\PI.CS.PublisherFilterTests\PI.CS.PublisherFilterTests\TestManager.cs:line 44

**Comment by cgillum** [comment] 2017-11-16 22:00
Ah, I see! Yes, this definitely looks like a bug we should fix, especially since it's very non-intuitive. Thanks for reporting it.

**Comment by cgillum** [comment] 2017-11-16 22:38
I was able to reproduce the issue locally and pushed a fix, which will go out in the next release.

**Closed by cgillum** 2017-11-16 22:38 UTC
