### ISSUE TITLE
DurableOrchestrationStatus cannot be returned from an activity function

### ISSUE THREAD

**Issue by praveena-m** [Azure/azure-functions-durable-extension#388] opened 2018-07-12 23:39 UTC
I have an orchestration trigger "KMA-Orch-Singleton" that calls an activity function "KMA-GetOrchestrationStatus". 

**Issue**: I get the correct runtimestatus when I call await starter.GetStatusAsync(instanceId); in activity function i.e RunTimeStatus = "Completed". But when activity function is replayed the value is coming as new instance of DurableOrchestrationStatus class with RunTimeStatus = "Running" (Not the actual result of an activity function). Please refer the attached screenshots.

> Azure runtime version : 1.0
> FUNCTIONS_EXTENSION_VERSION : ~1

![orchstatus](https://user-images.githubusercontent.com/1097942/42664719-0e919762-85f1-11e8-8eb5-736ae75a9508.png)

![wrongorchstatus](https://user-images.githubusercontent.com/1097942/42664718-0e76da1c-85f1-11e8-979e-9c2c5ded46b8.png)

```
[FunctionName("KMA-GetOrchestrationStatus")]
public static async Task<DurableOrchestrationStatus> GetOrchestrationStatus([ActivityTrigger] DurableActivityContext ctx, [OrchestrationClient]DurableOrchestrationClient starter)
{
	try
	{
		var instanceId = ctx.GetInput<string>();
		var status = await starter.GetStatusAsync(instanceId);
		return status;
	}
	catch
	{
		throw;
	}
}


[FunctionName("KMA-Orch-Singleton")]
public static async Task SingletonOrchestration([OrchestrationTrigger]DurableOrchestrationContext ctx, [OrchestrationClient] DurableOrchestrationClient starter)
{
	try
	{
		(string functionName, string instanceId, QueueMessage queueMsg) = ctx.GetInput<(string, string, QueueMessage)>();

		// Check if an instance with the specified instanceId already exists.
		var durableOrchestrationStatus = await ctx.CallActivityAsync<DurableOrchestrationStatus>("KMA-GetOrchestrationStatus", instanceId);
		var runtimeStatus = durableOrchestrationStatus.RuntimeStatus;
	}
	catch (Exception ex)
	{
		logger.LogAllExceptions(ex);
	}
}
```

**Comment by cgillum** [comment] 2018-07-12 23:49
It's not just the status - all the fields are being reset to their default values. "Running" just happens to be the default value for the RuntimeStatus property. It looks to me like there is a serialization problem on the return value of your activity function.

Does it work if you define your own type, instead of using the built-in `DurableOrchestrationStatus` class?

**Comment by praveena-m** [comment] 2018-07-12 23:51
Yes it works, if I just return RunTimeStatus property.

**Comment by cgillum** [comment] 2018-07-12 23:59
I think the problem is that the properties in the `DurableOrchestrationStatus` have public getters but internal setters, so its not possible to correctly serialize instances of this type.  This is something we can consider changing.

**Comment by SimonLuckenuik** [comment] 2018-07-13 11:56
Referencing this issue, since closely related: https://github.com/Azure/azure-functions-durable-extension/issues/65

Currently, all my entities are immutables, except for those persisted by Durable Functions, since my setters are private to be immutable.

**Comment by cgillum** [comment] 2018-10-25 03:31
The fix for this has been merged, and will go out with the next release.

**Closed by cgillum** 2018-10-25 03:31 UTC
Labels: enhancement, help wanted
