### ISSUE TITLE
Orchestration loops forever when terminated

### ISSUE THREAD

**Issue by markheath** [Azure/azure-functions-durable-extension#146] opened 2018-01-29 22:01 UTC
I'm experimenting with eternal orchestrations, where I call an activity, sleep with a timer, and then `ContinueAsNew`. After its run for a few loops I attempt to terminate the orchestration, which returns a 202 accepted. 

Once I have done this, my activity function doesn't get called anymore, but when I query the orchestration status, I still get `runtimeStatus` of `Running`. 

```js
{
    runtimeStatus: "Running",
    input: 5,
    output: null,
    createdTime: "2018-01-29T21:16:01Z",
    lastUpdatedTime: "2018-01-29T21:16:11Z"
}
```

Then every five minutes the functions runtime (I'm testing locally) will run the orchestrator function. I can hit breakpoints and step through, but it doesn't actually call the activity function - it just steps through the whole orchestrator to continueasnew.

```
[29/01/2018 21:32:56] Function started (Id=6aa34ab0-0d59-4d97-8c49-aaf5ab48dbc8)
[29/01/2018 21:32:56] Executing 'O_PeriodicTask' (Reason='', Id=6aa34ab0-0d59-4d97-8c49-aaf5ab48dbc8)
[29/01/2018 21:32:56] c611b9c068754d078d1dc3419bb0c4ef: Function 'O_PeriodicTask (Orchestrator)', version '' started. IsReplay: True. Input: (4 bytes). State: Started. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[29/01/2018 21:32:56] c611b9c068754d078d1dc3419bb0c4ef: Function 'A_PeriodicActivity (Activity)', version '' scheduled. Reason: O_PeriodicTask. IsReplay: True. State: Scheduled. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[29/01/2018 21:32:56] c611b9c068754d078d1dc3419bb0c4ef: Function 'A_PeriodicActivity (Activity)', version '' completed. ContinuedAsNew: False. IsReplay: True. Output: (replayed). State: Completed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[29/01/2018 21:32:56] c611b9c068754d078d1dc3419bb0c4ef: Function 'O_PeriodicTask (Orchestrator)', version '' is waiting for input. Reason: CreateTimer:2018-01-29T21:16:41.8355378Z. IsReplay: True. State: Listening. HubName: DurableFunctionsHub. AppName: . SlotName: .  ExtensionVersion: 1.1.0.0.
[29/01/2018 21:32:56] c611b9c068754d078d1dc3419bb0c4ef: Function 'O_PeriodicTask (Orchestrator)', version '' was resumed by a timer scheduled for '2018-01-29T21:16:41.8355378Z'. IsReplay: False. State: TimerExpired. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[29/01/2018 21:32:56] c611b9c068754d078d1dc3419bb0c4ef: Function 'O_PeriodicTask (Orchestrator)', version '' completed. ContinuedAsNew: True. IsReplay: False. Output: (4 bytes). State: Completed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[29/01/2018 21:32:56] Function completed (Success, Id=6aa34ab0-0d59-4d97-8c49-aaf5ab48dbc8, Duration=20ms)
[29/01/2018 21:32:56] Executed 'O_PeriodicTask' (Succeeded, Id=6aa34ab0-0d59-4d97-8c49-aaf5ab48dbc8)
```

My orchestrator looks like this (n.b. `timesRun` doesn't increase after I call the terminate API, `GetInput` returns the same value every time from then on):

```cs
[FunctionName(OrchestratorNames.PeriodicTask)]
public static async Task<int> PeriodicTask(
   [OrchestrationTrigger] DurableOrchestrationContext ctx,
   TraceWriter log)
{
    var timesRun = ctx.GetInput<int>();
    timesRun++;
    if (!ctx.IsReplaying)
        log.Info($"Starting the PeriodicTask orchestrator {ctx.InstanceId}, {timesRun}");
    await ctx.CallActivityAsync(ActivityNames.PeriodicActivity, timesRun);
    var nextRun = ctx.CurrentUtcDateTime.AddSeconds(30);
    await ctx.CreateTimer(nextRun, CancellationToken.None);
    ctx.ContinueAsNew(timesRun);
    return timesRun;
}
```
The activity function just writes a log message.

When I stop the local runtime, I can see that there are messages in the queues relating to this orchestration, with the dequeue count slowly ramping:

```
{
    "$type": "DurableTask.AzureStorage.MessageData, DurableTask.AzureStorage",
    "ActivityId": "48ecdf76-18af-4fa1-a0cd-bc2b7534e9cf",
    "TaskMessage": {
        "$type": "DurableTask.Core.TaskMessage, DurableTask.Core",
        "Event": {
            "$type": "DurableTask.Core.History.ExecutionTerminatedEvent, DurableTask.Core",
            "EventType": 3,
            "Input": null,
            "EventId": -1,
            "IsPlayed": false,
            "Timestamp": "2018-01-29T21:16:41.7705083Z"
        },
        "SequenceNumber": 0,
        "OrchestrationInstance": {
            "$type": "DurableTask.Core.OrchestrationInstance, DurableTask.Core",
            "InstanceId": "c611b9c068754d078d1dc3419bb0c4ef",
            "ExecutionId": null
        }
    }
}
```
(dequeue count 14)

and
```
{
    "$type": "DurableTask.AzureStorage.MessageData, DurableTask.AzureStorage",
    "ActivityId": "8530befa-9c71-44cd-aa3f-dcf978ee7977",
    "TaskMessage": {
        "$type": "DurableTask.Core.TaskMessage, DurableTask.Core",
        "Event": {
            "$type": "DurableTask.Core.History.TimerFiredEvent, DurableTask.Core",
            "EventType": 11,
            "TimerId": 1,
            "FireAt": "2018-01-29T21:16:41.8355378Z",
            "EventId": -1,
            "IsPlayed": false,
            "Timestamp": "2018-01-29T21:16:11.8715383Z"
        },
        "SequenceNumber": 0,
        "OrchestrationInstance": {
            "$type": "DurableTask.Core.OrchestrationInstance, DurableTask.Core",
            "InstanceId": "c611b9c068754d078d1dc3419bb0c4ef",
            "ExecutionId": "3c030e05a3ae48b5aad41b1004ad7776"
        }
    }
}
```
(dequeue count 14).

In fact it seems quite easy to get into the situation where messages for dead orchestrations get stuck in the queues with ever increasing dequeue counts - I have a whole host of them left over in my queues with high dequeue counts, several for orchestrations I thought had ended successfully.

I haven't tried replicating this in a live function app yet, but obviously its not a good situation if a terminated orchestration can get stuck in a state where its orchestrator function keeps running indefinitely (although presumably there's a max queue message lifetime that will eventually kill this off).

Is this a known issue or related to testing locally?

**Comment by chilberto** [comment] 2018-01-31 03:20
Hello Mark, I am running using Azure for my testing and I recreated the periodic task orchestration.  After terminating the orchestration, I received a correct response:
![image](https://user-images.githubusercontent.com/20585509/35603441-4591758a-06a2-11e8-81ab-1df6d1c6452d.png)

I can also confirm that the orchestration no longer is launched periodically.  Because of this I believe this is an issue related to the simulator.

I will retry in the simulator to see if I get the same result testing locally.

Cheers,
Jeff

**Comment by markheath** [comment] 2018-01-31 06:57
thanks Jeff, that's good to know. I'm hoping to have time soon to do a bit more testing of this in the cloud to be sure it terminates reliably.

**Comment by markheath** [comment] 2018-02-01 21:45
Looks like it's working ok in the cloud so that's good - my orchestration terminates and the orchestration function doesn't get called again.

I am still noticing that it seems easy to end up with messages in the task hub control queues that relate to dead orchestrations that sit around for a long time ramping up dequeue count. Is this something to be concerned about or can they safely be ignored?

**Comment by bestcoder** [comment] 2018-02-01 22:49
I am running into what seems like a similar issue to this one. My orchestration is running locally using the simulator and is using an Azure storage account. After I start it once using a version of the HttpStarter sample, it basically never stops running, even though I have it setup as a singleton and do not use ContinueAsNew. I have a similar result when I supposedly terminate it. Says it terminated successfully but it really isn't terminated.

Subsequently, after I start it in the debugger, a few minutes later it self-executes and writes IsReplay: True to the log and then completes with it set to false. It then continues to run indefinitely, and IsReplay is always false. 

This is what it writes to the log:

`[02/01/2018 10:22:41 PM] Job host started
[02/01/2018 10:29:51 PM] Function started (Id=70ddc285-c820-4407-8907-eb6c65cf58a9)
[02/01/2018 10:29:51 PM] Executing 'StatusOrchestration' (Reason='', Id=70ddc285-c820-4407-8907-eb6c65cf58a9)
[02/01/2018 10:29:51 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' started. IsReplay: True. Input: (16 bytes). State: Started. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:29:51 PM] Getting units for status check from data source
[02/01/2018 10:29:51 PM] 1: Function 'GetUnits (Activity)', version '' scheduled. Reason: StatusOrchestration. IsReplay: True. State: Scheduled. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:29:51 PM] Found 0 active status check units
[02/01/2018 10:29:51 PM] Failed updates: 0
[02/01/2018 10:29:51 PM] Successful updates: 0
[02/01/2018 10:29:51 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' completed. ContinuedAsNew: False. IsReplay: False. Output: (4 bytes). State: Completed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:29:51 PM] Function completed (Success, Id=70ddc285-c820-4407-8907-eb6c65cf58a9, Duration=96ms)
[02/01/2018 10:29:51 PM] Executed 'StatusOrchestration' (Succeeded, Id=70ddc285-c820-4407-8907-eb6c65cf58a9)
[02/01/2018 10:32:24 PM] Function started (Id=847f7397-df96-45e7-ab5e-653cdc0abd3a)
[02/01/2018 10:32:24 PM] Executing 'StatusOrchestration' (Reason='', Id=847f7397-df96-45e7-ab5e-653cdc0abd3a)
[02/01/2018 10:32:24 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' started. IsReplay: True. Input: (16 bytes). State: Started. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:32:24 PM] Getting units for status check from data source
[02/01/2018 10:32:24 PM] 1: Function 'GetUnits (Activity)', version '' scheduled. Reason: StatusOrchestration. IsReplay: True. State: Scheduled. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:32:24 PM] Found 0 active status check units
[02/01/2018 10:32:24 PM] Failed updates: 0
[02/01/2018 10:32:24 PM] Successful updates: 0
[02/01/2018 10:32:24 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' completed. ContinuedAsNew: False. IsReplay: False. Output: (4 bytes). State: Completed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:32:24 PM] Function completed (Success, Id=847f7397-df96-45e7-ab5e-653cdc0abd3a, Duration=12ms)
[02/01/2018 10:32:24 PM] Executed 'StatusOrchestration' (Succeeded, Id=847f7397-df96-45e7-ab5e-653cdc0abd3a)
[02/01/2018 10:34:59 PM] Function started (Id=86e6b86b-c60e-4697-8654-1be723176172)
[02/01/2018 10:34:59 PM] Executing 'StatusOrchestration' (Reason='', Id=86e6b86b-c60e-4697-8654-1be723176172)
[02/01/2018 10:34:59 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' started. IsReplay: True. Input: (16 bytes). State: Started. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:34:59 PM] Getting units for status check from data source
[02/01/2018 10:34:59 PM] 1: Function 'GetUnits (Activity)', version '' scheduled. Reason: StatusOrchestration. IsReplay: True. State: Scheduled. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:34:59 PM] Found 0 active status check units
[02/01/2018 10:34:59 PM] Failed updates: 0
[02/01/2018 10:34:59 PM] Successful updates: 0
[02/01/2018 10:34:59 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' completed. ContinuedAsNew: False. IsReplay: False. Output: (4 bytes). State: Completed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:34:59 PM] Function completed (Success, Id=86e6b86b-c60e-4697-8654-1be723176172, Duration=9ms)
[02/01/2018 10:34:59 PM] Executed 'StatusOrchestration' (Succeeded, Id=86e6b86b-c60e-4697-8654-1be723176172)
[02/01/2018 10:37:32 PM] Function started (Id=4c91dd21-b6b7-4aad-b78b-ac1d71a6d615)
[02/01/2018 10:37:32 PM] Executing 'StatusOrchestration' (Reason='', Id=4c91dd21-b6b7-4aad-b78b-ac1d71a6d615)
[02/01/2018 10:37:32 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' started. IsReplay: True. Input: (16 bytes). State: Started. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:37:32 PM] Getting units for status check from data source
[02/01/2018 10:37:32 PM] 1: Function 'GetUnits (Activity)', version '' scheduled. Reason: StatusOrchestration. IsReplay: True. State: Scheduled. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:37:32 PM] Found 0 active status check units
[02/01/2018 10:37:32 PM] Failed updates: 0
[02/01/2018 10:37:32 PM] Successful updates: 0
[02/01/2018 10:37:32 PM] 1: Function 'StatusOrchestration (Orchestrator)', version '' completed. ContinuedAsNew: False. IsReplay: False. Output: (4 bytes). State: Completed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
[02/01/2018 10:37:32 PM] Function completed (Success, Id=4c91dd21-b6b7-4aad-b78b-ac1d71a6d615, Duration=45ms)
[02/01/2018 10:37:32 PM] Executed 'StatusOrchestration' (Succeeded, Id=4c91dd21-b6b7-4aad-b78b-ac1d71a6d615)`

**Comment by cgillum** [comment] 2018-02-03 19:08
It's odd that it happens locally but not in Azure. I can't think of a good reason for observing different behavior. It would actually be easier for me to investigate if it were in Azure because then I could see the lower level ETW traces that are emitted by the messaging layer. :)

@tohling would you mind taking a look into this? The multiple dequeue count on the message is suspicious and would suggest that messages are not getting deleted when they should be. Relevant code is here (in DurableTask.AzureStorage): https://github.com/Azure/durabletask/blob/azure-functions/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs

**Comment by cgillum** [comment] 2018-02-10 01:23
I tried to reproduce the issue using by writing an infinite loop orchestration:

```csharp
[FunctionName("InfiniteLoop")]
public static void InfiniteLoop([OrchestrationTrigger] DurableOrchestrationContext ctx)
{
    ctx.ContinueAsNew(null);
}
```
I ran it several times locally using the Azure Storage Emulator and I was able to successfully terminate it each time (verified by observing that there was no more output from the functions runtime). One issue I observed is that the status was set to "ContinuedAsNew" instead of "Terminated".

```http
HTTP/1.1 202 Accepted
Content-Type: application/json; charset=utf-8
Date: Sat, 10 Feb 2018 01:14:26 GMT
Location: http://localhost:7071/admin/extensions/DurableTaskExtension/instances/ed2120292e6f4439a6a390a2ca9a4125?taskHub=DurableFunctionsHub&connection=Storage&code=XXX
Retry-After: 5
Server: Microsoft-HTTPAPI/2.0
Transfer-Encoding: chunked

{
    "createdTime": "2018-02-10T01:10:26Z",
    "input": null,
    "lastUpdatedTime": "2018-02-10T01:10:27Z",
    "output": null,
    "runtimeStatus": "ContinuedAsNew"
}
```
But it was definitely terminated. The issue you're observing might be something different - like messages not being deleted for some reason (similar to the sub-orchestration issue you also reported), which would likely cause replays for an extended period of time.

**Comment by cgillum** [comment] 2018-02-28 21:29
So it seems like we're not able to reproduce the original issue, and there may be the possibility that it is conflated with some other known bugs. I'm going to close this for now, but please do re-open or open new issues if you are noticing something abnormal about termination that we should look at.

**Comment by cgillum** [comment] 2018-03-01 21:38
Reopening - I just repro'd this exact issue locally. I'll investigate further.

**Comment by cgillum** [comment] 2018-03-01 22:27
It looks like the terminate message may be causing some state corruption. Here is the exception coming from DurableTask.Core.dll:

```
TaskOrchestrationDispatcher-f79977801ceb41aa82701d473427e52b-0: Exception while processing workItem 87e126f0d4f54d9ca092bf67c10cf4e0 Exception: System.InvalidOperationException : Multiple ExecutionCompletedEvent found, potential corruption in state storage at DurableTask.Core.OrchestrationRuntimeState.SetMarkerEvents(HistoryEvent historyEvent)
 at DurableTask.Core.OrchestrationRuntimeState.AddEvent(HistoryEvent historyEvent, Boolean isNewEvent)
 at DurableTask.Core.OrchestrationRuntimeState.AddEvent(HistoryEvent historyEvent)
 at DurableTask.Core.TaskOrchestrationDispatcher.ProcessWorkflowCompletedTaskDecision(OrchestrationCompleteOrchestratorAction completeOrchestratorAction, OrchestrationRuntimeState runtimeState, Boolean includeDetails, Boolean& continuedAsNew)
 at DurableTask.Core.TaskOrchestrationDispatcher.<OnProcessWorkItemAsync>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at DurableTask.Core.WorkItemDispatcher`1.<ProcessWorkItemAsync>d__34.MoveNext()
```

The result is that the queue messages are getting abandoned and replayed over and over. It's possible this could be some kind of race condition involving terminate (possibly the orchestration completing and being terminated at the same time). I'll investigate further.

**Comment by cgillum** [comment] 2018-03-02 01:38
I have confirmed that this is a known issue in the Durable Task Framework (https://github.com/Azure/durabletask/issues/25). The good news is that it should be relatively easy to fix.

**Comment by cgillum** [comment] 2018-03-31 23:56
The issue has been fixed, but we still need to get a new version of **DurableTask.AzureStorage** published so we can add it as a dependency.

**Comment by cgillum** [comment] 2018-04-13 23:47
We've checked-in a fix which brings in the latest version of **DurableTask.Core**. It will go out with the next release.

**Closed by cgillum** 2018-04-13 23:47 UTC
Labels: bug, dtfx, fix-ready
