### ISSUE TITLE
Orchestration getting stuck in Running

### ISSUE THREAD

**Issue by jjohnson23112** [Azure/azure-functions-durable-extension#1459] opened 2020-09-02 13:19 UTC
### Description
After running about 1000 instances through, 2 instances seem to be stuck in a running state.  I left them overnight and they are still stuck in running.  I do not see any other activity to indicate that they are actively doing anything.  

### Expected behavior
Orchestration should have completed or failed.  Not sure why it is stuck running.

### Actual behavior
Orchestration still shows Running - status URI returns Running.  Querying the application insights shows no trace messages logged since yesterday so it appears to be truly "stuck"

### Known workarounds
I could probably kill it and restart it but wanted to leave it up here to see what you guys think

### App Details
Durable Functions extension version: I believe I am running the latest version as I don't have a version listed in my hosts.json
Azure Functions runtime version (1.0 or 2.0): 2.0
Programming language used: C#

### If deployed to Azure

Timeframe issue observed: 9/1/2020
Function App name:SLAzureFunctionsAFDiscoveryPRD
Orchestration instance ID(s): 4511e893e7da47b79a13fd6d294853f0

**Comment by Tri125** [comment] 2020-09-08 18:33
We have the same issue in our application. We started seeing it a few months ago. We were thinking that #1380 could be the cause? We updated to 2.2.2 last week but we had it before.

Durable Functions extension version: 2.2.2
Azure Functions runtime version: 3.0
Programming language used: C#


Our code follow this pattern:

Every few minutes a time trigger start an orchestration.

The orchestration retrieve a list of configurations and create a deterministic instanceId from their GUID.

For each configuration, check the OrchestrationRuntimeStatus. If it's _ContinuedAsNew_, _Running_, or _Pending_, we continue to the next config. If the status is not one of those 3 we create a suborchestration with the deterministic instanceId.

**Comment by ConnorMcMahon** [comment] 2020-09-29 23:17
@Tri125,

Unfortunately, there are many different reasons an orchestration could get stuck, so we need to handle each investigation separately. Do you mind filing a separate issue with the appropriate information so that we can track your investigation there?

**Comment by ConnorMcMahon** [comment] 2020-10-16 19:54
@jjohnson23112 

Thanks for your patience with this issue.

There is certainly some strange behavior going on here.

I noticed that the pattern of your orchestration is to fan-out/fan-in in a repeated manner, with some intermediate steps between each fan-out/fan-in. Your orchestration appears to be getting stuck on one of the fan-out/fan-ins. Specifically, 38 activities were scheduled to fan out. What is odd, is that all 38 activities were completed and processed as completed by your orchestration, but then no further work was scheduled (i.e. your code got stuck at the `Task.WhenAll()` when it should have completed).

From what I can tell, there were no failure from a platform level that would have caused the `await Task.WhenAll()`. It's possible that there is some bug that I am missing that our telemetry does not expose, but that seems doubtful. At one point, we had an issue where large messages (i.e. inputs/outputs > ~30-60KB that we store in blob storage) would cause some issues, but this bug was fixed by the version of the code you were using.

The most likely reason the `Task.WhenAll()` would not continue on once all the activities had completed would be if you had some non-deterministic code, or if you were editing the tasks in some strange way (maybe `ConfigureAwait()`?). Unfortunately, without orchestration code, it will be hard to debug further.

In the meantime, I recommend upgrading to our latest version, as you are on 2.1.1 and we have made various reliability improvements since then.

**Comment by jjohnson23112** [comment] 2020-10-16 20:05
@ConnorMcMahon I can provide the code - can you send me an email address and I can get that over to you?  We are not doing (as far as we know) any non-deterministic things in the orch code. 

Also- you mention upgrading to 2.1.1 whats the best way to upgrade?

**Comment by ConnorMcMahon** [comment] 2020-10-16 20:32
@jjohnson23112,

You can contact me at Connor.McMahon@microsoft.com to send your code.

Assuming you are using a precompiled C# function app, you should just be able to update the package reference to Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.3.0 in your .csproj file.

**Comment by ConnorMcMahon** [comment] 2020-11-04 18:44
@jjohnson23112, it has been a few weeks, and I still have not received an email. Just checking to make sure that you are still having this issue.

I also recommend now upgrading to v2.3.1, as that is our latest version.

**Comment by jjohnson23112** [comment] 2020-11-04 18:53
> @jjohnson23112, it has been a few weeks, and I still have not received an email. Just checking to make sure that you are still having this issue.
> 
> I also recommend now upgrading to v2.3.1, as that is our latest version.

Hey Connor - I sent hte code right when you asked a few weeks ago and just sent it now.  Can you check again? I included a link to a dropbox with the code in it.  Maybe it got caught in your spam filter?

**Comment by ConnorMcMahon** [comment] 2021-04-01 21:45
@jjohnson23112 and I discussed this offline, and the issue was that large orchestration histories were causing the 1.5GB limit for consumption function apps to cause constant app recycles. This is the perfect scenario where #1682 would help.

**Closed by ConnorMcMahon** 2021-04-01 21:45 UTC
Labels: Needs: Attention :wave:
