### ISSUE TITLE
Log filtering possibly not working for "...: Lease renewal with token ... succeeded"

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-functions-durable-extension#1561] opened 2020-11-14 04:04 UTC
In our Durable Functions, host.json, I have configured:
   
```
"logging": {
        "fileLoggingMode": "always",
        "logLevel": {
            "default": "Information",
            "Host": "Warning",
            "Function": "Warning",
            "Host.Aggregator": "Information",
            "Host.Results": "Warning",
            "Host.Triggers.DurableTask": "Warning",
            "DurableTask.AzureStorage": "Warning",
            "DurableTask.Core": "Warning"
        }
[...]
}

```
But in App Insights, I'm still getting verbose trace messages like:
> knowledge-control-06: Lease renewal with token d6ebcda9-9b72-47b5-ad83-c5d0e03f53d4 succeeded

From the docs, DurableTask.AzureStorage looks to be the right log filter, so any help in how to filter these out would be appreciated!

**Comment by cgillum** [comment] 2020-11-14 04:46
(Moving this to the correct repo)

Is your app running in Azure or are you using the Functions core tools? I ask because an earlier version of the core tools had a problem where filters were not being honored correctly.

**Comment by kirk-marple** [comment] 2020-11-14 04:48
Thanks, this is in Azure, and I double-checked and we're using the latest nuget packages for the durable exceptions.

**Comment by ConnorMcMahon** [comment] 2020-11-16 19:49
@kirk-marple, do your other log level filters appear to be respected?

Also, can you report what version of the Functions Runtime this is in? I want to make sure we can get a repro ourselves and pin down where this bug is happening.

**Comment by kirk-marple** [comment] 2020-11-17 23:46
@ConnorMcMahon This is with the latest, I believe.  Using .NET Core 3.1.

        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.3.1" />
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />

For other log levels (i.e. our own trace/exceptions), those are working correctly, if that's what you meant?

It's just this noise I'd like to get rid of in our App Insights, esp to save on logging data costs:
![image](https://user-images.githubusercontent.com/13594550/99464026-03700d00-28ec-11eb-8c4a-012064ab5771.png)

**Comment by ConnorMcMahon** [comment] 2020-11-17 23:51
@kirk-marple, sorry I should have clarified. You should be able to find the function host version on the Azure Portal on the main page for your Function app Resource as "runtime version". 

![image](https://user-images.githubusercontent.com/8934380/99464352-c5bfb400-28ec-11eb-8248-4edec557d12a.png)

**Comment by kirk-marple** [comment] 2020-11-17 23:52
Ah no worries, we're running 3.0.14916.0.

**Comment by kirk-marple** [comment] 2020-12-08 08:14
@bachuv Hi there, I wanted to check on the status of potentially getting this fixed.  

Normally I wouldn't care, but it actually ends up costing us money in log data usage in App Insights with all this extra noise.

**Comment by bachuv** [comment] 2020-12-08 20:37
Hi @kirk-marple, sorry for the delay! I took some time off recently, but I'm prioritizing this issue and you can expect an update by the end of the week.

**Comment by bachuv** [comment] 2020-12-11 00:30
Hi @kirk-marple, I looked into the issue and couldn't reproduce it. Do you have a Startup.cs file in your project? If you do, can you share the contents of it?

**Comment by Greg-Hitchon** [comment] 2020-12-11 02:31
Hello,

I don't quite have the same issue but it might be of some help:

Runtime version: 3.0.14916.0
When viewing "live metrics" in the Azure Portal I see something like:
![image](https://user-images.githubusercontent.com/3837138/101848964-bbc45600-3b24-11eb-9fa6-27ae1d901484.png)

With:
```{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "Host.Triggers.DurableTask": "Warning",
      "default": "Warning"
    }
  }
```
These do not actually get logged to file though. They are annoying when looking at the "live metrics" stream

**Comment by kirk-marple** [comment] 2020-12-13 18:34
Our Startup.cs is refactored into some helper classes, so it's a bit much to send over.

But I think the telemetry client would be the key part, right?

```
        public static TelemetryClient CreateTelemetryClient()
        {
            string? key = Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY");
            if (String.IsNullOrWhiteSpace(key))
                throw new ArgumentException("APPINSIGHTS_INSTRUMENTATIONKEY environment variable");

            var config = !String.IsNullOrWhiteSpace(key) ? new TelemetryConfiguration(key) : new TelemetryConfiguration();
            config.TelemetryInitializers.Add(new OperationCorrelationTelemetryInitializer());

            QuickPulseTelemetryProcessor? processor = null;

            config.TelemetryProcessorChainBuilder
                .Use((next) =>
                {
                    processor = new QuickPulseTelemetryProcessor(next);
                    return processor;
                })
                .Build();

            var quickPulse = new QuickPulseTelemetryModule();
            quickPulse.Initialize(config);
            quickPulse.RegisterTelemetryProcessor(processor);

            return new TelemetryClient(config);
        }
```

**Comment by ConnorMcMahon** [comment] 2020-12-14 17:24
Ah yes, that is likely the culprit here. You configuring your own telemetry client is likely why the host.json log category filters are being ignored.

In general, we recommend against doing custom App Insights things inside of your Startup.cs for this reason. We do have some [recommendations for doing custom logging](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services) if you want support for that. 

Note that it may not fully support everything you want to do with your current custom client. If that is the case, we will want to have you file an issue against the azure-functions-host repository to see if they could add support for the customization you need.

**Closed** 2020-12-30 06:00 UTC
Labels: Needs: Author Feedback, no-recent-activity

**Comment by xsurfer** [comment] 2024-03-29 14:23
@kirk-marple did you manage to solve this issue? 
I'm actually facing the very same, despite I am not using any custom telemetry client :(

Any idea on how to troubleshoot it further?
