### ISSUE TITLE
Add support for interfaces in ReadEntityStateAsync()

### ISSUE THREAD

**Issue by ladeak** [Azure/azure-functions-durable-extension#960] opened 2019-10-03 21:47 UTC
Currently durable API with entities seems to put developers on a CQRS pattern.
Commands can be signaled (1-way communication), orchestrators can call entities to update their state still async, but in a 2-way communication.

To query data from entities in a two way communication, but still async (using ```Tasks<T>```) can be done through orchestrators or with ```ReadEntityStateAsync``` method from non-orchestrators.
Using orchestrators we get to a pull model, someone at the very end will need to check the state of the the orchestration result.
The other option is using ```ReadEntityStateAsync```. It feels this method is exposing the internals of an entity. Instead of doing this, I would like a way an entity may provide a method to transform the state before it is being returned.

It feel today this can be achieved with an additional function (to read the entity's state, transform it before being returned), but I think this could be part of the Entity function's definition.

**Comment by olitomlinson** [comment] 2019-10-04 15:14
Very similiar, if not the same, as my ask here https://github.com/Azure/azure-functions-durable-extension/issues/885#issuecomment-519610498 - A way to run some logic and project the response would certainly be desirable, rather than bleeding out the entire state to the caller.

**Comment by sebastianburckhardt** [comment] 2019-10-04 16:51
I agree that it seems "wrong" to expose the internal representation of the entity state. It breaks encapsulation, which goes against established software engineering principles.

However, we don't really prevent users from encapsulating the state. For example, consider the counter entity example. One can use a private field for the current value.

```csharp
public class Counter
{
    [JsonProperty("value")]
    private int CurrentValue { get; set; }

    public void Add(int amount) => this.CurrentValue += amount;
    
    public Task<int> Get() => Task.FromResult(this.CurrentValue);

    [FunctionName(nameof(Counter))]
    public static Task Run([EntityTrigger] IDurableEntityContext ctx)
        => ctx.DispatchAsync<Counter>();
}
```

Now, on the client, we have to use the `Get()` method to be able to read the current value of the counter:

```csharp
var counter = await client.ReadEntityStateAsync<Counter>(entityId);
return counter.Get();
```

What we don't currently have is support for using just the interface, as in:

```csharp
var counter = await client.ReadEntityStateAsync<ICounter>(entityKey);
return counter.Get();
```

were the interface is defined as
``` csharpt
public Counter : ICounter {
   ...
}

public interface ICounter {
    void Add(int amount);
    Task<int> Get();
}
```

Perhaps it would be worth adding support for this since it provides stronger encapsulation (via interface) than the private field.

**Comment by ladeak** [comment] 2019-10-04 17:01
I would be happy with that approach. And as I understand this would be executed on the caller side, something to pay attention for.

**Comment by olitomlinson** [comment] 2019-10-04 20:02
@sebastianburckhardt I like the solution and it would be a great start!

I have a use-case where the entity state size could be considerable. Imagine a `List<string>` with a few thousand items and growing, but in a certain scenario I only need to expose the last entry in the List to the caller through a `GetLastEntry()` method. 

I'm assuming this method you propose would serialise the entire state to the caller?

**Comment by sebastianburckhardt** [comment] 2019-10-04 20:52
Yes, the entire state is transmitted every time.

Perhaps it is worth noting here that working with large entity states can be problematic (from a performance viewpoint) not just on clients, but in general: our current implementation is not optimized to deal with large states. In particular, what happens is that every time a batch of operations is ready to process, the state gets loaded/deserialized (before running the operations) and then serialized/stored (after running the operations).

**Comment by ladeak** [comment] 2019-10-04 20:57
So that means even if ```GetLastEntry()``` would run on an entity side, the whole state would be serialized/deserialized by the entity. So actually 'transmitting' the state to the call side is more efficient with one deserialize less?

On the other side, is there any optimization to use some sort of a local cache/file on the "serverless" machine running the entity? Is there a machine affinity to run the same functions on the same machine?

**Comment by sebastianburckhardt** [comment] 2019-10-04 21:04
> So actually 'transmitting' the state to the call side is more efficient with one deserialize less?

Yes, exactly. This is definitely true for the current Azure.Storage backend.

> is there any optimization to use some sort of a local cache?

Extended sessions provide some level of caching; but I think there is quite a bit of room for improvement. I believe for entities in particular, there is still a fair amount of storage traffic and serialization/deserialization that could be optimized.

**Comment by olitomlinson** [comment] 2019-10-04 21:30
@sebastianburckhardt Thank you for the warning on large entity states. This is certainly something that I shall be load testing for suitability when you GA. 

What are the concurrency characteristics of Entities in the current implementation? I'm comfortable that I understand how Orchestrations achieve a level of concurrency through the `partitionCount` property. Does the same concurrency characteristics apply to Entities?

**Comment by sebastianburckhardt** [comment] 2019-10-04 22:52
> Does the same concurrency characteristics apply to Entities?

Yes, it uses the exact same mechanism. In particular, for scaling out, you may want to increase the `partitionCount`.

**Comment by ladeak** [comment] 2019-10-07 18:02
Is there a way to assure that Read Operations does modify the entity state? Having an entity:
```csharp
public class Counter
{
    [JsonProperty("value")]
    private int CurrentValue { get; set; }

    public Task<int> Get() => Task.FromResult(+this.CurrentValue);

    [FunctionName(nameof(Counter))]
    public static Task Run([EntityTrigger] IDurableEntityContext ctx)
        => ctx.DispatchAsync<Counter>();
}
```

Calling the get from another function:

```csharp
var counter = await client.ReadEntityStateAsync<ICounter>(entityKey);
return counter.Get();
```
This would not update the state of the Counter entity (or at least it would not persist), right?

I seems to end up creating Orchestrator functions so that I can [coordinate](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities#entity-coordination) two entities. This seems to make my functions extra chatty, I really would like to have an entity make 2-way calls. This also makes me create some boilerplate code.

**Comment by sebastianburckhardt** [comment] 2019-10-07 21:09
Yes, what you get on the client is not the actual entity, just a snapshot of some past state of the entity. If you are modifying that state, you are just modifying the object in memory, it has no other effect.

By design, what you can do inside clients and entities is very limited. You really need to use orchestrators to do multi-step or multi-object things. This is a design invariant; though it may be possible to figure out ways to reduce the boilerplate overhead of defining orchestrations.

BTW, you may want to use C# tuples for operation arguments to reduce the boilerplate. It helps a little.

**Comment by ladeak** [comment] 2019-10-10 06:08
1, Is there a way so that Entities could expose GET operations (or Read from CRUD) through an HTTP API instead of the current ReadEntityStateAsync? 

2, This might worth its own github question: is there a way to replace Newtonsoft.Json serialization to custom or say System.Text.Json?

**Comment by ladeak** [comment] 2019-10-10 21:33
I would also like if there was a proxy when calling an entity. Currently it is
```csharp
var entityKey = new EntityId(nameof(MyEntityActor), actorId.ToString());
await _context.CallEntityAsync(entityKey, nameof(MyEntityActor.Operation), optionalArguments);
```
and a proxy could be
```csharp
var entityKey = new EntityId(nameof(MyEntityActor), actorId.ToString());
var proxy = _contenxt.CreateProxy<IMyEntityActor>(entityKey);
await proxy.Operation(optionalArguments);
```

This would cleanup input arguments and code as well. What do you think @sebastianburckhardt ?

**Comment by sebastianburckhardt** [comment] 2019-10-10 21:47
We already support the use of entity proxies from within orchestrations. Are you specifically asking for the same functionality on clients? As stated, this is not currently possible - we know it is a desirable feature, but the implementation simply does not have the internal wiring required to send response messages to the client. It would require somewhat substantial work to add that, so it probably won't be supported in the near future. 

If you want the top experience (full consistency & type-checked access via interfaces for both reading and updating) you will need to use orchestrations to access the entities, for now.

**Comment by ladeak** [comment] 2019-10-10 21:54
Ah sorry I meant the last example with the proxy from orchestrator functions.

**Comment by ladeak** [comment] 2019-10-16 05:32
Having a limited number of input arguments seems to be doable if the proxy wraps input args and DispatchAsync unwraps them. Is that is something doable, you are looking into it?

**Comment by sebastianburckhardt** [comment] 2019-10-16 19:49
I would recommend just using a [C# tuple type](https://docs.microsoft.com/en-us/dotnet/csharp/tuples) for the input. Then the C# compiler already does all the work. Note that the tuple can have named and typed components, mimicking multiple arguments. For example:

```csharp
public void SomeOperation((int a, int b) input)
{
    var sum = input.a + input.b;
}
```

and you can call it like this:
```csharp
proxy.SomeOperation((5, 8));
```

**Comment by ladeak** [comment] 2019-10-16 19:52
Yep, using that currently.

**Comment by ladeak** [comment] 2019-10-23 10:56
When MyEntity type has a ctr and using ctr dependency injection, the ReadEntityStateAsync will not do the dependency injection.
```ReadEntityStateAsync<MyEntity>(new EntityId(nameof(MyEntity), id));```

Is there a suggested workaround?

**Comment by ElanHasson** [comment] 2019-10-23 12:49
I worked around this by moving my state properties to a base class and using ReadEntityStateAsync<MyEntityState>

**Comment by ConnorMcMahon** [comment] 2020-02-25 00:29
@ladeak 

I'm going to limit this issue to talking about allowing `ReadEntityStateAsync` with interfaces, as that solution seems to address the initial question.

I am opening a separate issue for the dependency injection with `ReadEntityStateAsync`. I'm not positive that this is something we could enable support for, but at the very least we should document it better.

**Closed** 2020-02-25 06:22 UTC
Labels: enhancement, needs-discussion
