### ISSUE TITLE
Orchestrator takes 30 minutes to start, control queue count is very high

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-functions-durable-extension#1999] opened 2021-11-05 09:27 UTC
### Description
Our durable functions take long to process and causing SessionLockLostException. When I checked the control queue tables, there seems to be thousands of messages in queue with high Dequeue Count. This issue started happening simultaneously at a similar time in some of our environments. We have a few durable functions that are triggered by service bus

What does it mean when a message has a large number of dequeue count?
We also have orchestrators with status RUNNING for 2 days

This is a big blocking issue, so we can really use the help. I created a microsoft support ticket but still no reply in 1 week

### Expected behavior
Orchestrator functions take less than a minute to process

### Actual behavior
Orchestrator functions take time to start after being scheduled (I saw in 30+ minutes in one case)

### Relevant source code snippets
N/A

### Known workarounds
We tried reducing filtering the messages in the trigger function to schedule less orchestrator but this doesn't help. Also tried increasing the instance to 2 but also doesn't help

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.5.1
- **Azure Functions runtime version (1.0 or 2.0)**: ~3
- **Programming language used**: C#

### Screenshots
![image](https://user-images.githubusercontent.com/7829826/140487783-34869a25-924e-4c15-ac78-858de0a3ad1e.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: from 21st October 2021 ~9:44 AM until now
- **Function App name**: see orchestration instance ID, this also happens in the same function app in other environments
- **Function name(s)**: N/A
- **Azure region**: West Europe
- **Orchestration instance ID(s)**: 0a6ac9f1b1004e949e235e678a37f322
- **Azure storage account name**: 

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment] 2021-11-05 18:05
Issues like this typically happen if something is causing your process to crash repeatedly. Have you tried taking a look at the [Azure Functions Diagnose and Solve Problems](https://docs.microsoft.com/en-us/azure/azure-functions/functions-diagnostics) tool? It can point out general app health issues and you can search "Durable Functions" to get visibility into DF-specific issues that can be detected by internal telemetry. It would be great if you could take a look at that and share any findings you have.

**Comment by cgillum** [comment] 2021-11-05 19:23
I was able to find the name of your app using the instance ID you provided. It took some time because the time range you provided doesn't match the time range of the instance ID.  However, I did notice an issue that explains the delays and unfortunately, it's not one that will be displayed by the Diagnose and Solve Problems tool (although you would see it if you enabled [Durable Task Framework Logging](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp#durable-task-framework-logging)).

Basically, the following exception is being observed:

```
Microsoft.WindowsAzure.Storage.StorageException: Element 1 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UploadHistoryBatch(String instanceId, String sanitizedInstanceId, String executionId, TableBatchOperation historyEventBatch, StringBuilder historyEventNamesBuffer, Int32 numberOfTotalEvents, Int32 episodeNumber, Int32 estimatedBatchSizeInBytes, String eTagValue, Boolean isFinalBatch) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1503
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1292
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1094
Request Information
RequestID:e91c80f7-1002-005b-7928-cf0ff4000000
RequestDate:Mon, 01 Nov 2021 13:55:02 GMT
StatusMessage:1:The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
ErrorCode:
ErrorMessage:1:The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.
RequestId:e91c80f7-1002-005b-7928-cf0ff4000000
Time:2021-11-01T13:55:02.7615093Z
```

This appears to be a bug in how we serialize your entity state. Normally we do size checks to avoid overrunning Azure Table storage limitations, but it appears you may have run into a corner case that we missed. Unfortunately, this error message doesn't give me enough information to know exactly what's triggering it. Two of the entities I'm seeing that are running into problems are `@xenonentity@406378032` and `@xenonentity@447809010`. These unhandled exceptions are unfortunately causing the dispatcher to dramatically slow down processing.

In terms of how to mitigate this problem, we have a few options. One option is to try and change the "xenonentity" code to save a smaller amount of state (assuming that the problem is related to state storage) - not sure if this is at all practical for you. Another option is to try to remove any state in your Azure Storage account related to these problems. A good place to start would be any queue messages that have especially high dequeue counts.  If this doesn't work or if it's not an option that you're willing to take, we could try to provide you with a private fix that handles the issue more gracefully so that these broken entities don't impact the performance of other orchestrations. Let me know what you think.

**Comment by adeliab** [comment] 2021-11-08 08:25
@cgillum thanks for the investigation. how are these entities wrongly serialized? what is the bug exactly?
is it possible for you to share the query you used to find this exception so we can check it better in the future?

regarding the fix, if i see the Input column in the @xenonentity@406378032 entity, the content is not a lot - only 7 json value properties. i'm wondering how can it be considered too large?

maybe also good for you to know, we also just found out today that the table & blob capacities in the storage account hugely increased at the time of the issue.
![image](https://user-images.githubusercontent.com/7829826/140707858-40153877-caed-4948-8a42-1a87246fbe2b.png)

and the private fix i assume will be a separate package that we need to use? how long will that take? i have a call with MS support at 2pm CET today - i'm wondering what's the best course of action.

this issue is affecting all our environments now since 21st of October so it's really urgent to be fixed.

**Comment by adeliab** [comment] 2021-11-08 08:26
also a lot of failures:

![image](https://user-images.githubusercontent.com/7829826/140708264-f97d3dad-5eee-405f-be0b-6cc024d022ac.png)

**Comment by adeliab** [comment] 2021-11-08 08:27
also a lot of "ClientOtherError" failures

![image](https://user-images.githubusercontent.com/7829826/140708370-215a9c48-b91f-4656-9a7c-c2574ce04e22.png)

**Comment by cgillum** [comment] 2021-11-08 15:15
> is it possible for you to share the query you used to find this exception so we can check it better in the future?

The query I use is going to be different than the query you use since our internal telemetry sources format data differently from what's available in Application Insights. Here's a query that I believe should help you see warnings and errors like these (based on the query that exists in [our documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp#durable-task-framework-logging)):

```kql
traces
| where customDimensions.Category startswith "DurableTask"
| where severityLevel > 1
| project
    timestamp,
    severityLevel,
    Category = customDimensions.Category,
    EventId = customDimensions.EventId,
    InstanceId = customDimensions.InstanceId,
    TaskName = customDimensions.TaskName,
    Details = customDimensions.Details,
    message,
    customDimensions
| order by timestamp asc
```

> how are these entities wrongly serialized? what is the bug exactly?

Normally entity state is stored in Azure Table storage. However, Table Storage has limits around how much data can be stored in a single table entity as well as individual properties. We have code that checks these limits and, if we find we might come close to exceeding it, instead store state in Blob Storage. However, the error message seems to indicate that we attempted to save too much data into one of the properties we write in Azure Table storage. It doesn't tell us which property exceeded the limit, however, so it's difficult for me to know exactly where the issue is.

> and the private fix i assume will be a separate package that we need to use?

Right, it would need to be a private version of the Microsoft.Azure.DurableTask.AzureStorage NuGet package. But to be clear, we don't know what the exact problem is yet and thus don't know exactly what fix is needed. In the worst case, we can handle this kind of error differently so that it won't result in long processing delays.

> also a lot of "ClientOtherError" failures

I'm guessing these are those same Azure Storage errors that I shared with you above.

**Comment by adeliab** [comment] 2021-11-08 16:18
so from the options we have:
- changing the code to save less state: i don't think this is the issue since the body of the state is not big (looking at the 2 entities you mentioned)
- deleting the state of message with the highest dequeue count: do you mean from the instance & history table? what would happen to the message in the queue - there's not an option in azure queue to remove a specific message , only dequeue from the top. and also we can't be monitoring and doing this every time. FYI we cleared the storage account (completely removing the resource) before and recreating it again, and the issue came back again
- private fix: this will be preferable but would be good to know what the fix will be (how this situation will be handled) and a timeline?

may i ask how did you come to the conclusion of those 2 entities? we had a call with Emad today, and he's not sure why you mentioned those 2 entities, he said he will check with you. 
although he proposed a 'workaround' by changing the name of the taskhub. if our function name is my-function-app, currently our taskhub is called myfunctionapp. and he said having the taskhub name the same as function app name caused issues before - even though he said it's a different issue. he suggested changing one of our environments task hub name and monitor it. if this works, it would be good to know why it works though and what issue it solved.

**Comment by cgillum** [comment] 2021-11-08 18:11
> may i ask how did you come to the conclusion of those 2 entities?

The Durable Task Framework logs that report the exception also mention the "instanceId" associated with the problem. Here is my view (using [Kusto](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/tools/kusto-explorer-using)):

![image](https://user-images.githubusercontent.com/2704139/140793087-56646b28-69be-4010-80ae-d17d0d0d4e64.png)

The `InstanceId` field encodes in it the entity's name and key, which is how I know exactly what entity is running into problems. These are just a couple that I noticed. There are other very similar error messages that are reporting a "backoff" period of 10 seconds to avoid a tight failure loop. It's my assumption that this is the reason why your orchestrations are starting slow and your control queue counts are high.

> he suggested changing one of our environments task hub name and monitor it. if this works, it would be good to know why it works though and what issue it solved.

I can't imagine why changing the task hub name would work when clearing your Azure Storage account didn't. In both cases, you're effectively recreating storage resources from scratch. The only exception would be if you had more than one app (or possibly even a single app with multiple staging slots) sharing the same task hub. Renaming the task hub used by one of them would resolve potential conflicts associated with task hub collision. By chance do you have multiple apps that use the same task hub name, or multiple staging slots for the same app that use the same task hub name?

The other interesting thing this might reveal is that the problem of delayed orchestrations isn't necessarily caused by broken entities - i.e. this could be a red herring. I'd be interested to hear if this resolves the issue for you.

> private fix: this will be preferable but would be good to know what the fix will be (how this situation will be handled) and a timeline?

All the changes we make happen on GitHub, so you can view the PR and it's description if you're interested. That said, I still want to investigate this a bit more first to see if there might be an actual code bug I can spot that might explain what's going on. Either way, in terms of timelines, there's a good chance we could get you something sometime this week.

**Comment by adeliab** [comment] 2021-11-08 20:24
> By chance do you have multiple apps that use the same task hub name, or multiple staging slots for the same app that use the same task hub name?

No, we have 1 function app with a staging slot & production slot. Each slot uses a different taskhub name.

> I can't imagine why changing the task hub name would work when clearing your Azure Storage account didn't. In both cases, you're effectively recreating storage resources from scratch.

It has been quite a puzzling issue tbh.. there were a couple of 'changes' that I thought helped the issue, if i'm not mistaken the order was:
1. Filter messages in trigger function > instead of scheduling an orchestrator for all messages, i moved the logic that checks whether the message needs to be processed to the trigger function. if the message doesn't have the right information, complete the trigger function without scheduling an orchestrator
2. Clear storage account in one of our dev environments
3. Step 1 and 2 seemed to help with the issue, I saw most messages were being processed although some sessionlocklostexception still occurred
4. And then we had a deployment mistake that caused the all dev storage accounts to be removed
5. After event 4, the issue came back again even though all dev environments basically uses new storage accounts

Emad mentioned that he noticed an issue with taskhub having the same name as function app (without the special characters). But he wasn't sure what the actual issue is and he mentioned that he hasn't spoken about it with the team. Therefore he suggested to change the taskhub name

We also noticed quite some of our entities becoming too large because of ReceivedFromInstance properties. Which causes the table storage to refer to a blob storage which I believe is related to this issue https://github.com/Azure/azure-functions-durable-extension/issues/1302

**Comment by cgillum** [comment] 2021-11-09 01:06
I'm trying to reproduce this issue locally so I can figure out how to fix the root issue. I've tried a variety of scenarios with large entity state and normal state seems to be handled fine.

> We also noticed quite some of our entities becoming too large because of ReceivedFromInstance properties.

I'm currently trying to create a repro that inflates the `ReceivedFromInstance` property with an ever growing amount of data, but I'm having trouble figuring out how this property gets set. Adding @sebastianburckhardt in case he can provide some guidance on how to create a minimal sample that generates an inflated `ReceivedFromInstance` property.

**Comment by adeliab** [comment] 2021-11-09 08:33
with changing the name of the taskhub, i don't see messages in queue/ DLQ but i still see the sessionlocklostexception happening. It happens much less than before but still happens so there's still delay in starting the orchestrator

**Comment by cgillum** [comment] 2021-11-09 15:16
Can you share a recent instance ID where you saw an unusual delay with the new taskhub name?

**Comment by adeliab** [comment] 2021-11-09 17:56
I think these 2 instances are one of them: 6b91f4329a614ff083d3787aa628e5b3 and 4812c04fb3f14a6fb7261c95123242c3
I'm a bit confused reading the history - rowkey 1 has an earlier timestamp than rowkey 0, i thought the rowkey determines the order of the history?

![image](https://user-images.githubusercontent.com/7829826/140977719-c25fcdc9-d150-4a07-9fde-b56da2baf8d2.png)

![image](https://user-images.githubusercontent.com/7829826/140977805-11ccba05-c240-434f-90c8-405f52ae2488.png)

In both instances, it seems there's a delay in start at the beginning and also in the middle (the row I highlighted)

So what the trigger function does, is it waits for the orchestrator for a period of time and if the orchestrator doesn't finish, it abandons the message. The difference with before is that when the messages are being abandoned and the sessionlocklostexception happens, the messages were managed to get processed by subsequent delivery before it hits the maximum delivery count (and become deadlettered). so i think that's why even though we're still getting these exceptions now, we don't see the DLQ increasing. the control queue tables are also empty so i think that's good.

**Comment by cgillum** [comment] 2021-11-09 18:51
Before writing up my response, I decided to create a README that describes the events in this table to help provide some context for what you're seeing. You can find it here: https://github.com/Azure/durabletask/tree/main/src/DurableTask.Core/History#durable-task-framework-history-events.

From what I can see in your screenshots of the history table, it looks like things are running relatively smoothly. For 6b91f4329a614ff083d3787aa628e5b3, I see there is an ~8 second delay between when the orchestration is scheduled and when it starts. It then appears to complete in a little less than a minute after starting. Similar story for 4812c04fb3f14a6fb7261c95123242c3.

There are some cases where the `_Timestamp` column may not always be in order, but this is normal. RowKey determines the actual history order. I added some notes about what these timestamps mean in the README that I linked to above. To summarize, the `_Timestamp` column for ExecutionStarted represents the time your orchestration was _scheduled_, whereas the timestamp in rowkey 0 represents the time the orchestration actually started running. The fact that they don't show up in chronological order is just how the Durable Task Framework was originally written, which unfortunately predates me.

The row you highlighted in the middle represents the point at which your orchestrator resumed after its sub-orchestration completed. Based on the timestamps, it looks like the sub-orchestration took about 52 seconds to complete. Is this expected?

Given that these orchestrations are completing in just over a minute after being scheduled, how long is your trigger function waiting before abandoning the message?

**Comment by adeliab** [comment] 2021-11-09 19:25
thanks for the readme! the timeout is set at 55 seconds because we expected the function to finish fast. there are 3 questions i have in mind now:
- what could be the reason for the 8 second delay? this function app in particular is running with 4 instances with 4 control queues (i scaled it out to see if it could help with the issue - but usually it's running with 1 instance). and we're currently receiving 1/3000 messages that we expect to see in the future so it's concerning that it's already giving 8s delay now. but maybe it's something that i need to look into in the design & configuration of the function app

- this brings me back to my question about handling session lock in azure function https://github.com/Azure/azure-sdk-for-net/issues/25130 it's still unclear for me how this works, what are the default settings and how we can configure it. if I look into the exception, it actually happens when it completes the message `Message processing error (Action=Complete`. so i don't think the timeout is the issue because even if we extend the timeout to 2 minutes and the orchestrator completes in 1.5 minute, if that past the session lock duration - we will still get the exception. so either way, any action to the message past the session lock expiration will throw this exception i think

- so it seems that changing/ having shorter task hub name fixes the original delayed issue? is there any field being serialized that contains the taskhub name?

**Comment by cgillum** [comment] 2021-11-09 19:41
> what could be the reason for the 8 second delay?

We have some documentation that describes orchestration start delays in detail, including some settings that can impact the delay. Definitely take a good look at this: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#queue-polling.

I don't know the answer to the SessionLockLostException question, unfortunately. Hopefully the Azure SDK folks will get back to you on this. In my very limited experience, some of this configuration exists in [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#hostjson-settings) and some of it exists in the Service Bus resource itself. I've also seen some cases where prefetching too many Service Bus messages can cause these kinds of mysterious issues as well. Those might be some things to look at as you continue to investigate on your side.

> so it seems that changing/ having shorter task hub name fixes the original delayed issue? is there any field being serialized that contains the taskhub name?

I'm still not sure why reducing the task hub name would make any difference, though I'm glad it seems to help in your case. This is something that still needs follow-up. I'm going to continue some small experiments to see if I can reproduce the problem you saw.

**Comment by adeliab** [comment] 2021-11-09 20:10
We've been postponing our production release because of this issue. Even with the taskhub change, I'm wondering what can be the fallback plan if the issue suddenly happens in production. what can we do to unblock the execution? you mentioned clearing the state, does that mean deleting the instances & history records? but I suppose that won't remove the stuck message in the control-queue

and I suppose to see this exception https://user-images.githubusercontent.com/2704139/140793087-56646b28-69be-4010-80ae-d17d0d0d4e64.png
, i'll need to enable the DurableTask logging?

**Comment by adeliab** [comment] 2021-11-10 17:00
@cgillum unfortunately we just discovered that our application doesn't work as expected with this change. We still need to do some investigation but we suspect it is because we have durable entities that don't exist in the new table storage. Is there a tool to migrate durable entities from one storage to another? Keep in mind that some entities have gotten too big because of the ReceivedFromInstance properties and has a reference to blob storage

**Comment by adeliab** [comment] 2021-11-11 08:35
@cgillum changing the taskhub name doesn't help. the DLQ is increasing again. The control queues table were also 'stuck' with 59 dequeue count for 1 message (there were several messages). and then 15 minutes later they're all gone. it doesn't seem stable

![image](https://user-images.githubusercontent.com/7829826/141265080-8d75f774-f9c4-4e43-9694-e93d2f94978e.png)

See this one was started the next day after it's scheduled

**Comment by davidmrdavid** [comment] 2021-11-17 00:32
Hi @adeliab,

Sorry for the delayed response, I've been working internally with your Microsoft point of contact for the ticket you raised. From our investigation, it seems to us that the reason for these errors was the serialization strategy for our "Correlation" payload for the Distributed Tracing feature.

Is Distributed Tracing enabled on your app? If so, are you able to reproduce these errors with it **disabled**? In general, Distributed Tracing is still in **preview** so these kinds of errors may occur if you're using that feature.

Please let us know! I've also asked these questions through your Microsoft support engineer. Thanks!

**Comment by adeliab** [comment] 2021-11-17 09:57
hi @davidmrdavid thanks for the update. distributed tracing is enabled in our app, i've just deployed a version with DT disabled so we can see how it goes

I didn't know that the distributed tracing is using the task sub storage, which table & field are impacted by this? where is the correlation being serialized?

also we then have to disable distributed tracing, what logging mechanism would you advise us to use to be able to have a meaningful correlation in each orchestrator invocation? it's impossible to keep track of which logs belong to which invocation otherwise - or maybe i'm missing something

**Comment by adeliab** [comment] 2021-11-17 10:02
@davidmrdavid . Also, this issue happens for a while after distributed tracing was enabled. What is the specific cause for this serialization error to happen? Is it when it's build up for a while or is there any edge case that we hit?

Another team in our company is using distributed tracing as well, so it'll be useful for us to know the cause of this

**Comment by davidmrdavid** [comment] 2021-11-17 22:21
Hi @adeliab,

The specific error I spotted was that the Function **correlation** data, which exists as a field in our History event objects, was not getting compressed prior to being saved in Azure Table Store. As a result, when trying to save your Orchestrator/Entity History to AzureStorage, we were seeing exceptions saying that a particular field ("Correlation" in this case) exceeded the size limits of Azure Storage, and so the operation would fail. 

We were able to diagnose this after reviewing the new logs we obtained after you took on the **private** AzureStorage package we sent you. To continue diagnosing this, we'll need to continue using that private package as it gives us useful extra information.

In case you haven't reproduced this with that private package, please do so so that we can get that extra telemetry. As always, we'll need the appname, a time-frame in UTC, and instanceIDs. I'll go ahead and dive into our logs now, for the appnames you have provided in the past, and see if I can spot anything.

I'll also communicate this to your support engineer, so you might be getting this message from me on both fronts. 

To answer your questions about logging with distributed tracing disabled, I'll defer to either @amdeel or @cgillum .

**Comment by cgillum** [comment] 2021-11-17 23:19
> also we then have to disable distributed tracing, what logging mechanism would you advise us to use to be able to have a meaningful correlation in each orchestrator invocation?

We've observed various teams using the orchestration instance ID as the "poor man's" implementation of trace correlation. For example, including the instance ID in every log message from an orchestration or an activity function and then writing log queries that query against a specific instance ID to get all related logs. Note that you can get the instance ID associated with an activity function execution by either adding a `string instanceId` parameter to your activity function method signature or by getting it from the `IActivityContext` trigger binding value.

> Is it when it's build up for a while or is there any edge case that we hit?

We're not sure exactly what causes this to happen yet but one hypothesis I have is that it's related to flowing correlation information through entities. I don't recall to what extend distributed correlation has been tested for entities and I wonder if we might accidentally be adding an unbounded list of correlation IDs in the entity state.

**Comment by adeliab** [comment] 2021-11-18 20:28
> We've observed various teams using the orchestration instance ID as the "poor man's" implementation of trace correlation.

I used to do this as well but it 'only works' for orchestrators & activities. When activities/ orchestrators call methods in other classes (services, etc aka. non durable function related classes), it's not clean anymore to pass around instanceId for the sole purpose of logging correlation. Any timeline on when distributed tracing is expected to be released?

**Comment by davidmrdavid** [comment] 2021-11-23 00:09
Hi @adeliab,

I cannot provide a timeline for distributed tracing, but we're aware that it's a a top-request from our users and we're actively working on unblocking that scenario.

In the meantime, we've developed another private package which should contain a patch for the Distributed Tracing error you were experiencing. Can you please take a dependency on "Microsoft.Azure.DurableTask.AzureStorage 1.9.5-private-v2" (from the same MyGet feed as before) and let us know if the issue continues after re-enabling Distributed Tracing?

If the issue no longer appears, then we'll be merging this fix in our next release. Please let us know, thank you!

cc/ @bachuv

**Comment by davidmrdavid** [comment] 2021-12-02 21:29
Just another update: the fix for this behavior has been merged and released as part of [DurableTask.AzureStorage v1.10.0](https://github.com/Azure/durabletask/releases/tag/durabletask.azurestorage-v1.10.0). A release of the Durable Functions Extension that takes on this dependency is still pending.

I'll be closing this issue as the fix has been merged. Thanks all!

**Closed by davidmrdavid** 2021-12-02 21:29 UTC
Labels: bug, dtfx

**Comment by adeliab** [comment] 2022-02-25 06:33
hi @davidmrdavid will the new v2.6.1 issue fix this issue then? since the dependency to AzureStorage is updated to the version you mentioned?
