### ISSUE TITLE
CallEntityAsync<> causes orchestration execution to 'Complete'

### ISSUE THREAD

**Issue by overunityx** [Azure/azure-functions-durable-extension#1293] opened 2020-03-26 01:09 UTC
### Description
> I have an Orchestration that stops execution when CallEntityAsync<> is awaited. With breakpoints, I can see the entity is called correctly, and the entity state is valid.
> I hope to get some understanding of why this is behaving this way.

### Expected behavior
> I expect the CallEntityAsync<> to assign a value to local variable, as follows.
> bool result = await ctx.CallEntityAsync<bool>(testID, "enabled");
>
>The 'JobManager' creates a List<EntityID>, then it starts sub-orchestrations and assigns an EntityID to each. Each worker is expected to be able to retrieve the state of their assigned EntityID.

### Actual behavior
> When the Entity reaches a return point; The Caller Orchestration immediately stops execution and moves to a 'Completed' state. All code following the CallEntityAsync<> is ignored.

### Relevant source code snippets
> Main Orchestration (run once)
```csharp
[FunctionName("JobManager")]
public static async Task RunOrchestration([OrchestrationTrigger] IDurableOrchestrationContext ctx, [DurableClient]IDurableOrchestrationClient client, ILogger log)
{
   int maxThreads = ctx.GetInput<int>();

   // add workers
   var adds = await ctx.CallActivityAsync<List<EntityId>>("Activity_Entity", ("add", thread, $"10"));

   // Start Workers
   List<Task> wkrStartTasks = new List<Task>();
   foreach(EntityId id in adds)
   {
      Task wkr = ctx.CallSubOrchestratorAsync("ExtractWorker", $"WKR-{id.EntityKey}", id);
      wkrStartTasks.Add(wkr);
   }
   await Task.WhenAll(wkrStartTasks); // Start all Sub Orchs
}
```
> Entity Class
```csharp
[JsonObject(MemberSerialization.OptIn)]
public class Entity_Tester
{
   [JsonProperty("value")]
   public bool enlu { get; set; }

   public bool enabled() => false;

   [FunctionName(nameof(Entity_Tester))]
   public static Task Run([EntityTrigger] IDurableEntityContext ctx) => ctx.DispatchAsync<Entity_Tester>();
}
```
> Worker Orchestration (many can exist)
```csharp
[FunctionName("ExtractWorker")]
public async void RunWorker([OrchestrationTrigger] IDurableOrchestrationContext ctx, [DurableClient] IDurableEntityClient client, ILogger log)
{
   EntityId entity = ctx.GetInput<EntityId>();
   //Objects.Worker wkr = await ctx.CallEntityAsync<Objects.Worker>(entity, "enabled");
   
   EntityId testID = new EntityId("Entity_Tester", "tester1000");

   //EntityStateResponse<JObject> stateResponse = await client.ReadEntityStateAsync<JObject>(testID);
   bool result = await ctx.CallEntityAsync<bool>(testID, "enabled"); // Execution never continues past this point.

   if(result)
   {
      ctx.ContinueAsNew(entity);
   }
   else
   {
      await ctx.CallEntityAsync(entity, "state", "Completed");
   }
}
```

### Known workarounds
> After 2 days on this, I have not come up with any workarounds. Aside from manually saving state to a custom Storage Table, and skipping Durable Entities.

### App Details

- **Durable Functions extension version 2.2.0**:
- **Azure Functions runtime version 2.0**:
- **Programming language used: C#**:

### Screenshots
> NA

### If deployed to Azure
> not yet. Currently testing locally with Azure Storage Emulator

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> 

[TaskHubTables.zip](https://github.com/Azure/azure-functions-durable-extension/files/4384776/TaskHubTables.zip)

**Comment by overunityx** [comment] 2020-03-26 05:42
Further testing seems to indicate issues around using Durable Entities in general. the following code also causes the orchestration to immediately halt with 'Completed'.
I've also published this to an azure tenant, and the problem persists.
I can write to an entity but cant seem to read.
What sort of things could cause this behavior?

```csharp
var lockId = new EntityId("LockEntity", $"LOCK-{entity.EntityKey}");
using(await ctx.LockAsync(lockId)) // Breakpoint shows lockId is valid, but execution ends here.
{
   // do nothing
}
```

**Comment by sebastianburckhardt** [comment] 2020-04-03 17:06
Hi @overunityx, I am trying to repro this locally. Some questions about the code you posted. Is it exactly what you were running? There seem to be some mistakes. For example,

```csharp
[FunctionName("ExtractWorker")]
public async void RunWorker([OrchestrationTrigger] IDurableOrchestrationContext ctx, [DurableClient] IDurableEntityClient client, ILogger log)
{
```
should really be

```csharp
[FunctionName("ExtractWorker")]
public static async void RunWorker([OrchestrationTrigger] IDurableOrchestrationContext ctx, [DurableClient] IDurableEntityClient client, ILogger log)
{
```

(it has to be a static function for the binding to work).

**Comment by ConnorMcMahon** [comment] 2020-04-09 23:55
It sounds like we should definitely at least add this case to our analyzer.

**Comment by cgillum** [comment] 2020-04-10 02:56
Static methods are not required for Functions generally. Instance methods were allowed starting in Functions 2.0 in order to support dependency injection. It would be good to understand why this seems to be causing problems for orchestration triggers.

**Comment by withinboredom** [comment] 2020-04-15 11:01
I vaguely remember reading somewhere in the documentation that orchestrations must be static. I can't find it now, but I'm very positive it's in there somewhere. I think it's to avoid being able to us DI which may make execution non-deterministic.

**Comment by overunityx** [comment] 2020-04-15 23:42
I ended up dropping this project.
Then upgraded from VS2017 > VS2019. Upgraded all DLLs.
Rewrote the project, & used static orchestrations... I never saw this particular 'bug' again.

Thx to efforts from everyone, keeping things moving forward =)

**Comment by ConnorMcMahon** [comment] 2020-04-15 23:50
Glad to hear you were fixed @overunityx. I'm going to leave this issue open, and hopefully we can investigate it just to make sure no one else hits this issue, but I will put it at a slightly lower prioritization since you seem to be fixed in the meantime.

**Comment by olivergrimes** [comment] 2020-10-22 21:22
I'm having a nightmare with this - It's reproductible on my machine by just adding the `Counter` example entity from docs to the default orchestration template and trying to `LockAsync` within `RunOrchestrator`.  The lock is never obtained, and nothing happens.  All `static` functions, nuget up to date, tried clearing storage many times, VS2019.

Any hints to resolve would be greatly appreciated.

**Comment by sebastianburckhardt** [comment] 2023-02-14 23:16
This issue appears to no longer show up. There have been many fixes since 2020.

**Closed by sebastianburckhardt** 2023-02-14 23:16 UTC
Labels: bug, Needs: Investigation :mag:
