### ISSUE TITLE
Exception: FunctionsDurableTaskClient does not support purging of orchestration instances.

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-functions-durable-extension#2793] opened 2024-04-15 10:51 UTC
### Description
After upgrading from in-process to isolated, the call from `PurgeInstanceHistoryAsync` changed to `PurgeAllInstancesAsync`. When running, it throws an exception. 

### Expected behavior
A way to purge the history

### Actual behavior
Exception thrown:
```csharp
[2024-04-15T10:36:06.885Z] Executed 'Functions.PurgeInstanceHistory' (Failed, Id=85dc65c0-b1a6-4ebb-be29-ace174e7f9ba, Duration=6875ms)
[2024-04-15T10:36:06.886Z] System.Private.CoreLib: Exception while executing function: Functions.PurgeInstanceHistory. System.Private.CoreLib: Result: Failure
Exception: System.NotSupportedException: Microsoft.Azure.Functions.Worker.FunctionsDurableTaskClient does not support purging of orchestration instances.
[2024-04-15T10:36:06.887Z]    at Microsoft.DurableTask.Client.DurableTaskClient.PurgeAllInstancesAsync(PurgeInstancesFilter filter, PurgeInstanceOptions options, CancellationToken cancellation)
[2024-04-15T10:36:06.888Z]    at Example.Functions.SharedFunctions.PurgeInstanceHistory(TimerInfo myTimer, DurableTaskClient client) in D:\repos\Example.Functions\Functions\SharedFunctions.cs:line 105
```

### Relevant source code snippets
```csharp
    [Function(nameof(PurgeInstanceHistory))]
    public static async Task PurgeInstanceHistory(
        [TimerTrigger("0 * * * * *")] TimerInfo time,
        [DurableClient] DurableTaskClient client
    )
    {
        var createdFrom = new DateTimeOffset(2000, 1, 1, 0, 0, 0, TimeSpan.Zero);
        var filter = new PurgeInstancesFilter(createdFrom, DateTimeOffset.UtcNow.AddDays(-7),
            new List<OrchestrationRuntimeStatus>
            {
                OrchestrationRuntimeStatus.Completed,
                OrchestrationRuntimeStatus.Failed,
                OrchestrationRuntimeStatus.Terminated
            });

        var purgeResult = await client.PurgeAllInstancesAsync(filter);
    }
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details
 c# (NET6)
Microsoft.Azure.Functions.Worker.Extensions.DurableTask v1.1.2
Microsoft.Azure.Functions.Worker 1.21.0

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by benderncb** [comment] 2024-04-18 12:07
Also affects `PurgeInstanceAsync` 

e.g. `var purgeResult = await client.PurgeInstanceAsync(entityId.ToString());`

**Comment by th3ragex** [comment] 2024-04-18 18:55
See: https://github.com/microsoft/durabletask-dotnet/issues/282
Rolling back `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` to 1.1.0 seems to work (https://github.com/microsoft/durabletask-dotnet/issues/282#issuecomment-2049016045)

**Comment by davidmrdavid** [comment] 2024-04-22 23:08
Indeed, I think this is likely a duplicate of: https://github.com/microsoft/durabletask-dotnet/issues/282.
I'll close it as such, to help centralize the discussion there ^.

**Closed by davidmrdavid** 2024-04-22 23:08 UTC
Labels: Needs: Triage :mag:
