### ISSUE TITLE
Fan Out/Fan In Scenario, stuck in running state, not completing

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#288] opened 2018-04-30 07:01 UTC
**Investigative information**
Please provide the following:

Timestamp: 2018-04-30T06:39:00.287Z
Function App version (1.0 or 2.0-beta): 1.0
Function App name: keysersoze-dev-phone-functions
Function name(s) (as appropriate): SaveCcr, SaveCcrOrchestrator, ParseCcr, SaveMsisdn, SavePhoneCall, SaveSms, SaveInvestigationObject, UpdateReportStatus
Instance ID: 5dc5c8ea9f524464816823d2e52414e7
Region: Australia South East

**Scenario**
I have a scenario where I've got a central orchestration function, that performs the following steps:

 - Receives a message from Azure Service Bus with a pointer to a blob location
 - Calls and activity to update the status of the job (written to CosmosDB)
 - Delegates to an activity to parse the data inside the blob location
 - Creates a number of tasks from the previous activity to perform effectively an Upsert to CosmosDB in various activities.
 - Calls and activity to update the status of the job (written to CosmosDB)

**Expected Behaviour**
Once all the fan out activities have completed, the orchestration should continue to the next step in logic and successfully complete

**Actual Behaviour**
From what I can tell looking at table storage logs and Application Insights, the fan out activities do successfully complete (see results in CosmosDB collections). However, it appears the orchestrator is still 'waiting' for something to occur. I'm unsure if it thinks there are still activities to be executed or the queues have got into a weird state and it not continuing, the result is that the function remains in a 'Running' state, never progressing.

![image](https://user-images.githubusercontent.com/4549796/39417335-2401b4a0-4c86-11e8-83d4-2d2cb57ff7ed.png)

![image](https://user-images.githubusercontent.com/4549796/39417353-424a6164-4c86-11e8-9202-e051615f9aa2.png)

**Related information**
Programming language used is C# (VS2017 - 15.6.7)

**Comment by ChRonX13** [comment] 2018-04-30 16:26
Yes correct... Apologies for missing that out!

**Comment by cgillum** [comment] 2018-04-30 17:10
Thanks. Unfortunately I can only see Azure Storage messaging telemetry right now, so my visibility is a bit limited. I'll do my best with what info I can get though. :)

From what I can see, it looks like the fan out is to 12K+ activity functions. Does that sound accurate? It also appears that these 12K activity functions completed, like you mentioned. 

One potentially odd thing I noticed is that although there are 12K activity function calls, it seems we've issued over 50K+ delete operations against the work-item queue. Some of those may be duplicate delete operations as the orchestrator is probably taking a long (longer than 5 minutes) to process all the responses (note this will get better when we fix [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/82)). But even then, it seems the huge batch of delete operations finished around **2018-04-30 06:48:00**.

What's even more odd is that I see more messaging operations take place about an hour later, around **2018-04-30 07:58:00**. Looking at the age of the messages in the queue, my guess is that these were from the original batch and somehow never got deleted.

Finally, all activity stops at **2018-04-30 08:16:27**. Does your orchestration still show up in the Running state or has it finally completed?

Let me know if there's any other information you can provide which can help me track this down.

**Comment by ChRonX13** [comment] 2018-05-01 00:29
12k seems about right, the following is what i expect to be called to each of the fanned out activities

269 calls to SaveMsisdn
2274 calls to SavePhoneCalls
3542 calls to SaveSms
6085 calls to SaveInvestigationObject

Total = 12170 'activity' calls

The timestamp for **2018-04-30 08:16:27** was when i shut off the function as I was leaving work for the day. I had some concerns it might be having high consumption being left to run overnight as there were still 10+ servers active when i looked at the Application Insight telemetry.

Checking this morning, it appears that the job went into a state of 'Failed' at **2018-04-30T08:14:33.245Z** with an output of **Non-Deterministic workflow detected: TaskScheduledEvent: 6895 TaskScheduled SaveInvestigationObject**. I'm unsure if that was related to the fact that I was shutting down the function instance or something else going on.

I've also noticed that it appears that the function isn't timing out correctly. I followed the same pattern as advised at [https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-error-handling#function-timeouts](url)

`
            var timeout = TimeSpan.FromHours(1);
            var deadline = context.CurrentUtcDateTime.Add(timeout);

            using (var cts = new CancellationTokenSource())
            {
                var timeoutTask = context.CreateTimer(deadline, cts.Token);
                var processTask = ProcessCcr(context, log);

                var winner = await Task.WhenAny(timeoutTask, processTask);

                if (winner == processTask)
                {
                    log.Info("Task completed...");
                    // success case
                    cts.Cancel();
                    return true;
                }

                log.Info("Timeout...");
                // timeout case
            }
`

Perhaps that timer call is related to the activity found around **2018-04-30 07:58:00**. 

Is there additional debugging that I could insert from a code perspective that might be able to assist in debugging information?

Running the scenario seems to work fine with a trivial dataset of 5 'activity' calls. I'll attempt to run a number of scenarios with a slightly smaller dataset than the above to see if it is related to specific volumes of data.

**Comment by cgillum** [comment] 2018-05-01 04:38
Thanks for the additional info. For the "stuck" case, could you try restarting your function app in the portal to see if that gets things going again? I'm wondering if something could have gone wrong with the starting/stopping sequence (I've seen similar issues in the past). Indeed, nothing appears to be running (I see the "start" message but nothing else).

BTW, regarding function timeouts, note the following from the [timer docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-timers#usage-for-timeout):

> This mechanism does not actually terminate in-progress activity function execution. Rather, it simply allows the orchestrator function to ignore the result and move on.

I'm creating a docs PR now to clarify this.

Regarding the original issue, one possible related cause could be a known performance issue: https://github.com/Azure/azure-functions-durable-extension/issues/81. If so, we have a feature/fix coming in the next release which will hopefully address this problem (and it will also fix the internal telemetry issue that's making this harder for me to investigate).

**Comment by cgillum** [comment] 2018-05-03 16:38
Thanks. Update on my side: it looks like the hour-long pause for execution from **2018-04-30 06:48:33** to **2018-04-30 07:57:15** was caused by a repeated host restart failure, which itself was caused by Azure Storage 409 conflict errors.

```
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException : The listener for function 'SaveInvestigationObject' was unable to start. ---> Microsoft.WindowsAzure.Storage.StorageException : The remote server returned an error: (409) Conflict. ---> System.Net.WebException : The remote server returned an error: (409) Conflict.
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result,TableOperation operation,HttpWebResponse resp,Exception ex) at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\Protocol\TableOperationHttpResponseParsers.cs : 61
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult) at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs : 299 
   End of inner exception
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs : 77
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult asyncResult) at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Table\CloudTable.cs : 1183
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs : 66
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.AzureStorageOrchestrationService.GetTaskHubCreatorTask()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.StartTaskHubWorkerIfNotStartedAsync()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(??) 
   End of inner exception
```
The fact that this kept happening until you shut off the function makes me think there is a logic bug in our task hub creation code that is putting things into a bad state (and fixed by restarting the function app). I'm going to follow up on this and see if I can improve the robustness of this code.

Still need to spend more time investigating your other findings.

**Comment by ChRonX13** [comment] 2018-05-04 00:10
Thanks @cgillum , do let me know if I can further assist in running other scenarios to help out! Very keen to help get this working!

**Comment by cgillum** [comment] 2018-05-04 00:32
@ChRonX13 Would you be willing to test out an updated version of the extension? If so, I can get you something that I think may help relatively soon.

**Comment by ChRonX13** [comment] 2018-05-04 00:33
@cgillum yes definately

**Comment by cgillum** [comment] 2018-05-04 05:08
I've published a new version of the extension here: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.3.4-rc. Can you try upgrading your web app with this version?

Also, you will need to update your host.json with the following configuration:

```json
{
  "durableTask": {
    "extendedSessionsEnabled": true
  }
}
```
The expected effect is that the replay behavior should basically be disabled, allowing large fan-ins to complete much faster. Give it a try and let me know how it goes - or if you run into any new issues.

**Comment by wahyuen** [comment] 2018-05-04 05:44
InstanceId: 6cf74f6520384a66a00ab158d48fa5a2
CreatedTime: 2018-05-04T05:29:10.961Z

Initial observations:
Appears that most of the activities are queued up, however, they don't seem to be executed right away. I can't see actual runs on the 'activity' functions at all. However, I can see these messages pop up on the Live Metrics Stream

![image](https://user-images.githubusercontent.com/4549796/39614241-f65dfba8-4fa0-11e8-9ba0-658793cc7188.png)

and application insights metrics query shows the following:
![image](https://user-images.githubusercontent.com/4549796/39614250-0d968c22-4fa1-11e8-9f1d-f56e8b6e17e9.png)

Will continue to let the function run to see if it eventually progress and update here...

**Comment by cgillum** [comment] 2018-05-04 06:30
OK, I looked at your execution and I'm detecting a problem with this package. Please go ahead and revert back to the previous version. I need to investigate and come back with an updated version. Really sorry about the trouble. :(

**Comment by wahyuen** [comment] 2018-05-04 06:39
not a problem at all :) happy to help out where possible! :)

**Comment by cgillum** [comment] 2018-05-04 20:48
I have a new version to try when you have a moment: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.3.5-rc. It fixes a couple different issues I discovered while analyzing your most recent run.

**Comment by wahyuen** [comment] 2018-05-05 01:40
InstanceId: **2c0edd4d311148289380db91a859c574**
CreatedTime: **2018-05-05T00:46:23.703Z**

Seems to have happily processed the activities...however, we are now back to it being stuck in a 'running' state. Been almost an hour and some 'replay' messages are still trickling through on Live Metrics Stream, however, it seems to have scaled back in to only be running 2 servers.

![image](https://user-images.githubusercontent.com/4549796/39658539-483b3740-5048-11e8-9f22-07b70d61cbb4.png)

**Comment by cgillum** [comment] 2018-05-07 00:52
So I'm not seeing anything that can clearly explain what the long delay is.  Here is a summary of what your orchestration appears to be doing:

| TIMESTAMP | TaskName | Reason | LastTime |
|-|-|-|-|
| 00:45 | FunctionScheduled | NewInstance | 00:46:25.339 |
| 00:45 | FunctionStarting |  | 00:49:14.556 |
| 00:45 | FunctionListening | CreateTimer:2018-05-05T01:49:12.879Z | 00:49:14.557 |
| 00:45 | FunctionAwaited |  | 00:59:57.350 |
| 01:00 | FunctionAwaited |  | 01:14:55.785 |
| 01:15 | FunctionAwaited |  | 01:29:44.021 |
| 01:30 | FunctionAwaited |  | 01:44:55.166 |
| 01:45 | TimerExpired | 2018-05-05T01:49:12.8794263Z | 01:56:16.402 |
| 01:45 | FunctionAwaited |  | 01:56:16.415 |
| 01:45 | FunctionCompleted |  | 01:56:44.757 |

The table shows all unique events that occurred within 15 minute windows.

BTW, I used the following "Kusto" query to get this data, and you can write a similar query in the Application Insights query language.
```
let startTime135 = datetime(2018-05-05T00:46:23.000Z);
let startTime = startTime135;
let endTime = startTime + 2h;
DurableFunctionsEvents
| where TIMESTAMP > startTime135 and TIMESTAMP <= endTime
| where InstanceId == "2c0edd4d311148289380db91a859c574"
| where ProviderName == "WebJobs-Extensions-DurableTask"
| where FunctionType == "Orchestrator" and IsReplay != 1
| project TIMESTAMP, Pid, Tid, FunctionName, TaskName, Reason, ExtensionVersion 
| summarize LastTime = max(TIMESTAMP) by TIMESTAMP = bin(TIMESTAMP, 15m), TaskName, Reason
```

The thing that's most interesting to me is that the work ultimately completed shortly after the durable timer expired. That sometimes means that the orchestrator function is simply waiting for it's timer to expire before it can be complete (a common problem when users forget to cancel timers they don't care about).

Can you share your orchestrator function code (maybe as a gist) so I can review it and see if there might be any known issues in the core logic?  I would just need to see the orchestrator function code, not any activity function code. You shared snippets previously, but it's easier for me if I can see the whole thing.

**Comment by wahyuen** [comment] 2018-05-07 01:40
@cgillum happy to email you a private gist if that works?

**Comment by cgillum** [comment] 2018-05-09 23:59
I received an internal report of a similar issue to this one. I'm starting to suspect there is actually a bug in the **DurableTask.AzureStorage** package logic which is resulting in extremely slow control-queue processing, and it may be impacting your scenario as well as others. I'm going to continue to investigate and see if I can track this down in the next few days. I'll keep you posted.

**Comment by wahyuen** [comment] 2018-05-10 04:13
I've run some more scenarios in the hope that some of this telemetry might be useful in your investigations.

I'm unsure if this is the expected throughput on a consumption plan, but I've found the actual time taken to process the individual tasks in the fan out stage to be quite high. As a test, I migrated my application to an App Service Plan to see if changing these settings affected the performance and/or the 'stuckness' of some of the jobs.

Currenct host.json settings
{
  "durableTask": {
    "extendedSessionsEnabled": true,
    "extendedSessionIdleTimeoutInSeconds": 30,
  }
}

Based on the new documentation from the GA release, I've rewired the fan out processes into sub orchestrations, and have the main orchestrator just awaiting the completion of these sub orchestrations.

When the app service plan is of sufficiency performance, it appears that the sub orchestrations are executed extremely quickly and completes. However, it appears that there is always 1 sub orchestration that takes longer than the others (not always the same one) and this sub orchestration seems to just trickle feed processing.

**Stuck**
**_B1 App Service Plan (3 instances)_**
InstanceId: 7a072e6923264748b637f9c271309d94
Created Time: 2018-05-10T01:50:06.047Z
Still stuck

**_B3 App Service Plan (3 instances)_**
InstanceId: 9ef05252fd804fa4812f57f2d20f312e
Created Time: 2018-05-10T03:25:31.478Z
Completed Time: 2018-05-10T03:29:01.488Z
**3 minutes 30s**

**_S3 App Service Plan (10 instances)_**
InstanceId: fe3bdb60da584df1a96f7dc1fd17fc04
Created Time: 2018-05-10T03:35:02.031Z
Completed Time: 2018-05-10T03:44:53.124Z
**9 minutes 51s**

InstanceId: 503946b374734d1b968f0926e62d480e
Created Time: 2018-05-10T03:44:42.265Z
Completed Time: 2018-05-10T03:50:48.803Z
**6 minutes 6s**

Below is a Gist or just the main orchestration code with some internal methods removed.

https://gist.github.com/wahyuen/ee518eac31ff5073c732cbbc087e86b5

**Comment by cgillum** [comment] 2018-08-30 05:52
Today we released the [v1.6.0 release](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.6.0) which contains a variety of reliability improvements. As part of the testing process, I created an orchestration which fans out to 100K+ activities, and verified that all of them completed successfully across multiple runs. Let me know if you run into issues like this in the future using the more recent builds.

**Closed by cgillum** 2018-08-30 05:52 UTC
Labels: needs-investigation

**Comment by VikasChitturi** [comment] 2021-03-13 09:02
> Thanks for the additional info. For the "stuck" case, could you try restarting your function app in the portal to see if that gets things going again? I'm wondering if something could have gone wrong with the starting/stopping sequence (I've seen similar issues in the past). Indeed, nothing appears to be running (I see the "start" message but nothing else).
> 
> BTW, regarding function timeouts, note the following from the [timer docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-timers#usage-for-timeout):
> 
> > This mechanism does not actually terminate in-progress activity function execution. Rather, it simply allows the orchestrator function to ignore the result and move on.
> 
> I'm creating a docs PR now to clarify this.
> 
> Regarding the original issue, one possible related cause could be a known performance issue: #81. If so, we have a feature/fix coming in the next release which will hopefully address this problem (and it will also fix the internal telemetry issue that's making this harder for me to investigate).

First Issue: 
@cgillum so why is it that the restart of the function app in the portal can get things going again, I am using azure durable functions with runtime python, and I think I am facing a similar issue, Durable function runs for some time does the ingestion from REST API and after some time when there are still some messages in the work-item queue, it stops generating relevant logs for me to monitor and just gives me random messages like this (From Live Metrics of App Insights) :+1: 

![image](https://user-images.githubusercontent.com/78720273/111025023-c7ffce00-8407-11eb-948e-425b935ad4e1.png)

when I restart the function app then the relevant logging indicating that data ingestion is happening starts appearing again then it goes on for sometime and after some time it repeats - I had to restart the function app 4-5 times to get the durable function to "Completed' stage.

Second Issue:
The durable function is "stuck" when there is only 1 message in work-item queue and only 1 activity function is loaded into worker memory in fanin-fanout scenario - It is showing these traces:

```
81d38bebff754a7f9487a270918083f7: Renewing...zenoti_get_all_sales_details_activity#2038]
81d38bebff754a7f9487a270918083f7: Renewing...ion-workitems for an additional 300 seconds
81d38bebff754a7f9487a270918083f7: Renewing...zenoti_get_all_sales_details_activity#2038]
``` 
which indicates that activity function is running but it is taking unusually large amount of time and then timing out in Azure data factory.

Please help me with above issues.thanks

**Comment by absognety** [comment] 2021-03-13 16:15
Hi @cgillum I am @VikasChitturi who put the above comment, so no confusion there. So if you see here there is only 1 message in the storage queue for the configured taskhub, 
![storage_queue](https://user-images.githubusercontent.com/25507554/111036336-bee12200-8444-11eb-8fd6-130a7f35d4bb.png)

and only one parallel activity is running I guess waiting for something, so I would like to see that particular queue message so that it can help me debug further - It is not showing up no matter how many times I refresh - How to see messages in  work-item queue
![taskactivity](https://user-images.githubusercontent.com/25507554/111036353-d15b5b80-8444-11eb-964c-e92a5452ef5a.png)
