### ISSUE TITLE
Analyzer - Cater for activity constants and/or suppress DF109 warnings

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#1287] opened 2020-03-23 01:25 UTC
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

We currently have a number of functions where we make reference to the activity name via a constant

eg.
```csharp
await context.CallActivityAsync(SendComputerVisionWorkToMonitor.EnqueuePerformComputerVisionRequestMessageActivityName,...
```

This currently raises a warning from the analyzer with 

`ProcessComputerVision.cs(49,29): warning DF0109: Activity function named 'SendComputerVisionWorkToMonitor.EnqueuePerformComputerVisionRequestMessageActivityName' does not exist. Did you mean`

### Expected behavior
> A clear and concise description of what you expected to happen.

Ability to resolve constant names when performing this check

### Actual behavior
> A clear and concise description of what actually happened.

Warning is thrown

### Relevant source code snippets
```csharp
await context.CallActivityAsync(SendComputerVisionWorkToMonitor.EnqueuePerformComputerVisionRequestMessageActivityName,

public const string EnqueuePerformComputerVisionRequestMessageActivityName = "EnqueuePerformComputerVisionRequestMessage";
```

### Known workarounds
> Provide a description of any known workarounds you used.

If we can't achieve this check with constants, would there be a way to provide a way to suppress or exclude this check on a case by case basis? (some opt out attribute?)

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3
- **Programming language used**: .Net

**Comment by amdeel** [comment] 2020-03-25 19:17
Thanks for bringing this up.

You should be able to disable this entire analyzer under dependencies -> analyzers -> Microsoft....DurableTask.Analyzers -> DF109. Right click to set custom severity to none.

Alternatively, if you want to only disable this analyzer for specific cases, you can right click on the warning in the visual studio ErrorList to suppress the warning. It will generate code for you around the flagged code.

**Comment by jublair** [comment] 2020-03-25 22:33
Same goes for other static resolvers such as `nameof(FunctionName)`. 😄

**Comment by sebader** [comment] 2020-03-27 14:29
observed the same as @jublair. I would actually not like to supress this since IMHO using `nameof()` to reference Functions is actually best practice over using constant strings.

**Comment by wahyuen** [comment] 2020-03-27 15:40
Out of interest...why the preference of `nameof` vs constant strings? Do they not both evaluate to a compile time constant anyway?

**Comment by sebader** [comment] 2020-03-27 15:42
because then you still need to make sure that the constant is always up-to-date with the name of the actual function. Using `nameof` the name of the function is the single point of truth. (happy for somebody to tell me that there is a better way)

**Comment by wahyuen** [comment] 2020-03-27 16:03
```csharp
public const string FooConstant = "Example";

[FunctionName(FooConstant)]
public async Task BlahFunction(...) {}
`

We generally have followed the above pattern, still allowing for single point of truth, but allowing us to better name our Functions for debugging in App Insights. Still interesting thought regarding `nameof()`, have never really considered using that before! :)

**Comment by cgillum** [comment] 2020-03-27 16:37
We actually did have a PR submitted that was intended to handle usage of `nameof(...)`: https://github.com/Azure/azure-functions-durable-extension/pull/1263. For the folks running into problems with `nameof`, are you using v0.2.0 of the analyzer? A code snippet of what isn't working would be helpful in case the implementation of the analyzer is working for some cases but not others.

**Comment by jublair** [comment] 2020-03-27 16:54
Ah - this seems to be tripping for `CallActivityAsync` on my end:

```
await context.CallActivityAsync(nameof(FunctionName), input);
```

We use the `nameof()` extensively in our durable functions do ensure that function renames do not break any dependent function calls.

**Comment by jublair** [comment] 2020-03-27 17:16
We also receive this warning when generating the activity name dynamically, for instance:

```
await context.CallActivityAsync(function, comb);
```

I reckon that dynamically named variables should have this warning suppressed too, since right now the warning assumes in the above example that the function name is literally "function", and the onus should be on the developer to ensure they're getting the function name right in this instance.

**Comment by sebader** [comment] 2020-03-27 19:22
@cgillum I'm using 0.2.0:

![image](https://user-images.githubusercontent.com/11445087/77792430-a677cc00-7068-11ea-8333-397dbf9af7a7.png)

**Comment by amdeel** [comment] 2020-03-27 21:22
@sebader The suggestion to suppress the warning was only to temporarily eliminate the warnings if desired. This will be fixed in our next release of the analyzer. 0.2.0 does not have the PR mentioned above.

**Comment by marcduiker** [comment] 2020-03-27 22:14
I'm afraid the `nameof()` usage still triggers the `DF109` warning in v2.2.0. So something in my PR was probably not correct 😢. I'll try to reproduce this in unit tests.

**Comment by marcduiker** [comment] 2020-03-27 22:33
Yes, `nameof(...)` should be detected properly in the next release of the Analyzer :). 

I think the check of using constants will be a nice one for me to pick up if you are ok with that @amdeel.

**Comment by amdeel** [comment] 2020-03-28 00:15
@marcduiker Sure, feel free to work on this! Thank you! :)

**Comment by DenisBalan** [comment] 2020-04-05 10:04
Same issue, with nameof, as we treat warning as errors, this causes ci build failing fixed via additional steps to disable analyzer.

**Closed** 2020-04-09 02:23 UTC
Labels: analyzer
