### ISSUE TITLE
Functions always fails with InvalidCastException when distributed tracing is enabled

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#1611] opened 2020-12-12 10:57 UTC
### Description

Adding `distributedTracingEnabled = true` to enable distributed tracing in existing Durable Functions-based applications will now fail with a runtime exception.

This seems to occur when newly enabling distributed tracing. Once the distributed tracing worked correctly, it did not occur thereafter.

### Expected behavior

Execution completed without exceptions.

### Actual behavior

**Exception message**

```
Exception while executing function: RenewCertificates_Timer Unable to cast object of type 'DurableTask.Core.HttpCorrelationProtocolTraceContext' to type 'DurableTask.Core.TraceContextBase'.
```

**Stack trace**

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__20.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 330)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__15.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 94)
Inner exception System.InvalidCastException handled at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw:
   at DurableTask.Core.CorrelationTraceClient+<>c__DisplayClass7_0.<SetUp>b__1 (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\CorrelationTraceClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 60)
   at System.Reactive.AnonymousObserver`1.OnNextCore (System.Reactive.Core, Version=3.0.6000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263)
   at System.Reactive.ObserverBase`1.OnNext (System.Reactive.Core, Version=3.0.6000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263)
   at System.Diagnostics.DiagnosticListener.Write (System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at DurableTask.Core.CorrelationTraceClient+<>c__DisplayClass9_0.<TrackDepencencyTelemetry>b__0 (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\CorrelationTraceClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 95)
   at DurableTask.Core.CorrelationTraceClient.Execute (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\CorrelationTraceClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 144)
   at DurableTask.Core.CorrelationTraceClient.TrackDepencencyTelemetry (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\CorrelationTraceClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 95)
   at DurableTask.Core.TaskHubClient.CreateAndTrackDependencyTelemetry (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\TaskHubClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 669)
   at DurableTask.Core.TaskHubClient+<>c__DisplayClass27_0.<InternalCreateOrchestrationInstanceWithRaisedEventAsync>b__1 (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\TaskHubClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 611)
   at DurableTask.Core.CorrelationTraceClient.Execute (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\CorrelationTraceClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 144)
   at DurableTask.Core.TaskHubClient+<InternalCreateOrchestrationInstanceWithRaisedEventAsync>d__27.MoveNext (DurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89ddDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: C:\source\durabletask\src\DurableTask.Core\TaskHubClient.csDurableTask.Core, Version=2.5.0.0, Culture=neutral, PublicKeyToken=d53979610a6e89dd: 611)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient+<Microsoft-Azure-WebJobs-Extensions-DurableTask-IDurableOrchestrationClient-StartNewAsync>d__31`1.MoveNext (Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289: D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.csMicrosoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289: 170)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at AppService.Acmebot.Functions.RenewCertificates+<Timer>d__2.MoveNext (AppService.Acmebot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=nullAppService.Acmebot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\Users\shibayan\Documents\GitHub\appservice-acmebot\AppService.Acmebot\Functions\RenewCertificates.csAppService.Acmebot, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: 123)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2+<InvokeAsync>d__2.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 20)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__10.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 52)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeWithTimeoutAsync>d__27.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 559)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__26.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 505)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__20.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.25.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 283)
```

### Relevant source code snippets

**host.json**

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request;Exception"
      }
    },
    "logLevel": {
      "KeyVault.Acmebot": "Warning"
    }
  },
  "extensions": {
    "durableTask": {
      "hubName": "DurableFunctionsHub",
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 120,
      "tracing": {
        "distributedTracingEnabled": true
      }
    },
    "http": {
      "customHeaders": {
        "Cache-Control": "no-store"
      }
    }
  }
}
```

### Known workarounds

Disable distributed tracing.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: .NET Core / C#

**Comment by ConnorMcMahon** [comment] 2020-12-14 17:51
To clarify @shibayan, it sounds like your in-flight orchestrations are failing with this casting exception, but all new orchestrations started after enabling distributed tracing do not encounter this issue. Is that correct?

**Comment by shibayan** [comment] 2020-12-14 18:07
Occurred in an orchestration performed after enabling distributed tracing rather than in a running orchestration.

I share because there was a way to reproduce it in simple steps.

### Repro steps

1. Create new Durable Function project and update to v2.4.0
2. Enable distributed tracing (adding `"distributedTracingEnabled": true` to host.json)
3. Create new Azure Functions (use portal)
4. Deploy function app
5. Trigger `HttpStart` function

### Error log

```
2020-12-14T18:03:25  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2020-12-14T18:03:32.244 [Information] Executing 'Function1_HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=be7ae71b-5ce0-454f-98b9-9fe185c1a166)
2020-12-14T18:03:32.283 [Error] Executed 'Function1_HttpStart' (Failed, Id=be7ae71b-5ce0-454f-98b9-9fe185c1a166, Duration=3ms)Unable to cast object of type 'DurableTask.Core.HttpCorrelationProtocolTraceContext' to type 'DurableTask.Core.TraceContextBase'.
2020-12-14T18:03:51.569 [Information] Executing 'Function1_HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=3739dc21-6a10-4319-b744-3a7517c7e970)
2020-12-14T18:03:51.637 [Error] Executed 'Function1_HttpStart' (Failed, Id=3739dc21-6a10-4319-b744-3a7517c7e970, Duration=51ms)Unable to cast object of type 'DurableTask.Core.HttpCorrelationProtocolTraceContext' to type 'DurableTask.Core.TraceContextBase'.
2020-12-14T18:03:58.158 [Information] Executing 'Function1_HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=81a83c2c-8632-4efe-8223-70996cd3c528)
2020-12-14T18:03:58.260 [Error] Executed 'Function1_HttpStart' (Failed, Id=81a83c2c-8632-4efe-8223-70996cd3c528, Duration=38ms)Unable to cast object of type 'DurableTask.Core.HttpCorrelationProtocolTraceContext' to type 'DurableTask.Core.TraceContextBase'.
```

### Deployment info

- **Timeframe issue observed**: 2020-12-14T18:03:32.244
- **Function App name**: distributed-tracing-test
- **Function name(s)**: Function1_HttpStart
- **Azure region**: Central US
- **Orchestration instance ID(s)**: Can't start
- **Azure storage account name**: storageaccountdistra792

**Comment by ConnorMcMahon** [comment] 2020-12-14 18:14
Hmm, that is rather confusing, because looking [at the code](https://github.com/Azure/durabletask/blob/e1d9ecf497c0d4c2af1be6096cd1563123f86bbe/src/DurableTask.Core/HttpCorrelationProtocolTraceContext.cs#L25),  `DurableTask.Core.HttpCorrelationProtocolTraceContext` extends `DurableTask.Core.TraceContextBase`, so there should be no casting exception here. This will definitely require an investigation.

In your initial post, you mentioned 

> This seems to occur when newly enabling distributed tracing. Once the distributed tracing worked correctly, it did not occur thereafter.

Roughly how long did it take for your application to start working correctly with distributed tracing?

**Comment by shibayan** [comment] 2020-12-14 18:47
I don't know exactly how long it took me to deploy and change the configuration repeatedly, but I think it took about 30 minutes.

I was curious about the version of Function Runtime, so I changed the setting to use an older version, and it worked correctly. The following is a summary of the results.

⭕ `FUNCTIONS_EXTENSION_VERSION = 3.0.14916`
❌ `FUNCTIONS_EXTENSION_VERSION = 3.0.15185`

Since I was using Consumption Plan, it may have just worked because the runtime version happened to change after cold start.

**Comment by davidmrdavid** [comment] 2021-01-13 20:38
Just confirming that I'm able to reproduce this error. This is what I see:

```
2021-01-13T20:38:09  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2021-01-13T20:38:10.167 [Information] Executing 'DurableFunctionsOrchestrationCSharp1_HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=85533be3-0566-4fa3-99df-cceecf112fa2)
2021-01-13T20:38:10.283 [Error] Executed 'DurableFunctionsOrchestrationCSharp1_HttpStart' (Failed, Id=85533be3-0566-4fa3-99df-cceecf112fa2, Duration=122ms)Unable to cast object of type 'DurableTask.Core.W3CTraceContext' to type 'DurableTask.Core.TraceContextBase'.
```

**Comment by davidmrdavid** [comment] 2021-01-13 21:23
And I believe the exception is taking place [here](https://github.com/Azure/durabletask/blob/e1d9ecf497c0d4c2af1be6096cd1563123f86bbe/src/DurableTask.Core/CorrelationTraceClient.cs#L36-L62)

**Comment by davidmrdavid** [comment] 2021-01-13 21:29
@shibayan , can you clarify what you meant by this?

⭕ FUNCTIONS_EXTENSION_VERSION = 3.0.14916
❌ FUNCTIONS_EXTENSION_VERSION = 3.0.15185

Does this mean that it worked for you with `3.0.15185` but not for `3.0.14916` or vice-versa?

**Comment by shibayan** [comment] 2021-01-14 08:37
@davidmrdavid 

>Does this mean that it worked for you with 3.0.15185 but not for 3.0.14916 or vice-versa?

It did not work with the version `3.0.15185`, but it worked when I lowered the version to `3.0.14916`. I'm sorry it's not clear.

**Comment by davidmrdavid** [comment] 2021-01-19 22:50
I'll be transferring this ticket to continue investigating during our upcoming release sprint

**Comment by ichesa** [comment] 2021-02-01 09:38
Hi all,

I think I'm having a similar issue, so I would like to share some details with you in case it is of any help.

I'm using a Timer Trigger function as the DurableClient (and for the ochestrator some activities, sub orchestrators, and the fan in/out pattern) and everything runs well when the function is auto triggered. However, when I run the function through the Azure Portal I get this error: **_Exception while executing function: FireGroupsSynchronisation Unable to cast object of type 'DurableTask.Core.W3CTraceContext' to type 'DurableTask.Core.TraceContextBase'._**

The real problem with this is that, once this error appears, all subsequent auto executions fail the same way and I'm forced to redeploy in order to have the functions working again.

As you may already notice, I'm using W3CTraceContext instead, like in your sample project. This is my config applied:
host.json
```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "CorrelationTesting",
      "tracing": {
        "distributedTracingEnabled": true,
        "distributedTracingProtocol": "W3CTraceContext"
      }
    }
  },
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      },
      "httpAutoCollectionOptions": {
        "enableW3CDistributedTracing": true
      }
    }
  }
}
```
I hope this is of any help and we can get this solved.

Regards.

**Comment by davidmrdavid** [comment] 2021-02-01 18:40
Thank you for the additional context @ichesa, every little bit of it helps :-) !

Just to confirm, @ichesa, this issue occurs for you **only when the orchestrator is started via the Portal, correct?** So it doesn't occur when automatically triggered by some other means, such as an HTTP request to the site's actual endpoint?

The tricky thing about debugging this issue is that it doesn't occur when debugging locally, so I suspect the azure portal is loading some different assembly or something like that.

**Comment by ichesa** [comment] 2021-02-04 13:59
Hi @davidmrdavid ,

My apologies for the late response.

Yes, you're right. In my case I'm using a "TimerTrigger" function as the "DurableClient" and the executions run without any issues each time the function is auto-triggered at its schedule (each 20 mins in my case). The problem comes when I run the function manually through the Azure Portal (because I need to start the process earlier for example). In that case, the error is the one I pasted in my previous message.

Because you mentioned also other approaches like the HTTP, I have done another test by triggering the timer function with Postman through a POST call using the master key.  This test works without any issue, like when it is autotriggered.

So, at the moment, I've only been able to reproduce this problem when triggering the function manually from the Azure Portal.

**Comment by davidmrdavid** [comment] 2021-03-11 20:51
Thanks everyone. I just tried reproducing this error again and was unable to do so. Is this still ongoing for y'all: @ichesa, @shibayan? Try re-deploying, I think it's working out of the box now. Please let me know if not.

**Comment by shibayan** [comment] 2021-03-12 13:20
I tried again, and it appears to have worked correctly with the current latest Function Runtime Host (`3.0.15406`).

Error : `3.0.15193`
Worked : `3.0.15406`

I don't keep track of what updates have been made during this version, but as long as no regressions occur, I don't think it will be a problem. Thanks!

**Closed** 2021-03-12 18:16 UTC
Labels: Needs: Investigation :mag:, bug

**Comment by helsaawy** [comment] 2021-06-03 21:34
Hello,

I am on a newer version of the runtime host and am having this error:
```
Python version 3.7.10 (python3).
Core Tools Version:       3.0.3477 Commit hash: 5fbb9a76fc00e4168f2cc90d6ff0afe5373afc6d  (64-bit)
Function Runtime Version: 3.0.15584.0
```

```
Executed "Functions.DurableFunctionsHttpStart" (Failed, Id=e0967397-2aea-4e97-bcb1-47755fa630df, Duration=892ms)
System.Private.CoreLib: Exception while executing function: Functions.DurableFunctionsHttpStart. System.Private.CoreLib: Result: Failure
Exception: Exception: {
  "Message": "Something went wrong while processing your request",
  "ExceptionMessage": "Unable to cast object of type "DurableTask.Core.W3CTraceContext" to type "DurableTask.Core.TraceContextBase".",
  "ExceptionType": "System.InvalidCastException",
  "StackTrace": "
   at DurableTask.Core.CorrelationTraceClient.<>c__DisplayClass7_0.<SetUp>b__1(KeyValuePair`2 evt) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 66
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at DurableTask.Core.CorrelationTraceClient.<>c__DisplayClass9_0.<TrackDepencencyTelemetry>b__0() in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 95
   at DurableTask.Core.CorrelationTraceClient.Execute(Action action) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 146
   at DurableTask.Core.CorrelationTraceClient.Tracking(Action tracking) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 138
   at DurableTask.Core.CorrelationTraceClient.TrackDepencencyTelemetry(TraceContextBase context) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 96
   at DurableTask.Core.TaskHubClient.CreateAndTrackDependencyTelemetry(TraceContextBase requestTraceContext) in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskHubClient.cs:line 670
   at DurableTask.Core.TaskHubClient.<>c__DisplayClass27_0.<InternalCreateOrchestrationInstanceWithRaisedEventAsync>b__1() in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskHubClient.cs:line 611
   at DurableTask.Core.CorrelationTraceClient.Execute(Action action) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 146
   at DurableTask.Core.CorrelationTraceClient.Propagate(Action action) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 115
   at DurableTask.Core.TaskHubClient.InternalCreateOrchestrationInstanceWithRaisedEventAsync(String orchestrationName, String orchestrationVersion, String orchestrationInstanceId, Object orchestrationInput, IDictionary`2 orchestrationTags, OrchestrationStatus[] dedupeStatuses, String eventName, Object eventData, Nullable`1 startAt) in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskHubClient.cs:line 614
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 170
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 766
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 284"
}
```

It usually happens after one or two function executions, and causes all subsequent tries to fail

**Comment by davidmrdavid** [comment] 2021-06-03 22:04
Hi @helsaawy,

Thanks for reaching out. Could you please open a new issue containing your durable-extension version as well as the functions host version you're running on? That will help us kickstart an investigation :)

cc/ @bachuv
