### ISSUE TITLE
Some activity functions are getting completed and some throwing error "Activity function 'Func1' failed: Value cannot be null. Parameter name: logger"

### ISSUE THREAD

**Issue by iamsuresha** [Azure/azure-functions-durable-extension#783] opened 2019-05-29 11:40 UTC
Its working fine in local but i when i deploy to azure portal its throwing the above said error. @cgillum Kindly advise on this. Please let me know if you need any details.

**Comment by iamsuresha** [comment] 2019-05-31 12:55
@cgillum I have around 22k activities scheduled. When the activity started it starts playing more than once. 

After around 8k records processed the function becomes non deterministic. Please help me to resolve the issue.

My Orchestration function:

 public static async Task<bool> TransformOrchestration([OrchestrationTrigger] DurableOrchestrationContext context)
        {
            _logger.LogTrace($"{nameof(SlyceDurableFeed.TransformOrchestration)} : OrchestrationTrigger strated");
            var processStartTime = context.GetInput<DateTime>();
            List<ISlyceProductDetail> productDetails = new List<ISlyceProductDetail>();
            List<Task<SlyceProductDetail>> catTasks = new List<Task<SlyceProductDetail>>();

            string accountNumberShipTo = _appSettings.AccountNumberShipTo;

            string[] allAccountsToSend = accountNumberShipTo.Split(new string[] { "," }, StringSplitOptions.None);

            if (allAccountsToSend.Length > 0)
            {
                foreach (string account in allAccountsToSend)
                {
                    accNumShipTo = account.Split(new string[] { "-" }, StringSplitOptions.None);

                    Dictionary<string, string[]> ProductSkusByAccountNumberShipto = new Dictionary<string, string[]>();

                    List<ISlyceProductDetail> allProducts = new List<ISlyceProductDetail>();
                    List<string> warehouseIds = new List<string>();
                    warehouseIds = _appSettings.WholesaleWarehouse.Split(',').ToList();
                    if (warehouseIds.Count == 0)
                        warehouseIds.Add("");
                    foreach (string warehouseId in warehouseIds)
                    {
                        IEnumerable<ISlyceProductDetail> products = _productService.GetProductAsync(accNumShipTo[0], accNumShipTo[1], warehouseId);
                        List<ISlyceProductDetail> productsList = AutoMapper.Mapper.Map<IEnumerable<ISlyceProductDetail>>(products).ToList();
                        productDetails.AddRange(productsList);
                    }
                }
            }


            for (int i = 0; i < productDetails.Count; i++)  //loop through all the products and spin off a task for each one to get it's categories
            {
                Task<SlyceProductDetail> task = context.CallActivityAsync<SlyceProductDetail>("FetchCategoriesBySku", productDetails[i]);
                catTasks.Add(task);
            }

            //Waiting for all of the tasks for getting categories to be done
            await Task.WhenAll(catTasks);

  //Assigning category ID and Product Categories
            productDetails.ForEach(cat => cat.CategoryId = catTasks.Find(x => x.Result.RetailSkuId == cat.RetailSkuId)?.Result.CategoryId);
            productDetails.ForEach(cat => cat.ProductCategory = catTasks.Find(x => x.Result.RetailSkuId == cat.RetailSkuId)?.Result.ProductCategory);
}

My Activity function:
       [FunctionName("FetchCategoriesBySku")]
        public static SlyceProductDetail FetchCategoriesBySku([ActivityTrigger] DurableActivityContext context, ILogger logger)
        {
            var prod = new SlyceProductDetail();
            try
            {
                logger.LogTrace($"{nameof(SlyceDurableFeed.FetchCategoriesBySku)} Started FetchCategoriesBySku function");
                if (context != null)
                {
                    prod = context.GetInput<SlyceProductDetail>();
                    List<string> categoriesDelimitedByCommas = _categoriesService.GetCategoriesBySku(prod.RetailSkuId);
                    if (categoriesDelimitedByCommas.Any())
                    {
                        prod.CategoryId = categoriesDelimitedByCommas[0];
                        prod.ProductCategory = string.Join(",", categoriesDelimitedByCommas);
                    }
                }
                else
                {
                    logger.LogTrace($"{nameof(SlyceDurableFeed.FetchCategoriesBySku)} Context value passed as Null");
                }
                logger.LogTrace($"{nameof(SlyceDurableFeed.FetchCategoriesBySku)} Completed FetchCategoriesBySku function");
            }
            catch (Exception ex)
            {
                _logger.LogError($"{nameof(SlyceDurableFeed.FetchCategoriesBySku)} activity function failed . Error Message: {ex.Message}, {ex}");
            }
            return prod;
        }



My Hub history:

![image](https://user-images.githubusercontent.com/50022627/58707057-6f497780-83d1-11e9-822c-22641598d007.png)

![image](https://user-images.githubusercontent.com/50022627/58707092-85573800-83d1-11e9-8b34-dc1442f0a2bf.png)

**Comment by cgillum** [comment] 2019-05-31 16:37
Are you familiar with the replay behavior of orchestrator functions? Also, are you familiar with the coding constraints for orchestrator functions? Both are described here:
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#the-technology

I noticed the following line in your code which seemed suspicious:
```csharp
IEnumerable<ISlyceProductDetail> products = _productService.GetProductAsync(accNumShipTo[0], accNumShipTo[1], warehouseId);
```

What does `_productService.GetProductAsync` do? If it's making any async calls like the method name implies, or if it's doing any I/O, then that's likely the cause of the non-determinism.

**Comment by iamsuresha** [comment] 2019-06-07 14:37
@cgillum 
Sorry i was out of station. The call(_productService.GetProductAsync) is  sync only its just naming issue. One thing i have noticed that its running in local for more than 20k activities also but in portal only it failed.

**Comment by cgillum** [comment] 2019-06-07 17:07
I still worry about `_productService.GetProductAsync(...)`. For example, does it do any I/O? Even if it is synchronous I/O, it's extremely dangerous because doing any I/O is naturally non-deterministic. Problems can occur, for example, if during some replay a different set of products are returned.  If any I/O is involved, you _must_ refactor your code so that `_productService.GetProductsAsync(...)` runs inside an activity function.

**Comment by iamsuresha** [comment] 2019-06-11 07:51
@cgillum  I split the code and made that as a activity function and now its working fine in local. But in still in portal it throws as below ...
Activity function 'FetchPSAPIProdcuts' failed: Value cannot be null.
Parameter name: logger

**Comment by cgillum** [comment] 2019-06-12 00:16
Durable Functions triggers don't work particularly well in the Azure Portal. But I suppose there's no real reason why an activity function shouldn't work. If you change your trigger to be a queue trigger, does the same function code work correctly in the portal?

**Comment by iamsuresha** [comment] 2019-06-14 10:39
@cgillum thanks for the suggestion. Currently we have planned to put all the lists into queue in the first azure function(Timer trigger) and update the queue using the 2nd function(queue trigger). Then another trigger to serve our need i.e, generating the content.

**Comment by cgillum** [comment] 2019-07-12 20:41
@iamsuresha just to be clear, you have moved on from using Durable Functions for this particular scenario? If so, are we good to close this issue?

**Closed** 2019-12-14 00:00 UTC
Labels: Needs: Author Feedback, no-recent-activity
