### ISSUE TITLE
Durable Functions using TimeTrigger won't follow singleton behavior

### ISSUE THREAD

**Issue by elksson** [Azure/azure-functions-durable-extension#542] opened 2018-12-10 20:51 UTC
I am having issues with durable functions running more than 1 at a time. I would like this durable function to run once every 15 seconds but the function can take between 5 seconds and 10 minutes to complete. I need to ensure that the function does not run more than 1 instance at a time even if the functions are scaled to more than 1 host. My expectation was that this behavior should already be taken care of by the TimeTrigger however it does not appear that that is respected. 

I would appreciate some help how I can troubleshoot this issue further as I am totally stumped how to proceed with debugging:

Here is a definition of my durable function. 

Thanks

```csharp
[FunctionName("Sync")]
        public static async Task Sync([OrchestrationTrigger] DurableOrchestrationContextBase context, ILogger log)
        {
            double maxSync;
            double.TryParse(Environment.GetEnvironmentVariable("MaxSync"), out maxSync);
            maxSync = maxSync == 0 ? 30 : maxSync;
            await context.CallActivityAsync("ServiceTypeSync", maxSync);
            await context.CallActivityAsync("EmployeeSync", maxSync);
            await context.CallActivityAsync("CustomerSync", maxSync);
            await context.CallActivityAsync("SubscriptionSync", maxSync);
            await context.CallActivityAsync("AppointmentSync", maxSync);
            await context.CallActivityAsync("TicketSync", maxSync);
            await context.CallActivityAsync("PaymentSync", maxSync);
        }
```
```csharp
[FunctionName("StartSync")]
        public static async Task StartSync([TimerTrigger("%TimerInterval%")] TimerInfo myTimer, [OrchestrationClient]DurableOrchestrationClient starter, ILogger log)
        {
            string instanceId = await starter.StartNewAsync("PestRoutesSync", null);

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");
        }
```

**Comment by cgillum** [comment] 2018-12-13 05:54
Hi @elksson. Since the behavior you're seeing appears to be by design, I'm going to go ahead and close this issue. Please let us know if you have any additional questions or concerns.

**Closed by cgillum** 2018-12-13 05:54 UTC
