### ISSUE TITLE
Some durable tasks seems still running after orchestrator is completed

### ISSUE THREAD

**Issue by kaluznyt** [Azure/azure-functions-durable-extension#891] opened 2019-08-08 09:09 UTC
### Description
We have a quite complex infrastructure which in part is based on durable function. 

It basically decrypts a lot of blobs and save these as decrypted on blob storage. 

Then it reads these blobs and deserialize these into c# pocos (table entities) and inserts into azure storage table.

Everything works ok, besides 1 thing, after the durable function is completed which means
"runtimeStatus" : "Completed" and output having value returned from function, some rows are added to the storage table (these rows are basically duplicates of some (very small subset) rows previously added). 

So in short, after function with all it's sub-activities finish, we can see a correct state in azure storage table, but then (always almost exactly after 5 minutes) some more rows (duplicates of some earlier batch) are added. Initially we thought that we cannot remove the storage table, but then the analysis shown that the table was recreated due to these rows being added. Not all rows are added thought. It's like for a table with 400000 rows we could see for example 1500 rows added after 5 minutes when function was completed so it's like just some orphaned batch (or replay or anything, I don't quite understand at this point where these rows are coming from).

### Expected behavior
No duplicated rows added to the storage table after the durable function is completed.

### Actual behavior
It's described above.

### Relevant source code snippets
Orchestrator code:
```csharp
[FunctionName(nameof(TransferData))]
    public static async Task<string> TransferData(
      [OrchestrationTrigger] DurableOrchestrationContext context,
      TraceWriter log)
    {
      var (someId1, someKey1, someId2) = context.GetInput<(string, Guid, Guid)>();

      var containerPath = $"container-{someId1}";

      var batches = await context.CallActivityAsync<List<List<string>>>(
                          nameof(GetBlobListFromContainer),
                          containerPath);

      var guid = context.NewGuid();
      var temporaryTableName = $"Data{guid:N}";
      var temporaryDecryptedBlobContainer = $"temp-{guid:N}";

      var decryptionTasks = new List<Task>();

      foreach (var blobs in batches)
      {
        decryptionTasks.Add(
          context.CallActivityAsync(
            nameof(DecryptBlob),
            (blobs, someId1, temporaryDecryptedBlobContainer)));
      }

      await Task.WhenAll(decryptionTasks);

      var insertionTasks = new List<Task>();

      foreach (var blobs in batches)
      {
        insertionTasks.Add(
          context.CallActivityAsync(
            nameof(InsertBlobToTable),
            (blobs, someId1, someKey1, someId2, temporaryTableName, temporaryDecryptedBlobContainer)));
      }

      await Task.WhenAll(insertionTasks);

      return temporaryTableName;
    }
```

### Known workarounds
No workaround found yet.

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**:
Microsoft.Azure.WebJobs.ExtensionsDurableTask v1.8.3
- **Azure Functions runtime version (1.0 or 2.0)**:
Azure Functions runtime v1
- **Programming language used**:
C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
2019-08-08 00:40 - 00:50 UTC

- **Orchestration instance ID(s)**:
19db2f3356884330a3b0cbe81e493694

InvocationID for these invalid rows:
5d518610-c9c8-4f89-802b-1cd0f982aec9

Timestamp on this rows is around:
2019-08-08T00:47:23.042Z (this is took from one of these but all are around this time - same minute)

{
"name": "XXXXXXX",
"instanceId": "60da848666f84dd78e1410fa80fe898b",
"runtimeStatus": "Completed",
"input": {
"$type": "System.ValueTuple`3[[System.String, mscorlib],[System.String, mscorlib],[System.String, mscorlib]], mscorlib",
"Item1": "ec5f5113-5ac7-4022-9493-ef1338ebd92f",
"Item2": "085f8f41-04f1-4a7d-aaf5-0b66062da9d3",
"Item3": "5caf774e-b2fe-4fd9-a6ac-4fb1219aff29"
},
"customStatus": null,
"output": "XXXXXXXXXXX",
"createdTime": "2019-08-08T00:44:58Z",
"lastUpdatedTime": "2019-08-08T00:45:09Z"
}

**Comment by kaluznyt** [comment] 2019-08-12 14:01
This is actually same issue as #839

**Comment by ConnorMcMahon** [comment] 2019-08-22 22:32
@kaluznyt I am going to close this as a duplicate of that issue. I will keep track of your case as well when investigating that issue.

**Closed by ConnorMcMahon** 2019-08-22 22:32 UTC
Labels: Needs: Triage :mag:
