### ISSUE TITLE
Analyzer - Does not pick up when function name is in variable

### ISSUE THREAD

**Issue by Fabian-Schmidt** [Azure/azure-functions-durable-extension#1299] opened 2020-04-01 05:23 UTC
### Description
When Function name is defined as external as `const string` the analyzer will ignore this method. It will not highlight any issues.

I use const string to reference Function names. This has the benefit of minimizing name issues and allows me to use `Find All References`.

### Expected behavior
Analyzer works with Functions where name is in const string.

### Actual behavior
Analyzer ignores methods with Function name stored in variable.

### Relevant source code snippets
```csharp
public const string OrchestratorName = "Orchestrator";
[FunctionName(OrchestratorName)]
public static async Task<OrchestratorEndMessage> RunOrchestrator(
  [OrchestrationTrigger] IDurableOrchestrationContext context)
{
  var d = DateTime.UtcNow;
...
```

### Known workarounds
Use static Function name and repeat yourself.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.1
- **Programming language used**: C#
- **Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers**: 0.2.0

**Comment by amdeel** [comment] 2020-04-06 16:15
Hey, @Fabian-Schmidt, this is an issue that is going to be fixed with the next release of the analyzer, I expect an analyzer release by the end of the week.

This is a duplicate of #1287, I'm going to close this.

**Closed by amdeel** 2020-04-06 16:15 UTC
Labels: analyzer
