### ISSUE TITLE
Durable Functions 1.8 fails with Method not found. 

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#667] opened 2019-03-22 20:29 UTC
I encounter the issue when I start Durable Functions 1.8. 

```
Microsoft.Azure.WebJobs.Extensions.DurableTask: Method not found: 'Void DurableTask.AzureStorage.StorageAccountDetails.set_ConnectionString(System.String)'.
```

It seems the DurableTask.Storage 1.5.0 seems old. 

When I fetch the source of the StorageAccountDetails from the Durable Functions 1.8, 
I can see this source. This is the old one. 

```csharp
    /// <summary>
    /// Connection details of the Azure Storage account
    /// </summary>
    public sealed class StorageAccountDetails
    {
        /// <summary>
        /// The storage account credentials
        /// </summary>
        public StorageCredentials StorageCredentials { get; set; }

        /// <summary>
        /// The storage account name
        /// </summary>
        public string AccountName { get; set; }

        /// <summary>
        /// The storage account endpoint suffix
        /// </summary>
        public string EndpointSuffix { get; set; }

        /// <summary>
        ///  Convert this to its equivalent CloudStorageAccount.
        /// </summary>
        public CloudStorageAccount ToCloudStorageAccount()
        {
            return new CloudStorageAccount(this.StorageCredentials, this.AccountName, this.EndpointSuffix, true);
        }
    }
}
```

**Comment by cgillum** [comment] 2019-03-22 20:36
Most likely the problem is because you have a prerelease version of **DurableTask.AzureStorage** in your nuget cache. We previously had this package on _myget.org_ and it did not contain the final bits that were pushed to _nuget.org_.

I've deleted this package from _myget.org_ to remove any possibility of people accidentally pulling it in when resolving nuget dependencies. Please clear your nuget cache and rebuild your code to see if that resolves the issue.

**Comment by TsuyoshiUshio** [comment] 2019-03-22 20:51
Hi @cgillum , Thanks. Clear cache works.

**Closed** 2019-03-22 20:57 UTC
