### ISSUE TITLE
Intermittent `RunAsync does not handle the function execution status FunctionsHostStoppingError` causing Orchestrations to fail

### ISSUE THREAD

**Issue by dylanhouston7** [Azure/azure-functions-durable-extension#2162] opened 2022-05-05 11:42 UTC
### Description
> When I run orchestrations, some of them intermittently fail with an exception:

```
Orchestrator function 'x' failed: The activity function 'x' failed: "Failed to deserialize exception from TaskActivity: Unhandled exception while executing task: System.InvalidOperationException: RunAsync does not handle the function execution status FunctionsHostStoppingError.
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 124
   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass14_1.<<OnProcessWorkItemAsync>b__2>d.MoveNext() in /_/src/DurableTask.Core/TaskActivityDispatcher.cs:line 183". See the function execution logs for additional details.
```

I've checked my app insights logs and I do not see any other underlying exceptions. 

### Expected behavior
I am running this in a deployed Azure environment and have ensured that slot functions are disabled. Most of the orchestrations succeed. I would expect orchestrations to not intermittently fail and to be reliable. 

### Actual behavior
> Orchestrations run, some succeed, and others fail for the reason described above.

### Relevant source code snippets

host.json file

`{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "%TaskHub%",
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 300,
      "useGracefulShutdown": true
    }
  },
  "functionTimeout": "00:00:30",
  "retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 3,
    "delayInterval": "00:00:30"
  },
  "logging": {
    "logLevel": {
      "default": "Information",
      "Microsoft": "Warning",
      "Azure.Messaging.ServiceBus": "Information",
      "Microsoft.Azure.WebJobs.Extensions.DurableTask": "Warning",
      "DurableTask.AzureStorage": "Warning"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}`

### Known workarounds
> No known workarounds. I've tried tweaking my `host.json` to no avail (see pasted text above).

### App Details
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.7.0
Microsoft.NET.Sdk.Functions 4.1.0
Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.3.0
Azure.Core 1.22.0

C#

### Screenshots
![image](https://user-images.githubusercontent.com/20400168/166914831-682b2af9-b252-4704-9227-337ade56490a.png)

### If deployed to Azure

- **Timeframe issue observed**:
2022-05-03 and 2022-05-04
Although it has been happening for weeks.

- **Function App name**:
I can't share my function app or storage account name as this is an issue I am experiencing with the company I work at. 
- **Function name(s)**:
 I can't share my function app or storage account name as this is an issue I am experiencing with the company I work at. 
 
- **Azure region**:
East US

- **Orchestration instance ID(s)**:

I'll list several of these to help with the investigation:

00c59fdb17a544c8a95994b5d1d2ddf7:2    (this sub orchestration failed)
0f8cde4630fb4763be6a4fa65278a8c8:2 (this sub orchestration failed)
015c7786e2274b15b39a3535110c7700:2 (this sub orchestration succeeded)

06904d7535924eaa895cc318ff3a961a (this orchestration failed)
2b259bdcb12f454dbba1dee6d754de45 (this orchestration failed)
204c0a7140564241acf790639df11ce2 (this orchestration succeeded)

- **Azure storage account name**:

I can't share my function app or storage account name as this is an issue I am experiencing with the company I work at.

**Comment by davidmrdavid** [comment] 2022-05-05 16:36
Thanks for reaching out @dylanhouston7.

I'm not immediately familiar with this error message, but from its contents it would seem like we're failing to deserialize the exception contents of a Function which was forcibly cancelled by the Azure Functions Host. 

@cgillum, I know you recently worked on some exception-serialization components, so: is this error known to you?

**Comment by lipalath-ms** [comment] 2022-05-11 07:00
I'm seeing a similar issue when I run orchestrations, - some of them intermittently fail with the above exception.

**Comment by dylanhouston7** [comment] 2022-05-11 11:07
> I'm seeing a similar issue when I run orchestration - some of them intermittently fail with the above exception. @[dylanhouston7](https://github.com/dylanhouston7) are you performing a swap while running the function?

Thanks for the reply.  I am not usually swapping while running the functions. However, I do have a deployment slot set up. One thing I did do was make sure that the functions in the slot are not enabled (via ARM template setting). I know that the task hub name is different for the slot than the "production" functions, but I wanted to make sure that the deploy functions don't consume any service bus messages intended for the "production" functions. 

![image](https://user-images.githubusercontent.com/20400168/167835066-840567ee-0e9c-4dec-b14f-2fa39b12112a.png)
![image](https://user-images.githubusercontent.com/20400168/167835355-58ef8289-10e3-4b25-b565-badf39ca5f29.png)

**Comment by davidmrdavid** [comment] 2022-05-12 17:44
Hi @dylanhouston7, and @lipalath-ms.

I've also been reached out internally from a user who is able to reproduce this error when using deployment slots, so I think we have a pattern with that.

In any case, I think this error is caused by a missing case in our Activity-handling logic, where we do not explicitly check against the case of a `FunctionsHostStoppingError`. I've made a very simple PR here with what I believe could be the fix: https://github.com/Azure/azure-functions-durable-extension/pull/2178/files

I'll be testing this over the coming days to see if the serialization error goes away. If it does, I'll update this thread with our deployment plans.

**Comment by davidmrdavid** [comment] 2022-05-12 22:02
Hi @dylanhouston7 , @lipalath-ms.

I just published a private preview release of the Durable Functions Extension which contains the patch in my PR above.
The package name is `Microsoft.Azure.WebJobs.Extensions.DurableTask` (same as before) and it's version is `2.7.2-internal-preview1`.

To download it, you'll need to add the following MyGet feed to your Nuget sources: `https://www.myget.org/F/azure-appservice/api/v3/index.json`.

Could you please give this a try and let me know whether your error is still reproducible with it? Thanks!

**Comment by dylanhouston7** [comment] 2022-05-13 17:24
@davidmrdavid  @lipalath-ms 

The patch appears to be working well for me. Out of the 300+ orchestrations I've run today, I have yet to repro the original issue — and I was getting them fairly frequently before. Orchestrations are completing as expected.

**Comment by davidmrdavid** [comment] 2022-05-13 17:41
That's great to hear @dylanhouston7, thanks for your confirmation.
Since I'm working with @lipalath-ms on a different thread (they're MSFT internal), I'll be closing this thread. Please reach out again if anything comes up :-)

**Closed by davidmrdavid** 2022-05-13 17:41 UTC
Labels: Needs: Investigation :mag:

**Comment by dylanhouston7** [comment] 2022-05-13 17:46
@davidmrdavid thanks for the help! Do you mind keeping the private preview release available until the patch is formally released? It'd help my team be able to test the business logic within our orchestrator.

**Comment by davidmrdavid** [comment] 2022-05-13 18:22
@dylanhouston7: Yeah we usually look to keep those online for a bit (think a few weeks) after the patch is formally released. Frankly, we often times forget we have those online until the next release, so I wouldn't worry too much about those becoming unavailable. Still, I'd appreciate keep a close eye on releases in the coming weeks to ensure you return to the official package.

We don't currently have an ETA for the official release as we just released a patch-release a day ago. I'll be pushing internally for a quick release though

**Comment by dylanhouston7** [comment] 2022-05-16 15:59
> @dylanhouston7 Could you please let me know how you tested with newer package version - My build fails with the error: Error NU1102: Unable to find package Microsoft.Azure.WebJobs.Extensions.DurableTask with version (>= 2.7.2-internal-preview1)

You'll need to reference the following nuget feed in your project, and/or in your build pipelines for the reference to work: `https://www.myget.org/F/azure-appservice/api/v3/index.json`
