### ISSUE TITLE
Are eternal orchestrators deprecated?  + Bug + Advice

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-functions-durable-extension#232] opened 2018-04-06 18:53 UTC
Testing out more reliable and scalable ways to solve a business problem, i tried DF. 

In my scenario I'm using an singleton-eternal orchestrator (constant InstanceID+timer+ContinueAsNew) with fan-in+fan-out pattern and it is actually not eternal.

The workflow actually works, specially the first minutes, but sometime it works for 1 hour, some other times (like today) it only executed the first time.

Main issue here is that the instance status is "running" even though I already got all the Sub Orchestrations done, (got record on my DBs). Each pass should do same things in 5 servers, and i checked those 5 servers and all of them got the data message.

And also I implemented a manual log just to be sure (even if I also has App Insight). When I check those logs, nothing indicates that anything has been stuck or partially done.

Only thing I can do is to terminate it and restart it again. Which I can obviously do with some kind of monitor or alert system.

Is there anyway I can debug this?  How can I provide more info about it?

Are eternal orchestrations deprecated?

https://github.com/Azure/azure-functions-durable-extension/issues/67
https://github.com/Azure/azure-functions-durable-extension/issues/118

Cheers

**Comment by cgillum** [comment] 2018-04-06 20:44
If I understand correctly, the problem you're describing is that `ContinueAsNew` is not actually continuing. Is that accurate?  If so, you might be running into this issue: https://github.com/Azure/azure-functions-durable-extension/issues/182 (note there is a potential fix available). Can you check and see if the updated nuget reference resolves your issue?

To respond to the title of the bug, eternal orchestrations are not deprecated. However, we have de-emphasized them because `ContinueAsNew` will cause messages (raised events and terminate requests) to be dropped and this can easily confuse and/or frustrate folks who expect zero message loss. The eternal orchestrator pattern is still useful for eternal monitor-type scenarios (and we do know people who have been using them that way successfully) but it has to be used with awareness of the `ContinueAsNew` limitations.

**Comment by andreujuanc** [comment] 2018-04-07 10:11
I'm using latest version of AF and DF. (sorry forgot to mention that).

I found that I had a "bad config" that awaited CreateTimer for 10 seconds, changed it for 5 minutes and now it works fine. I left it overnight and it is still working.

I don't know why such little delay would make this fail? Can it be related to the "raised event or termination requests" that arrives near continue as new more often since it was executing every 10 seconds? In my case I didnt have any of those two messages,but I do use LOTS of statusQueryGetUri while debugging and testing.

Can it be the cause of this issue? Short frequency plus lots of statusQuery messages?

Maybe there is a minimum timespan that CreateTimer + ContinueAsNew need to comply with.

**Comment by andreujuanc** [comment] 2018-04-10 08:01
@cgillum I just checked it again and it just stopped.
I will see if I can get any additional info. 

If you or someone can give me any tip on how to get deeper into this, it'd be much appreciated.

**Comment by cgillum** [comment] 2018-04-10 13:33
The first bug I linked to is a timing issue where two messages need to arrive at the same time, one representing ConitinueAsNew, and the other being anything else for that same instance (activity call response, time fired, etc). The result is that the orchestration gets stuck in the ContinuedAsNew state. This race condition is fixed in the latest package version.

By chance do you have a large fan-out of 99 or more, or do you have a durable timer which might fire at the exact same time as or very shortly after your ContinueAsNew call? Those are two situations where I think the race condition bug was getting triggered.

**Comment by andreujuanc** [comment] 2018-04-11 12:08
> This race condition is fixed in the latest package version.

I'm using the latest version (v1.2.2-beta3).  

Application Insight did not record any error, fails or exceptions whatsoever.

I'll explain my design:

**MainOrchestrator** -> Fans out N Targets (servers) (5 in failing tests, in prod will be about 100)
**Each Target** -> Fans out 3 functions via CallActivityAsync
**Each Activity** -> Goes to Target Server via SqlConnection and perform some operations

Things to know about MainOrchestrator:
 - Is singleton (called with predefined instance id and checked for status) 
 - Must be Eternal
 - Starts from a HttpRequest

I was thinking that it might be a port starvation issue, but maybe i'm just plain wrong. Since I'm disposing via using each SqlConnection.  I got to this idea since it seems that the longer the Timer, the longer this solution stays alive, which probably means that ports usage gets distributed along the duration.

I'll see if having a ConcurrentDictionary to keep connections there per target might fix the issue.

I do know that things like HttpClient are Shareble, but I can't find any info about SqlConnections.

**Comment by DannyvanderKraan** [comment] 2018-04-11 12:14
Is that de ADO.NET SQLConnection? It's actually recommended to keep a static instance of it and keep it open. That way it'll use its internal connection pool in the most efficient way.

**Comment by andreujuanc** [comment] 2018-04-11 12:25
@DannyvanderKraan  I'd appreciate any if you point me to any documentation related to it. 

Thanks

**Comment by DannyvanderKraan** [comment] 2018-04-11 12:27
@andreujuanc  Yes of course, sorry: [https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling](url)

**Comment by andreujuanc** [comment] 2018-04-11 12:30
@DannyvanderKraan From Docs:

> We strongly recommend that you always close the connection when you are finished using it so that the connection will be returned to the pool. You can do this using either the Close or Dispose methods of the Connection object, or by opening all connections inside a using statement

From my prev post: 

> Since I'm disposing via using each SqlConnection.

Maybe you got my idea wrong?

**Comment by DannyvanderKraan** [comment] 2018-04-11 12:32
@andreujuanc  Couldn't u Close the connection instead of disposing SqlConnection?

**Comment by DannyvanderKraan** [comment] 2018-04-11 12:51
My best guess is that the docs are not written with Function Apps in mind. I avoid static in general. Until I had to use HttpClient and my functions got slow and had unexpected behaviour. I expect functions (wether durable or not) play along nicer with SqlConnection declared static. But perhaps it's best if you wait for an answer from an expert if it's such a big change. Maybe it's not related to the SqlConnection at all...

**Comment by andreujuanc** [comment] 2018-04-11 13:11
Exactly. I do know and tested that HttpClient is shareable and has no issues as a singleton with functions.

But I haven't done any research about SqlConnection yet. I expected the docs to be more verbose about this.

Anyway, this is just hypothetical and does not mean, as @DannyvanderKraan said, that it's related to my issue. It was just a mean to blindly try to hit and fix the problem. 

For now all the orchestration works fine if I remove the eternal part of it and start it via HttpRequest.

I might use a standard function to call it every X minutes if it completed. Might be a workaround for now.

**Comment by cgillum** [comment] 2018-04-11 14:15
Disposing SqlConnection objects is the right thing to do. They don't have the same problem as HttpClient or other clients which wrap HttpClient. Even if it did, you would at least see some kind of error if it were a connection management problem. And this wouldn't affect orchestration execution since it is being done in an activity function.

The package I was referring to that has a fix is DurableTask.AzureStorage v1.1.3-beta, not Microsoft.Azure.WebJobs.Extensions.DurableTask.

**Comment by andreujuanc** [comment] 2018-04-11 19:07
I just "forced" DurableTask.AzureStorage v1.1.3-beta, and published to testing env. Will follow up with results.

Thanks a lot @cgillum

**Comment by andreujuanc** [comment] 2018-04-11 22:28
Went back and tried again, different timings, and it failed without any errors. 

I enabled dashboard again and there are no entries that shows any indication of an exception.

AppInsight does not shows anything relevant.

Will wait to extensions to update the dependency to "DurableTask.AzureStorage v1.1.3-beta".

**Comment by andreujuanc** [comment] 2018-04-12 12:36
UPDATE:
Migrated code to Monitor Pattern. Will see how it performs.

For those who were a bit skeptic like me: (i thought maybe loop would continue after terminating)

This is basically an infinite while loop. 

And yes IT DOES STOP when the instance is terminated. +1
And yes IT WORKS for singletons as well.  +1

**Comment by andreujuanc** [comment] 2018-04-12 18:04
Went out and back home after 4 hours I checked and it's down. Last insert in my log db is `2018-04-12 15:54:54`  And right now is `20:03:23`.

Ill turn off Fan out and leave the main orchestrator/monitor ON. and see what happens.

**Comment by andreujuanc** [comment] 2018-04-13 19:08
Removed iteration, ie, no monitor or eternal. But it is still singleton.
Used Azure Scheduler to do the start every 2 minutes. (orchestration ends in 20 seconds).

Got a lock inside one of the fans. Orchestrations says "Running".

Could not find anything in AppInsight that gave me any idea of what is going on.

**Comment by cgillum** [comment] 2018-04-13 23:26
So there's a lot of back-and-forth going on here and I'm not sure what to investigate. Can you give me a quick summary of the problem you're running into? Also, if you could give me an Instance ID, the region your deployed to, and a general timeframe, then I can search through our internal telemetry and possibly narrow down the issue.

**Comment by vsadams** [comment] 2018-05-08 03:33
I believe I am running into a similar issue. I have the following setup.

1 timer function that kicks off multiple eternal Orchestrators. 

The Orchestrators used to call multiple activity functions then wait a certain amount of time and run again. I found that was not nearly as performant as I had hoped and have now simplified it greatly. 

My orchestrators now call 1 activity function that does a bunch of stuff then returns a next runtime. Next the orchestrators will just await until the next runtime and finally continue as new.  

What I have found is this works great.... For about 2 or 3 days.... Then my control queues get super backed up and everything pretty much comes to a halt.  My work around is to stop the functions. Delete the queues and log tables and locks then restart the functions. I believe I might be running into some underlying issue but I am unsure on how to fix or how to better my implementation.

**Comment by cgillum** [comment] 2018-05-08 03:59
@vsadams something is definitely not right if your control queues are backing up. If you look into some of the control queue messages, which instance ID do you see most frequently?

Also, if running in Azure, can you share your region, timestamp, and an instance ID? Having that information will allow me to search through our internal telemetry for clues.

Lastly, make sure you're running the latest version of the extension (v1.4.0 at the time of writing).

**Comment by vsadams** [comment] 2018-05-08 15:38
Sure thing!
I will capture the control queues the next time it backs up.
I am running in Azure, here are the details...
**Region:** East US
**Timestamp:**
**Instance IDs:** We create an instanceId based off of a PK in our db so that we can poll status and check health...so there is a lot but here they are
- E6D7E872-BDDA-49DD-84D7-04D93A47B930
- 47E90258-BA4E-4CB7-93B6-06CCDE515EB6
- D2A8E31D-B9D7-4369-CF95-08D56A55CBC8
- B8677D8E-015D-4A28-CF96-08D56A55CBC8
- 064E7EAE-4C60-42CE-CF97-08D56A55CBC8
- 0D6FA3BF-823E-4004-CF98-08D56A55CBC8
- 5E1A469F-95E3-4E16-CF99-08D56A55CBC8
- CA9CFCBA-9360-497F-CF9A-08D56A55CBC8
- A10115D6-75C6-4D3A-94F6-0AA871EA375F
- 8A59892A-8B00-462A-9F58-0BA3A0B0DCE1
- FA113D98-A97D-4DCA-9649-0F5192AF2114
- 043188BD-CB2C-4B38-B67B-154576EE713F
- E020F84B-D465-4150-B168-18142F5C39C7
- 41B1D7FF-450E-4F74-93B7-23D80CB589F6
- 2A653863-5C15-4812-AFDB-241F650A525E
- 36E693BB-AE7D-44C0-9523-2522E0FF0B4C
- 5B33B4B3-4010-46E0-AAFD-2BE8AF0C6B07
- 59107461-9C31-4FA0-B769-3407204CC5AD
- 2D3605AC-205D-4E49-ACE8-379EA75E1C6F
- D280AE0D-5109-4BFA-A8FD-3B366DBA8459
- 36A19388-DB97-40B7-BF03-4005C6ABFBD4
- 30C53A2E-B4F2-4FA0-B5A0-464737D385F1
- C0689A72-5433-46CF-B8A3-48BA0A15122F
- C2161589-115E-4DA7-8DC8-56E2698E8BAF
- EE7A3884-22E9-47B2-BBF6-5EC005A5577E
- FE1D55C8-3B02-4753-B777-5FF5B03AA315
- 1AE4FB3C-8929-40AD-8BF0-6DB6B5F87509
- 592A6CA4-775F-4888-9E46-70BA008237E6
- DAEB1A09-E5D0-4B1C-BD41-730DA129BBBC
- 2D5CBD05-05BA-4054-B8BD-733C56A112EE
- ABE5BC5C-2C95-4301-96A4-79F3D2AA9831
- 204E6F1E-FF1B-4852-A285-7A6A2B653CD8
- 3111C977-6C71-4DB7-B4B5-869F9927E7C9
- 55A8046A-EF7F-40C4-A742-9E8EC2EFB35C
- D528A872-41FD-4299-B8A0-B1AD6B7FD9D1
- 17AAC3D7-2B39-4FD6-8490-B6204EB27B95
- EB9EEC93-8204-4BB8-87D7-C98C9C76C1A3
- 4A8CEC72-6102-43B0-AABC-CABE6DFE2717
- 4B71FC40-2D95-48DE-92C0-D1A46CAF93CD
- 34002D43-42EA-4BCA-AFCC-E86F40CB0E7F
- 890FC9F5-6333-402E-9CDD-E8D65F43EEDB
- 7EEA9433-99A4-4588-8E3A-EEB06F1456E7
- C7DFD31F-FD15-4EBD-AE3D-F2AC5B2E9BF3
- 348B2FA2-CD1E-472B-83AE-F66322450773
- 8D14B23C-D04A-4EEB-A3BC-FB01E7B9C277
- 255151BD-B17C-42CD-B3E7-FE7BDA840773
- 25F168CB-1DDD-49CB-BE43-06CEB3BC70E0
- 34599490-3019-4D9A-96B6-0B8C4420B60A
- 2499954E-F507-4661-9BA1-6D99D40A6DB7
- 06AFDDF4-D2F9-45E5-83EB-EA2A5C2D9DEC
- 02B78C69-59A1-48D8-AB3B-F9AB71D24391
- B2AF2674-3684-42E4-AADA-4B9B4CE5CBB0
- 428A2E1A-6BE6-4DD9-973A-4D652721FD89
- D0471133-08BE-4073-AD22-916FBE06AE5D
- 3223B35E-354F-4E4E-A205-9357200AE8FB
- 7E8B06EC-DDF5-4CAA-B833-B0C03FD9E31F
- 3FA92BD6-26C9-4B00-937D-4F25FD35FDA6
- 525A3FD2-93E9-4F3F-BE49-710414CB9698
- 4569315F-C069-43CD-8B37-8722BD8C02A1
- E6089862-5664-4484-860A-B5241E7A4777
- 05CD3D0D-92ED-44B8-93B8-F181DFCE2664
- 5BD5D277-FBC3-4008-85B3-0202397BFBB6
- E17F7013-318C-4563-A182-1168A75F0C8E
- E8911C3D-75D1-4CF5-A4BC-2A59DFB32087
- 2DE42B66-D91E-4E17-9519-2B8306D1F28A
- 754FE0EE-2991-4781-B3C1-30FD1C1D00A5
- 93C82159-156C-4D62-B3F4-37B69A4587CB
- 65C5643A-6C51-4F42-907E-3BE10F9120E1
- 1E6EF42D-5E32-443A-BB62-3F43099FB2DE
- 823CCACE-3B97-4AFD-BB10-4995F493D372
- 883A29A4-2FAC-4566-B1ED-5ED8FCDB1156
- 24480937-98A8-4926-9022-62C10385A6D2
- 7AA112A0-228C-496B-81B8-64B893036584
- 8A6139DD-103A-42B0-9DA9-66E783B14189
- A6F69C8D-F82C-441D-8FBD-72226456FEF3
- ED11A864-3749-4ED9-B13B-78D8AB6E3531
- C7963159-20E7-4349-8719-8776AC5C3DD4
- 8E5C2BDC-C9F5-4037-B0B2-9735EE16E923
- C93BFF7C-4FA5-430B-9FCD-B5BC0B7627A1
- CBE4ACD5-71C6-4926-9BF6-BB44797C812D
- C92F7846-4C74-41B6-813C-C5687F55F35D
- 1900755D-F548-4199-992A-D418C06262D8
- 25FB59A2-839E-4806-BEAE-E36391393A86
- F217027B-5FC0-4457-AE53-F905E1731526
- 29DD9B3C-F0CF-4FE2-8043-FCEEE52E957C
- 44EE5287-BBCF-46AA-AC9B-28390A1E88B5
- 819A9D22-B12A-46CD-87B8-2DB8401D2EE5
- 40563C81-2013-4FC6-A539-9C2B96A4A4A1
- 1B1B1C67-C8FA-4A7C-AEDC-449C937FFBE9
- 2C4D7A39-40F1-43C8-A717-528B7A12AAC7
- 5C7C1587-4D00-4C4A-B007-56A364203F10
- 9F755C2C-6AF1-429D-B64E-65882D1331EF
- 091F3A15-F022-4323-9635-7E728EDF3AFB
- 05933FA0-3D37-4D19-9EA3-821C165E55CE
- 7FB19012-5C72-451A-9A6E-9D7CD35EB979
- DAF8AB0D-1ADC-411C-901F-A6C39184C578
- F0463403-E494-4EC8-93F9-D68CACB1026A

**Timestamp:** I last noticed the issue at 5/7/2018 9:00 AM EST


Here is our code

<code>
namespace XXX.Services.Functions
{
	public static class AlertingOrchestrator
	{
		private static readonly HashSet<OrchestrationRuntimeStatus> _activeStatuses = new HashSet<OrchestrationRuntimeStatus>
		{
			OrchestrationRuntimeStatus.Running,
			OrchestrationRuntimeStatus.ContinuedAsNew,
			OrchestrationRuntimeStatus.Pending,
		};
		const int ASSUMED_DEAD_DELAY_MINUTES = 10;

		[FunctionName(FunctionNames.ALERTING_ORCHESTRATOR_WATCHER)]
		public static async Task RunAlertingOrchestrationWatcher([TimerTrigger("0/60 * * * * *")]TimerInfo timerInfo, [OrchestrationClient] DurableOrchestrationClientBase starter, [Inject] ILogger logger, [Inject] ICloudManagerReadonlyContext cloudManagerContext)
		{
			try
			{
				var exceptions = new List<Exception>();
				foreach (var configuration in await cloudManagerContext.CollectorConfigurations.ToListAsync())
				{

					try
					{
						await EnsureOrchestratorIsRunning(configuration, starter, logger);
					}
					catch (Exception ex)
					{
						exceptions.Add(ex);
					}
				}

				if (exceptions.Count > 0)
					throw new AggregateException(exceptions.ToArray());
			}
			catch (Exception ex)
			{
				logger.LogError(LogEvent.ALERTING_ORCHESTATOR_MONITOR_ERROR, ex, $"A failure occured while trying to query for {nameof(cloudManagerContext.CollectorConfigurations)}");
				throw;
			}
		}


		private static async Task EnsureOrchestratorIsRunning(CollectorConfiguration configuration, DurableOrchestrationClientBase starter, ILogger logger)
		{
			var collectorConfigurationId = configuration.CollectorConfigurationId.ToString();
			using (logger.BeginScope("Ensuring A Function is running for Collector {ConfigruationName} - {CollectorConfigurationId}", configuration.Name, collectorConfigurationId))
			{
				logger.LogTrace($"Checking on status of Function running for configuration {configuration.Name}");

				var status = await starter.GetStatusAsync(collectorConfigurationId);
				if (status == null)
					logger.LogTrace($"No status for Function running Configuration {configuration.Name}");
				else
					logger.LogTrace($"Retrieved status for Function running Configuration {configuration.Name} ({Enum.GetName(typeof(OrchestrationRuntimeStatus), status.RuntimeStatus)})");

				if (status != null && _activeStatuses.Contains(status.RuntimeStatus))
				{
					try
					{
						ThrowIfUnhealthy(status, configuration, logger);
					}
					catch (Exception ex)
					{
						logger.LogError(LogEvent.ALERTING_ORCHESTATOR_DEAD, ex, $"The job for the collector {configuration.Name} " +
							$"has a status of {Enum.GetName(typeof(OrchestrationRuntimeStatus), status.RuntimeStatus)} " +
							"but is unhealthy.");
						await starter.TerminateAsync(collectorConfigurationId, ex.Message);

					}

					//continue if it was healthy or if it was killed to give the function runtime a second to clean up the blood from the murder. 
					//for some reason the function runtime can get a bunch of kill messages in its queue then it gets in a bad state.
					return;
				}

				//start the function up if there was no status.
				logger.LogTrace($"Invoking orchestration function for configuration {collectorConfigurationId}");
				await starter.StartNewAsync(FunctionNames.ALERTING_ORCHESTRATOR, collectorConfigurationId, collectorConfigurationId);
				logger.LogInformation($"Started {FunctionNames.ALERTING_ORCHESTRATOR} with ID = '{collectorConfigurationId}'.");
			}

		}
		private static void ThrowIfUnhealthy(DurableOrchestrationStatus status, CollectorConfiguration configuration, ILogger logger)
		{
			var now = DateTime.UtcNow;

			var startTimeGracePeriod = status.CreatedTime.AddMinutes(ASSUMED_DEAD_DELAY_MINUTES);
			if (startTimeGracePeriod > now)
			{
				logger.LogTrace($"Configuration {configuration.Name} is running.  The Start Time Grace Period is {startTimeGracePeriod} and now is {now}.  Leaving it alone.");
				return;
			}


			var lastRan = configuration.LastRan ?? status.LastUpdatedTime;
			var nextExpectedRunTime = lastRan.AddSeconds(configuration.IntervalSeconds);
			var assumedDeadTime = nextExpectedRunTime.AddMinutes(ASSUMED_DEAD_DELAY_MINUTES);
			if (assumedDeadTime > now)
			{
				logger.LogTrace($"Configuration {configuration.Name} is running.  The Assumed DeadTime is {assumedDeadTime} and now is {now}.  Leaving it alone.");
				return;
			}

			var reason = $"Configuration {configuration.Name} says its running but the Start Grace Period is {startTimeGracePeriod}, the Assumed DeadTime is {assumedDeadTime}, and now is {now}. It should have ran by now.";
			throw new SystemException(reason);

		}


		[FunctionName(FunctionNames.ALERTING_ORCHESTRATOR)]
		public static async Task RunAlertingEternalOrchestrator([OrchestrationTrigger] DurableOrchestrationContextBase context, ILogger logger)
		{
			var collectorConfigurationId = context.GetInput<Guid>();
			if (!context.IsReplaying) logger.LogTrace($"Executing {FunctionNames.ALERTING_ORCHESTRATOR} for {{CollectorConfigurationId}}", collectorConfigurationId);

			try
			{
				var nextRun = await context.CallActivityAsync<DateTime?>(FunctionNames.ALERTING_PROCESSOR, collectorConfigurationId);
				if (nextRun == null)
					return;

				await context.CreateTimer(nextRun.Value, default(CancellationToken));
				context.ContinueAsNew(context.InstanceId);
			}
			catch (Exception ex)
			{
				logger.LogError(LogEvent.ALERTING_ORCHESTATOR_ERROR, ex, "The Alerting Orchestrator did not complete succesfully");
				throw;
			}
		}

		[FunctionName(FunctionNames.ALERTING_PROCESSOR)]
		public static async Task<DateTime?> Process([ActivityTrigger] Guid collectorConfiguraitonId, [Inject] IAlertingProcessDirector alertingProcessDirector)
		{
			var nextRun = await alertingProcessDirector.ExecuteProcess(collectorConfiguraitonId);
			return nextRun;
		}
	}

}


</code>

**Comment by vsadams** [comment] 2018-05-15 02:26
I see another version of the durable tasks was released, I am going to try that one for a few days and see what happens

**Comment by andreujuanc** [comment] 2018-05-15 07:50
I haven't had the chance to test it with the new version. But I'm planning to do so for sure.

@vsadams let me know if it fixes your issue. Might have something in common.

Cheers

**Comment by vsadams** [comment] 2018-05-26 01:57
@andreujuanc @cgillum  I have been running with version 1.4.1 for over a week now and have not had the issue occur again.  The overall performance seems to have improved also.

**Comment by andreujuanc** [comment] 2018-05-26 21:04
Ohh!! good to know, i haven't had the chance to upgrade the project and test it out. But If I find 10 min, i will certainly do so!!

**Comment by cgillum** [comment] 2018-05-28 00:33
Yes, please try the latest version of the extension. I'm going to close this issue for now. If you encounter the problem again, please open a new GitHub issue with a timestamp, instance ID, and region, and we can investigate further. Thanks!

**Closed by cgillum** 2018-05-28 00:33 UTC
Labels: needs-investigation

**Comment by andreujuanc** [comment] 2018-05-28 20:11
Will do, thanks! Sorry i left it open. I barely have time lately.
