### ISSUE TITLE
Durable function queues keep growing and process becomes slower

### ISSUE THREAD

**Issue by pierre-weceipt** [Azure/azure-functions-durable-extension#104] opened 2017-12-01 16:18 UTC
Hi, I'm still working on same project as #87 and am currently trying to make it work online. 
The whole purpose of the project is to daily import xml datas contained in tar.gz archives into a Neo4j graph database.
My process is as following : 

1. I download archives from external ftp
2. I extract them
3. I process the xml files they contain to turn them in blobs (for the text content) and azure table rows (for metadata). I have multiple rows for each xml corresponding to csv rows that are edited later in the process
4. Once all are extracted and table generated (one table per archive) I start building CSVs
5. A meta orchestrator is started that will fan out a suborchestrator per archive
6. Each suborchestrator fan out n activities (one per CSV needed to be created)
7. Each suborchestrator fan in the activities, when all CSV are built meta orchestrator fan in the suborchestrators
8. Here starts the import, this process is sequential as each archive need to be imported in order, same goes for the CSVs (nodes are imported before relationships)
8 bis. Meta orchestrator loops through archives to import and call a suborchestrator for each of them
9. Suborchestor start in a specific order an activity to import each CSV
10. All is done and my db is up to date...

Well that's how it's supposed to work and it is working when there's only a few archives to deal with. However when initiating a first time import for about 400 of them things don't work smoothly. Building CSVs phase is OK and did finish (I noticed other issues but still not sure what causes them so I'll deal with it later) but the import phase is getting slower and slower as archives are being imported.

I noticed that the number of messages in queues is growing during these imports instead of being constant and that when you stop the process, clean queues and start again it runs fast again. We can also see this in the console where the number of steps between two CSV import activities keeps increasing too.

Any idea? At the moment my only solution is running things from VS because process stops after 50 or so archives when run online.

**Comment by cgillum** [comment] 2017-12-04 20:16
Can you share with me the name of your function app and/or an instance ID + Azure region?  I can take a look at the service telemetry to get an idea of what might be going on.

**Comment by AHoran** [comment] 2017-12-04 22:23
I have a similar issue although with a simpler function chain. Happy to move this to a new issue if required.

I have an OrchestrationTrigger function that has two ActivityTrigger functions chained in sequence. I start my OrchestrationTrigger with a simple queue function.
I test with 9000 items, and my simple queue trigger kicks off the Durable Functions within minutes, and on my consumption plan will spin up a second server. However once this initial queue is processed then the second server drops and my queue will be processed very slowly from there on. Sometimes the remaining server stops/drops (according to App Insights), but visiting the function blade in portal seems to reactivate it.

My two chained activities have some I/O, copying blobs (~100KB), converting xml to json etc. the second function takes 600-1000ms, the first takes 400-700ms.  With those figures I'd expect 3-4 hours to process with a single thread and no overhead from the orchestration. I am seeing over 6 hours to process this small amount of work. However what I'm really expecting is some parallelisation and scaling of the compute to complete it much quicker. I ultimately need to process 300000 items, and with a longer function chain.

functionapp20171204061855 in SE Asia

It is possible that some of my resources are in E Asia too

**Comment by pierre-weceipt** [comment] 2017-12-05 09:48
@cgillum Hi, function app name is landcgraphbuilderprod in West Europe, not sure where I can fin the instance ID though
I cleaned the queues and table when migrating to beta2 yesterday but problem seems to still be here (even when importing 1 archive, some messages are left in the queues at the end).

**Comment by AHoran** [comment] 2017-12-05 22:13
@cgillum and for my version of the issue, my functions have now gone to sleep with 15k+ items in the workqueue

**Comment by cgillum** [comment] 2017-12-06 05:11
Thanks for the details and for upgrading to the latest package. I suspect these two issues are separate, but I'll look at them both. Firstly though, I'll mention a few important things to know about how the system works today:

* There are some known performance blockers that will result in longer processing times - this issue should help *significantly*: https://github.com/Azure/azure-functions-durable-extension/issues/82
* When using the consumption plan, if you detected that there were two workers, then the scale controller is probably working.
* Individual orchestration instances will only ever run on a single VM instance. It's the activity functions which benefit from scaling out. If you're seeing a single instance running, then it's possible that all the activity functions completed and time is being spent by the orchestrator instance processing all the results. This can lead to a significant amount of storage I/O until we introduce caching via https://github.com/Azure/azure-functions-durable-extension/issues/82.
* A workaround for large fan-out would be to fan out into multiple sub-orchestrations. Each sub-orchestration is its own instance and can run on a separate VM for better scale.

**Comment by AHoran** [comment] 2017-12-07 22:41
Re the scale controller. I'm less sure that it is working for me. 

I have a normal (non-durable) queueTrigger to kick off my orchestration. I am processing a batch of 20,000 items. My orchestration has 3 activities run in serial.
When the initial queueTrigger is active I see worker scaling. Once the queuetrigger has processed the backlog then I just have the orchestration and it's activities. At this point there's 20,000 items in the orchestration workqueue. I then start to see VMs dropping off, and eventually ALL VMs will stop even when items (1000s) remain in the orchestration work queue.
If I poke the functions app and wake it up then processing resumes. If I leave it alone it stops.

**Comment by cgillum** [comment] 2017-12-08 19:50
@AHoran you are right, I found your app in the telemetry and the scale controller is failing to correctly monitor your site. Would you mind opening a separate issue for this? I'm wondering if it might be a regression in the `1.1.0-beta2` release, but need to do more investigation.

@pierre-weceipt I still need to look into your issue to confirm the problem. Sorry for the delay.

**Comment by cgillum** [comment] 2017-12-09 19:05
@pierre-weceipt I'm still investigating your case. It's clearly a different issue because I see that the scale controller has scaled your function app out to at least 19 VMs over time. However, it looks like messages in your control queue stop getting successfully processed - so something is stuck.

I'm looking at one particular top-level instance with ID = `ed554737b5d84cabaa7d3ef700cf0b39` and I see that it's trying to process the return values from 8 different sub-orchestrations. For some reason it's failing to delete the queue messages associated with those return values (I believe storage is returning a 404 for those message IDs), resulting in them getting reprocessed every 5 minutes (which is the current invisibility timeout for queue messages). It tries to delete them almost immediately after dequeuing them, so it's not a case where the invisibility timeout would expire - leaving me puzzled. The control queue that manages messages for this instance is _durablefunctionshub-control-02_.

I noticed that this function app is using the `1.0.0-beta` version of the extension. Had you tried using the `1.1.0-beta2` version?  There were some fixes related to queue messaging and I wonder if some of those fixes might apply to your scenario (though I'm not completely sure). If you do try it, please create a separate function app with a separate task hub name (or storage account) to make sure it doesn't conflict with the existing function app.

**Comment by pierre-weceipt** [comment] 2017-12-09 19:26
Hi, I'm using beta2 since it was released and I deleted tables and queues when I switched to it (app is not in prod so I had no problem doing so). When running from local I notice the same issue with return message from suborchestrator being stucked in queue (though the whole process ends succesfully). I did not rerun online since the change though, maybe that's why you're still seing the beta1 telemetry. I should run it online on monday after some changes on the XML extraction part.

**Comment by cgillum** [comment] 2017-12-11 20:05
I do recall fixing an issue in the beta2 release which had similar symptoms: messages getting stuck in the queue even though the orchestration had completed successfully.  Are you using the same storage account locally as you are in Azure or are the accounts separate? I'm just wondering whether your local runs are processing the same stuck messages as the Azure runs.

**Comment by pierre-weceipt** [comment] 2017-12-11 20:08
Yep, during first dev i'm using same storage but cleaning queues between tests.

**Comment by cgillum** [comment] 2017-12-12 00:09
Thanks. I created a simple fan-out/fan-in orchestration that uses sub-orchestrations instead of activity functions and I think I've reproduced the behavior you're seeing - i.e. things complete but some of the messages are not getting cleaned up and are replaying every 5 minutes.  I'll investigate further and let you know when I have a fix.

Thanks for reporting this and for your patience as we work through some of these beta issues. :)

**Comment by cgillum** [comment] 2017-12-12 01:07
I've figured out the issue. Sub-orchestration start messages are being added to the wrong queue in the internal Azure Storage provider [here](https://github.com/Azure/durabletask/blob/378bb3296d63856910cf029a2f57c86474d3df77/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs#L932): we're using the instance ID of the parent orchestration when we need to be using the instance ID of the sub-orchestration. The sub-orchestrations still run and complete successfully but we fail to delete the start messages 75% of the time (because we don't know which queue the message came from), resulting in the queue growing over time and slowing down the processing for everybody.

I'll work on a fix for this and try to get it out later this week.

**Comment by pierre-weceipt** [comment] 2017-12-12 09:10
Glad to read this and looking forward to the patch!

**Comment by cgillum** [comment] 2017-12-12 22:07
OK, I have a patch ready which should fix the root cause of this issue.  Can you try it out and let me know if it helps?  You can simply add the following package reference to your .csproj:

```xml
<PackageReference Include="DurableTask.AzureStorage" Version="1.1.2-beta" />
```

This will update the version of the Durable Task Framework Azure Storage messaging layer used by Durable Functions. Note that you'll need to clear out your queues again.

**Comment by pierre-weceipt** [comment] 2017-12-13 15:46
It worked!! 👏

**Comment by cgillum** [comment] 2017-12-14 01:34
Excellent, thanks for confirming! I'll mark this issue as closed. In a future update of `Microsoft.Azure.WebJobs.Extensions.DurableTask`, I'll include the reference to the updated `DurableTask.AzureStorage` so that everyone will get these fixes automatically.

**Closed by cgillum** 2017-12-14 01:34 UTC
Labels: bug, dtfx, performance
