### ISSUE TITLE
Azure Functions in Python v2 not working with premium plan?

### ISSUE THREAD

**Issue by MihailV1989** [Azure/azure-functions-durable-extension#2435] opened 2023-04-04 15:57 UTC
I've followed the tutorial [Create your first durable function in Python](https://learn.microsoft.com/en-us/azure/azure-functions/durable/quickstart-python-vscode?tabs=windows&pivots=python-mode-decorators) for the Python v2 programming model and after figuring out several issues I've already stated in the [azure-docs repo](https://github.com/MicrosoftDocs/azure-docs/issues/106882), I managed to deploy it to a consumption plan so that it works fine. I'm using VS Code for the deployment as suggested in the tutorial.

Now I wanted to deploy it to a App Service or Premium plan in order to be able to use a virtual network. I did the exact same thing (many times), but it always states `No HTTP triggers found.` and in Azure Portal the Functions list is always empty:
![image](https://user-images.githubusercontent.com/65239934/229844352-1af3ab41-70ea-4a0b-9f8b-abb41e26bd59.png)

I've noticed that the deployment output is different for Consumption and App Service or Premium plan.

Consumption:
```
4:44:18 PM firstdurablepythonv2-1: Starting deployment...
4:44:18 PM firstdurablepythonv2-1: Creating zip package...
4:44:28 PM firstdurablepythonv2-1: Zip package size: 23 MB
4:44:29 PM firstdurablepythonv2-1: Fetching changes.
4:44:34 PM firstdurablepythonv2-1: Updating submodules.
4:44:35 PM firstdurablepythonv2-1: Preparing deployment for commit id 'fbab6ac3-c'.
4:44:35 PM firstdurablepythonv2-1: PreDeployment: context.CleanOutputPath False
4:44:35 PM firstdurablepythonv2-1: PreDeployment: context.OutputPath /home/site/wwwroot
4:44:35 PM firstdurablepythonv2-1: Repository path is /tmp/zipdeploy/extracted
4:44:35 PM firstdurablepythonv2-1: Running oryx build...
4:44:35 PM firstdurablepythonv2-1: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.9.7 -p packagedir=.python_packages/lib/site-packages
4:44:37 PM firstdurablepythonv2-1: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
4:44:37 PM firstdurablepythonv2-1: You can report issues at https://github.com/Microsoft/Oryx/issues
4:44:37 PM firstdurablepythonv2-1: Oryx Version: 0.2.20210120.1, Commit: 66c7820d7df527aaffabd2563a49ad57930999c9, ReleaseTagName: 20210120.1
4:44:37 PM firstdurablepythonv2-1: Build Operation ID: |UZsyVgwlM2M=.64cb0c7_
4:44:37 PM firstdurablepythonv2-1: Repository Commit : fbab6ac3-c69b-4414-ad32-3b70759f8d65
4:44:37 PM firstdurablepythonv2-1: Detecting platforms...
4:44:40 PM firstdurablepythonv2-1: Detected following platforms:
4:44:40 PM firstdurablepythonv2-1:   python: 3.9.7
4:44:40 PM firstdurablepythonv2-1:   dotnet: 3.1.32
4:44:40 PM firstdurablepythonv2-1: Version '3.9.7' of platform 'python' is not installed. Generating script to install it...
4:44:40 PM firstdurablepythonv2-1: Version '3.1.32' of platform 'dotnet' is not installed. Generating script to install it...
4:44:40 PM firstdurablepythonv2-1: Source directory     : /tmp/zipdeploy/extracted
4:44:40 PM firstdurablepythonv2-1: Destination directory: /home/site/wwwroot
4:44:40 PM firstdurablepythonv2-1: Downloading and extracting 'python' version '3.9.7' to '/tmp/oryx/platforms/python/3.9.7'...
4:44:41 PM firstdurablepythonv2-1: Downloaded in 1 sec(s).
4:44:41 PM firstdurablepythonv2-1: Verifying checksum...
4:44:41 PM firstdurablepythonv2-1: Extracting contents...
4:44:45 PM firstdurablepythonv2-1: Done in 5 sec(s).
4:44:45 PM firstdurablepythonv2-1: Downloading and extracting 'dotnet' version '3.1.426' to '/tmp/oryx/platforms/dotnet/3.1.426'...
4:44:50 PM firstdurablepythonv2-1: Downloaded in 5 sec(s).
4:44:50 PM firstdurablepythonv2-1: Verifying checksum...
4:44:50 PM firstdurablepythonv2-1: Extracting contents...
4:44:56 PM firstdurablepythonv2-1: Done in 11 sec(s).
4:44:56 PM firstdurablepythonv2-1: Python Version: /tmp/oryx/platforms/python/3.9.7/bin/python3.9
4:44:56 PM firstdurablepythonv2-1: Running pip install...
4:44:56 PM firstdurablepythonv2-1: [14:44:56+0000] Collecting azure-functions
4:44:56 PM firstdurablepythonv2-1: [14:44:56+0000]   Downloading azure_functions-1.13.3-py3-none-any.whl (163 kB)
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000] Collecting azure-functions-durable
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000]   Downloading azure_functions_durable-1.2.2-py3-none-any.whl (215 kB)
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000] Collecting python-dateutil>=2.8.0
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000] Collecting requests==2.*
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000]   Downloading requests-2.28.2-py3-none-any.whl (62 kB)
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000] Collecting furl>=2.1.0
4:44:57 PM firstdurablepythonv2-1: [14:44:57+0000]   Downloading furl-2.1.3-py2.py3-none-any.whl (20 kB)
4:44:58 PM firstdurablepythonv2-1: [14:44:58+0000] Collecting aiohttp>=3.6.2
4:44:58 PM firstdurablepythonv2-1: [14:44:58+0000]   Downloading aiohttp-3.8.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000] Collecting six>=1.5
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000]   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000] Collecting charset-normalizer<4,>=2
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000]   Downloading charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000] Collecting idna<4,>=2.5
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000]   Downloading idna-3.4-py3-none-any.whl (61 kB)
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000] Collecting certifi>=2017.4.17
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000]   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000] Collecting urllib3<1.27,>=1.21.1
4:44:59 PM firstdurablepythonv2-1: [14:44:59+0000]   Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
4:45:00 PM firstdurablepythonv2-1: [14:45:00+0000] Collecting orderedmultidict>=1.0.1
4:45:00 PM firstdurablepythonv2-1: [14:45:00+0000]   Downloading orderedmultidict-1.0.1-py2.py3-none-any.whl (11 kB)
4:45:00 PM firstdurablepythonv2-1: [14:45:00+0000] Collecting frozenlist>=1.1.1
4:45:00 PM firstdurablepythonv2-1: [14:45:00+0000]   Downloading frozenlist-1.3.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
4:45:01 PM firstdurablepythonv2-1: [14:45:01+0000] Collecting multidict<7.0,>=4.5
4:45:01 PM firstdurablepythonv2-1: [14:45:01+0000]   Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
4:45:01 PM firstdurablepythonv2-1: [14:45:01+0000] Collecting attrs>=17.3.0
4:45:01 PM firstdurablepythonv2-1: [14:45:01+0000]   Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
4:45:01 PM firstdurablepythonv2-1: [14:45:01+0000] Collecting aiosignal>=1.1.2
4:45:01 PM firstdurablepythonv2-1: [14:45:01+0000]   Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
4:45:02 PM firstdurablepythonv2-1: [14:45:02+0000] Collecting yarl<2.0,>=1.0
4:45:02 PM firstdurablepythonv2-1: [14:45:02+0000]   Downloading yarl-1.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (264 kB)
4:45:02 PM firstdurablepythonv2-1: [14:45:02+0000] Collecting async-timeout<5.0,>=4.0.0a3
4:45:02 PM firstdurablepythonv2-1: [14:45:02+0000]   Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
4:45:02 PM firstdurablepythonv2-1: [14:45:02+0000] Installing collected packages: azure-functions, six, python-dateutil, charset-normalizer, idna, certifi, urllib3, requests, orderedmultidict, furl, frozenlist, multidict, attrs, aiosignal, yarl, async-timeout, aiohttp, azure-functions-durable
4:45:04 PM firstdurablepythonv2-1: [14:45:04+0000] Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 attrs-22.2.0 azure-functions-1.13.3 azure-functions-durable-1.2.2 certifi-2022.12.7 charset-normalizer-3.1.0 frozenlist-1.3.3 furl-2.1.3 idna-3.4 multidict-6.0.4 orderedmultidict-1.0.1 python-dateutil-2.8.2 requests-2.28.2 six-1.16.0 urllib3-1.26.15 yarl-1.8.2
4:45:05 PM firstdurablepythonv2-1: WARNING: You are using pip version 20.2.3; however, version 23.0.1 is available.
4:45:05 PM firstdurablepythonv2-1: You should consider upgrading via the '/tmp/oryx/platforms/python/3.9.7/bin/python3.9 -m pip install --upgrade pip' command.
4:45:05 PM firstdurablepythonv2-1: Done in 9 sec(s).
4:45:05 PM firstdurablepythonv2-1: Preparing output...
4:45:05 PM firstdurablepythonv2-1: Copying files to destination directory '/home/site/wwwroot'...
4:45:06 PM firstdurablepythonv2-1: Done in 1 sec(s).
4:45:06 PM firstdurablepythonv2-1: Removing existing manifest file
4:45:06 PM firstdurablepythonv2-1: Creating a manifest file...
4:45:06 PM firstdurablepythonv2-1: Manifest file created.
4:45:06 PM firstdurablepythonv2-1: Done in 26 sec(s).
4:45:07 PM firstdurablepythonv2-1: Running post deployment command(s)...
4:45:07 PM firstdurablepythonv2-1: Generating summary of Oryx build
4:45:07 PM firstdurablepythonv2-1: Deployment Log file does not exist in /tmp/oryx-build.log
4:45:07 PM firstdurablepythonv2-1: The logfile at /tmp/oryx-build.log is empty. Unable to fetch the summary of build
4:45:07 PM firstdurablepythonv2-1: Triggering recycle (preview mode disabled).
4:45:07 PM firstdurablepythonv2-1: Linux Consumption plan has a 1.5 GB memory limit on a remote build container.
4:45:07 PM firstdurablepythonv2-1: To check our service limit, please visit https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits
4:45:07 PM firstdurablepythonv2-1: Writing the artifacts to a squashfs file
4:45:22 PM firstdurablepythonv2-1: Parallel mksquashfs: Using 1 processor
4:45:22 PM firstdurablepythonv2-1: Creating 4.0 filesystem on /home/site/artifacts/functionappartifact.squashfs, block size 131072.
4:45:22 PM firstdurablepythonv2-1: [=============================================================/] 1465/1465 100%
4:45:22 PM firstdurablepythonv2-1: Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
4:45:22 PM firstdurablepythonv2-1: 	compressed data, compressed metadata, compressed fragments, compressed xattrs
4:45:22 PM firstdurablepythonv2-1: 	duplicates are removed
4:45:22 PM firstdurablepythonv2-1: Filesystem size 26115.97 Kbytes (25.50 Mbytes)
4:45:22 PM firstdurablepythonv2-1: 	34.11% of uncompressed filesystem size (76554.29 Kbytes)
4:45:22 PM firstdurablepythonv2-1: Inode table size 11910 bytes (11.63 Kbytes)
4:45:22 PM firstdurablepythonv2-1: 	31.54% of uncompressed inode table size (37766 bytes)
4:45:22 PM firstdurablepythonv2-1: Directory table size 11395 bytes (11.13 Kbytes)
4:45:22 PM firstdurablepythonv2-1: 	36.05% of uncompressed directory table size (31607 bytes)
4:45:22 PM firstdurablepythonv2-1: Number of duplicate files found 51
4:45:22 PM firstdurablepythonv2-1: Number of inodes 1111
4:45:22 PM firstdurablepythonv2-1: Number of files 975
4:45:22 PM firstdurablepythonv2-1: Number of fragments 84
4:45:22 PM firstdurablepythonv2-1: Number of symbolic links  0
4:45:22 PM firstdurablepythonv2-1: Number of device nodes 0
4:45:22 PM firstdurablepythonv2-1: Number of fifo nodes 0
4:45:22 PM firstdurablepythonv2-1: Number of socket nodes 0
4:45:22 PM firstdurablepythonv2-1: Number of directories 136
4:45:22 PM firstdurablepythonv2-1: Number of ids (unique uids + gids) 1
4:45:22 PM firstdurablepythonv2-1: Number of uids 1
4:45:22 PM firstdurablepythonv2-1: 	root (0)
4:45:22 PM firstdurablepythonv2-1: Number of gids 1
4:45:22 PM firstdurablepythonv2-1: 	root (0)
4:45:22 PM firstdurablepythonv2-1: Creating placeholder blob for linux consumption function app...
4:45:22 PM firstdurablepythonv2-1: SCM_RUN_FROM_PACKAGE placeholder blob scm-latest-firstdurablepythonv2-1.zip located
4:45:22 PM firstdurablepythonv2-1: Uploading built content /home/site/artifacts/functionappartifact.squashfs for linux consumption function app...
4:45:23 PM firstdurablepythonv2-1: Resetting all workers for firstdurablepythonv2-1.azurewebsites.net
4:45:23 PM firstdurablepythonv2-1: Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip. Remote build.
4:45:39 PM firstdurablepythonv2-1: Syncing triggers...
4:45:46 PM firstdurablepythonv2-1: Querying triggers...
4:45:49 PM firstdurablepythonv2-1: HTTP Trigger Urls:
  http_start: https://firstdurablepythonv2-1.azurewebsites.net/api/...
```

Here on the last row you can see that the Trigger is found.

App Service or Premium plan:
```
4:49:03 PM firstdurablepythonv2-2: Starting deployment...
4:49:03 PM firstdurablepythonv2-2: Creating zip package...
4:50:15 PM firstdurablepythonv2-2: Zip package size: 23 MB
4:50:20 PM firstdurablepythonv2-2: Fetching changes.
4:50:21 PM firstdurablepythonv2-2: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/49ac3977-b643-481c-a50f-a42d31f79be8.zip (21.94 MB) to /tmp/zipdeploy/extracted
4:50:36 PM firstdurablepythonv2-2: Updating submodules.
4:50:37 PM firstdurablepythonv2-2: Preparing deployment for commit id '1f99850d-9'.
4:50:38 PM firstdurablepythonv2-2: PreDeployment: context.CleanOutputPath False
4:50:38 PM firstdurablepythonv2-2: PreDeployment: context.OutputPath /home/site/wwwroot
4:50:38 PM firstdurablepythonv2-2: Generating deployment script.
4:50:39 PM firstdurablepythonv2-2: Using the following command to generate deployment script: 'azure site deploymentscript -y --no-dot-deployment -r "/tmp/zipdeploy/extracted" -o "/home/site/deployments/tools" --basic --sitePath "/tmp/zipdeploy/extracted"'.
4:50:45 PM firstdurablepythonv2-2: Generating deployment script for Web Site
4:50:45 PM firstdurablepythonv2-2: Generated deployment script files
4:50:46 PM firstdurablepythonv2-2: Running deployment command...
4:50:46 PM firstdurablepythonv2-2: Command: "/home/site/deployments/tools/deploy.sh"
4:50:46 PM firstdurablepythonv2-2: Handling Basic Web Site deployment.
4:50:48 PM firstdurablepythonv2-2: Kudu sync from: '/tmp/zipdeploy/extracted' to: '/home/site/wwwroot'
4:50:49 PM firstdurablepythonv2-2: Copying file: '.funcignore'
4:50:49 PM firstdurablepythonv2-2: Copying file: 'extensions.csproj'
4:50:49 PM firstdurablepythonv2-2: Copying file: 'function_app.py'
4:50:49 PM firstdurablepythonv2-2: Copying file: 'getting_started.md'
4:50:49 PM firstdurablepythonv2-2: Copying file: 'host.json'
4:50:49 PM firstdurablepythonv2-2: Copying file: 'requirements.txt'
4:50:49 PM firstdurablepythonv2-2: Copying file: '__pycache__/function_app.cpython-39.pyc'
4:50:50 PM firstdurablepythonv2-2: Copying file: 'bin/Azure.Core.dll'
4:50:50 PM firstdurablepythonv2-2: Copying file: 'bin/Azure.Identity.dll'
4:50:50 PM firstdurablepythonv2-2: Copying file: 'bin/Castle.Core.dll'
4:50:50 PM firstdurablepythonv2-2: Copying file: 'bin/DurableTask.AzureStorage.dll'
4:50:51 PM firstdurablepythonv2-2: Copying file: 'bin/DurableTask.Core.dll'
4:50:51 PM firstdurablepythonv2-2: Copying file: 'bin/Google.Protobuf.dll'
4:50:52 PM firstdurablepythonv2-2: Copying file: 'bin/Grpc.Core.Api.dll'
4:50:52 PM firstdurablepythonv2-2: Copying file: 'bin/Grpc.Core.dll'
4:50:52 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.ApplicationInsights.dll'
4:50:52 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Authentication.Abstractions.dll'
4:50:53 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Authentication.Core.dll'
4:50:53 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Authorization.Policy.dll'
4:50:53 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Authorization.dll'
4:50:53 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Connections.Abstractions.dll'
4:50:53 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Hosting.Abstractions.dll'
4:50:54 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Hosting.Server.Abstractions.dll'
4:50:54 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Hosting.dll'
4:50:54 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Http.Abstractions.dll'
4:50:54 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Http.Extensions.dll'
4:50:55 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Http.Features.dll'
4:50:55 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Http.dll'
4:50:55 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.JsonPatch.dll'
4:50:55 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Mvc.Abstractions.dll'
4:50:56 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Mvc.Core.dll'
4:50:56 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Mvc.Formatters.Json.dll'
4:50:56 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll'
4:50:56 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.ResponseCaching.Abstractions.dll'
4:50:57 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Routing.Abstractions.dll'
4:50:57 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Routing.dll'
4:50:57 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Server.Kestrel.Core.dll'
4:50:57 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Server.Kestrel.Https.dll'
4:50:57 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll'
4:50:57 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll'
4:50:58 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.Server.Kestrel.dll'
4:50:58 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.AspNetCore.WebUtilities.dll'
4:50:58 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.Azure.WebJobs.Extensions.DurableTask.dll'
4:50:58 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.Azure.WebJobs.Host.dll'
4:50:58 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.Azure.WebJobs.dll'
4:50:59 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.Bcl.AsyncInterfaces.dll'
4:50:59 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.Build.Framework.dll'
4:50:59 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.Build.Utilities.Core.dll'
4:50:59 PM firstdurablepythonv2-2: Copying file: 'bin/Microsoft.DotNet.PlatformAbstractions.dll'
4:50:59 PM firstdurablepythonv2-2: Omitting next output lines...
4:51:07 PM firstdurablepythonv2-2: Finished successfully.
4:51:07 PM firstdurablepythonv2-2: Running post deployment command(s)...
4:51:08 PM firstdurablepythonv2-2: Triggering recycle (preview mode disabled).
4:51:08 PM firstdurablepythonv2-2: Deployment successful. deployer = ms-azuretools-vscode deploymentPath = Functions App ZipDeploy. Extract zip.
4:51:30 PM firstdurablepythonv2-2: Syncing triggers...
4:51:37 PM firstdurablepythonv2-2: Querying triggers...
4:51:42 PM firstdurablepythonv2-2: **No HTTP triggers found**.
```

And here on the last row it states that the HTTP trigger was not found.

Why is this so? Is it because of the different initial Application Settings? On the image below you can see the App Settings first of a newly created Consumption plan Function and then of App Service plan Function. I've only added the AzureWebJobsFeatureFlag setting, as this is needed for the python v2 model to work at all. You can see that the Consumption plan Function has additionally two settings beginning with "WEBSITE_CONTENT[..]".
![image](https://user-images.githubusercontent.com/65239934/229848669-1e8e3dcf-5630-4d32-962a-57a68bba9b3f.png)

Or is it because the deployment for Consumption and App Service or Premium plan is different? I've also tried the continuous deployment using a "Local Git", but still the same. Can I make a manual deployment to avoid the issue? 

I'm creating the Functions in a new Resource group using the wizard from Azure Portal.

Thanks!

**Comment by MihailV1989** [comment] 2023-04-06 14:11
It seems like the deployment can really be successful despite the error "No HTTP triggers found.". The Functions and the HTTP trigger just don't show right away like on the Consumption plan and it takes a while to appear. In my case that happened while I was refreshing the page. Maybe also after I restarted the function app which is one of the official ways to [sync the triggers](https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#trigger-syncing). In one case I had to wait for about 5 mins to see functions and HTTP trigger which is not what I would expect from the more expensive App Service plan.

What is more peculiar though is that the functions and the HTTP trigger shows only when the deployment in VS Code was performed after the durable function was first run locally in VS Code:

1. 
![image](https://user-images.githubusercontent.com/65239934/230324044-94b8ab12-4bf2-4bc9-b985-62d830720b91.png)

Maybe you also have to refresh the list with functions so that it shows the functions and not like in my case an error:
2.
![image](https://user-images.githubusercontent.com/65239934/230324424-b2494f83-e246-4bbd-ad43-b7cc5f1a08f2.png)

3.
![image](https://user-images.githubusercontent.com/65239934/230329988-b9f107a7-44e6-45e4-824a-1fdbbf4ff202.png)

So maybe this is actually a problem with Azure Functions Core Tools in VS Code.

The next problem comes when you make a more complex Durable Function using external libraries and you forget to update the requirements.txt. Happens on both Consumption and App Service plan. You get the same problem from above, where the Functions and the triggers don't show up. And you don't get any error to help you find the problem. Normally you should get an error when running the function locally, but if you weren't careful and installed the python libraries globally instead in the virtual environment of the Azure Function, then you will have hard time finding the issue.

**Comment by davidmrdavid** [comment] 2023-04-06 16:14
Hi @MihailV1989,

Thanks for reaching out and sorry to hear about the blockers you've experienced. I'll reply to the azure-docs feedback on that thread.

Regarding whether this should work on the Premium plan: it should. I can do test on my end to validate this. Before doing so, I'd like to confirm: you're deploying to a brand new elastic premium app, correct? Also to confirm: after sync'ing the Triggers and waiting 5 minutes (which does seem like a long time), your app is functioning correctly, right?

Regarding needing to use external libraries: yes, you will need to update `requirements.txt`. The reason for this is that we need a way to determine what libraries to install on your Azure machine, and `requirements.txt` is our source for that data. When developing locally, we recommend utilizing `requirements.txt` to track dependencies as well as a Python virtual environment so that dependencies are installed locally  to the app instead of globally. The latter will help prevent surprises when dependencies are not available on the deployed app.

**Comment by MihailV1989** [comment] 2023-04-19 12:49
Hi @davidmrdavid, 

Thanks for the info. Yes, after sync'ing the Triggers and waiting 5 minutes the app was functioning correctly. As of this week the problems I've experienced are not occurring anymore. Deploying from VS Code works straight forward without first starting the App locally and the 5 mins delay to show the functions is gone. I'm still using the same Basic App Service plan (I've tried the premium plan only in the very beginning). The "No HTTP triggers found" error is also not occurring anymore when everything is correct.

In any case it would be nice to have a more advanced error report for the case when the deployed durable functions does not appear in the function app at all.

**Comment by davidmrdavid** [comment] 2023-04-27 20:27
Thanks for the update @MihailV1989. I agree the deployment status reporting can be misleading at times, I'll pass on the feedback. I'll be closing this issue for now given that it seems the functionality, on the Durable Functions side, is working as intended.

**Closed by davidmrdavid** 2023-04-27 20:27 UTC
Labels: Needs: Attention :wave:
