### ISSUE TITLE
Jobs silently stalling, not responding to RaiseEvent

### ISSUE THREAD

**Issue by lxalln** [Azure/azure-functions-durable-extension#1086] opened 2019-12-03 19:54 UTC
### Description
After raising events, our orchestrations are not continuing. We have seen jobs that are stuck for days. Manually triggering (by calling the HTTP function that was originally called to raise the event) seems to wake the job up again.

We are experiencing heavy load for us, but we are only running in the region of 2-3k orchestrations per day. The control queues have ~2k messages in them, but none of them are currently visible.

I can provide more detailed logs if that'll help, but we're a little stuck with how to diagnose this further.

### Expected behavior
We expect our durable functions to continue after they receive an external event

### Actual behavior
The functions simply stall. We can see in the event being posted to the queue (in app insights) and the orchestration log message suggesting that the job is now 'scheduled', but the history of the job itself shows no record of the event being raised.

### Known workarounds
We have resorted to a poll against the durable function which is firing the external event over and over

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: v2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### If deployed to Azure

- **Timeframe issue observed**: ~a week
- **Function name(s)**: CheckoutPipeline-Orchestrator
- **Azure region**: uksouth
- **Orchestration instance ID(s)**: bypass_6l21zzi9auk
- **Azure storage account name**: giftupfuji

**Comment by lxalln** [comment] 2019-12-04 13:00
Note: We have downgraded to v1.8.3 of Durable Functions extension, and that appears to have resolved our jobs getting stuck.

**Comment by ConnorMcMahon** [comment] 2019-12-05 19:46
@lxalln, I'm glad that your issue is resovled.

In the interest of diagnosing the issue, I have a couple questions.

1. Do you specify a taskhub name in your application?
2. Were these inflight orchestrations scheduled back in 1.8.3 that were not reacting to events posted after upgrading to 2.0.0?

If that is the case, this is likely a duplicate of #1071.

Otherwise, it is also possible that this is related to the incorrect triggers sent to our scale controller logic like in #1064.

**Comment by lxalln** [comment] 2019-12-05 20:04
@ConnorMcMahon 

1. We did not specify a name, and we were caught out by the change in behaviour there, but accepted the loss of inflight orchestrations (due to table name changes)
2. Yes, but we lost those, which is fine. We have since moved back to 1.8.3, with a named taskhub (the same name that 2.0.0 auto generated) which has successfully picked up from where 2.0.0 was, and completed orchestrations.

I spotted the scaling issue today, it sounded like it might be relevant, however other reasons were causing our functions to scale, so there was plenty of available compute.

I'm not too familiar with how the scaling works for a class library functionsapp, but I assume all functions are available on all instances.

We have another issue open (#1089) and it was mentioned on there that running as netcoreapp2.2 is strange, so maybe that is pertinent.

**Comment by ConnorMcMahon** [comment] 2020-02-25 23:34
@lxalln 

Sorry for the delayed response.

Given your response, it sounds like this was almost certainly a duplicate of #1071, which is now resolved as a part of 2.1.1.

If you are still encountering this issue on our latest bits, then please reopen the issue!

**Closed by ConnorMcMahon** 2020-02-25 23:34 UTC
