### ISSUE TITLE
Delay noticed in processing when instances auto-scale back in

### ISSUE THREAD

**Issue by jforage-sw** [Azure/azure-functions-durable-extension#2651] opened 2023-10-27 14:54 UTC
### Description
> Running a .net 7 isolated function on a dedicated consumption plan with the following nuget packages
![image](https://github.com/Azure/azure-functions-durable-extension/assets/133007260/17befc86-4221-448a-9960-00c4b3b92a7d)
We are experiencing noticeable delays of varying times but often up to 10 minutes of processing time while the number of instances scales back down. Is this expected behavior? If so, can we mitigate against this?

### Expected behavior
> We would expect very little delay in processing whilst auto-scaling back down as the demand on instances decreases.

### Actual behavior
> Whilst fanning out tasks in parallel, we see the number of instances increases as demand increases. The tasks get processed and we fan back in again. As the number of instances starts to decrease we are often left with a few tasks remaining to be executed (to a factor 4x, based on the number of threads available per instance). No errors in the logs and no activity in the live metrics. Then after a period of anywhere between 0 and 10 minutes, the tasks are picked up and executed by an available thread on a remaining instance.

- **Timeframe issue observed**: 2023-10-27 14:03 - 14:09 UTC
- **Function App name**: `func-sandbox1-dts`
- **Function name(s)**: multiple but one example being `TransactionResetEngine_OrchestrationFunction`
- **Azure region**: Central US
- **Orchestration instance ID(s)**: `bb9e2447d8555c0484bd480cbed05572`
- **Azure storage account name**: `funcsandbox1dts`

**Comment by RichardBurns1982** [comment] 2023-10-29 08:08
It is possible this is due to:

maxConcurrentOrchestratorFunctions: 4
maxConcurrentActivityFunctions: 4

As the delay we see at the end is always a multiple of 4.

We scale out on potentially thousands of batches which are tracked in the DB so we can see when the batch is started and completed in an activity.  We watch as thousands of db entries are marked as completed in quick succession over seconds/minutes with a max scale out factor of 5 or 10 and then gets to 16 (12, 8, 4 always a multiple of 4 though) and stops and there is no DB activity, no function activity, nothing in live metrics for sometimes 1 or 2 minutes, at worse 5 - 10 minutes.

**Comment by RichardBurns1982** [comment] 2023-11-03 16:43
We've spent a fair amount of time investigating this and we have put together a sandbox which seems to fairly consistently demonstrate the problem.  

We are running on Consumption with a scale out limit of 10 and using table storage with 16 partitions.  We run 500 batches and we are regularly seeing the last jobs sat and not picked up for many minutes.  As the image below shows the scaled out servers are sat there doing nothing but they won't pick up the last jobs:

![image](https://github.com/Azure/azure-functions-durable-extension/assets/67505780/f1db4c48-5ee7-412b-981e-8eacc4b617ef)

After 4 minutes and 19 seconds the final 4 jobs were run.

**Comment by nytian** [comment] 2024-02-13 00:34
Hi, @jforage-sw . I did a query with the information you provided. 

The orchestrator is waiting for the next activities to be executed, while the corresponding `TaskScheduled` message was received by worker _dw0SmallDedicatedWebWorkerRole_IN_hr0HostRole-3184-VM-16_ and that's where the stuck issue happened.  This worker shut down before it finished processing this message. And at durable functions, if a message is read by a VM, it will be marked as invisible to other workers first.  If the message was processed successfully, it will be deleted from the queue. Otherwise, it will be visible to other workers after 5 minutes. Thus this message was invisible to other workers except _dw0SmallDedicatedWebWorkerRole_IN_hr0HostRole-3184-VM-16_ at 2023-10-27 14:04:23.5809861 UTC, which didn't finish the processing successfully. And at 10/27/2023 2:09:23 PM UTC this message was visible to others again and was picked up by a healthy worker. Thus, the orchestrator resumed.

**Comment by jforage-sw** [comment] 2024-02-13 07:15
Thanks for your reply @nytian. Any indication as to why the worker shutdown before finishing the processing all of the activities? There were no application errors in the logs to indicate any programming exceptions thrown during this time, so it suggests it's an infrastructure issue your end. Seems odd that workers can be auto scaled in while they still have tasks queued

**Comment by nytian** [comment] 2024-02-13 21:40
Hi, @jforage-sw  Did this scenario happen frequently or just one time?

**Comment by jforage-sw** [comment] 2024-02-13 22:28
@nytian Yes, consistently happens

**Comment by nytian** [comment] 2024-02-13 22:52
@jforage-sw  Can you help provide me another orchestrator instanceId and timestamp that has the same issue? I would need to verify this behavior is not random. Thanks!

**Comment by jforage-sw** [comment] 2024-02-13 23:22
@nytian Will get back to you on this

**Comment by RichardBurns1982** [comment] 2024-02-14 11:13
> @jforage-sw Can you help provide me another orchestrator instanceId and timestamp that has the same issue? I would need to verify this behavior is not random. Thanks!

@nytian We have removed all of our orchestration instances where we were testing this behaviour.  It happened across at least 3 environments but we could not consistently reproduce I'm afraid.

Our best guess was it was happening as instances were being scaled back, we created a sandbox where we fanned out and created 1000 activities which were performing DB and CPU intensive work and each updated a table so we could see how many had completed.  We were regularly seeing between 980 - 999 completed and the last 1 - 20 would complete at some point in the next 5 minutes.

I'm sorry we can't provide more details, as stated we just couldn't consistently reproduce the problem.

**Comment by nytian** [comment] 2024-02-14 21:38
Thanks, @jforage-sw , @RichardBurns1982  for the message provided. That makes sense, I don't need more instanceIds. VM can shutdown itself even when there is still work ongoing. This won't impact DF performance since message will only be deleted after it was processed, which means that this message will finally be picked up by other active VMs.  In our case, the VM shut down because the scale controller voted for scaling in. So, the problem here is that the default message visibility time is too long. And this can be configured at host.json via configuration _"controlQueueVisibilityTimeout"_.  Please refer [this page](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings?tabs=python-v2%2Cin-process%2C2x-durable-functions&pivots=programming-language-csharp#hostjson-settings). We can update this value to a more ideal one.

**Comment by jforage-sw** [comment] 2024-02-15 07:58
@nytian My understanding of the visibility timeout configuration setting is that it controls the time interval between retries if the processing of a message fails. Is this correct? If so, presumably there's a chance that a control / work item can get re-queued while it's being actively processed, not just failed? I understand this shouldn't matter provided you have idempotency built in but just wanted to double check the logic here

**Comment by nytian** [comment] 2024-02-16 18:08
@jforage-sw Yeah your understanding is correct. If we set the visibility time out configuration too short, it's possible that a message got processed multiple times by several VMs. But that's fine, duplicate result will be discarded.

**Comment by nytian** [comment] 2024-02-21 23:21
@jforage-sw  Hey just wonder if we can consider close this PR. Let me know if you have other questions. Thanks!

**Comment by jforage-sw** [comment] 2024-02-22 02:57
@nytian Yes, go ahead. We've not yet had a chance to test the configuration changes you advised but it sounds like the probable fix and now we better understand the behaviour we have been witnessing. Thanks for your help

**Closed** 2024-02-22 19:44 UTC
Labels: Performance, P1
