### ISSUE TITLE
Quotes added around activity function string parameter in isolated mode

### ISSUE THREAD

**Issue by buckprime** [Azure/azure-functions-durable-extension#2674] opened 2023-11-14 23:01 UTC
### Description

Using Microsoft.Azure.Functions.Worker.Extensions.DurableTask version 1.1.0, when you pass a string parameter to an activity function (as a parameter with the [ActivityTrigger] attribute), the activity function receives it with quotes added around it.

I have an app that uses Durable Functions isolated mode in .NET 7, and  when I upgraded the Microsoft.Azure.Functions.Worker.Extensions.DurableTask package to 1.1.0 this started happening. Thinking it might be something to do with my code, I used the new project wizard in Visual Studio to create a new Durable Functions isolated project and chose to have it create an orchestration function, so I now had the example "SayHello" app. Running this, it generates the expected `Saying hello to Tokyo`, `Saying hello to Seattle`, `Saying hello to London` messages. But when I updated the NuGet packages so that I'm now using Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.0, it now generates `Saying hello to "Tokyo"`, `Saying hello to "Seattle"`, `Saying hello to "London"`. Also, if you break in the SayHello function, you'll see that the variable "name" doesn't just contain, say, "Tokyo," it contains "\\"Tokyo\\"".

> A clear and concise description of what you expected to happen.

I expected that the activity function would receive the string passed in the CallAcivityAsync call unchanged, as it did in previous versions of the library.

### Actual behavior

The activity function received the string with quotes added around it.

### Relevant source code snippets

You can get this code by just creating the default app with the wizard in Visual Studio, but here are the relevant parts of the code. The orchestration function calls the activity function here:

```
outputs.Add(await context.CallActivityAsync<string>(nameof(SayHello), "Tokyo"));
```

And then the activity function starts with:

```
public static string SayHello([ActivityTrigger] string name, FunctionContext executionContext)
{   
    ...
```

In that function, "name" contains (for the above call) `"Tokyo"`.

### Known workarounds

None that I know of, except for stripping the quotes out of any strings passed to activity functions.

### App Details

Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.0
Azure Functions runtime version 4
Programming language used: C#

**Comment by Ilia-Kosenkov** [comment] 2023-11-15 14:59
Can this be related to https://github.com/Azure/azure-functions-durable-extension/pull/2656 and an attempt to fix https://github.com/Azure/azure-functions-durable-extension/issues/2504?
In my case, after this PR was merged, I no longer experience activity input deserialization issues, but I do see now extra `"` added to just plain strings.

**Comment by betim-raqi** [comment] 2023-11-20 20:43
#2677 same problem

**Comment by Tiktack** [comment] 2023-11-23 00:11
Facing same problem. Downgrade to 1.0.4 helped.

**Comment by jviau** [comment] 2023-12-06 21:07
Linking this here https://github.com/microsoft/durabletask-dotnet/issues/245

**Comment by jviau** [comment] 2023-12-08 17:51
@Ilia-Kosenkov that is the cause indeed. The dotnet worker special cases `string` and `byte[]`, which causes this issue. I am looking into this to see what the best fix will be.

**Comment by MatLeger** [comment] 2024-01-04 20:48
I have the same problem. However, if I downgrade `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` to `1.0.4` or if I upgrade to `1.2.0-rc.1` then my project won't build because the `Microsoft.DurableTask.Entities` namespace no longer exists.
```
error CS0234: The type or namespace name 'Entities' does not exist in the namespace 'Microsoft.DurableTask' (are you missing an assembly reference?)
error CS0246: The type or namespace name 'TaskEntityDispatcher' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'EntityTriggerAttribute' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'EntityTrigger' could not be found (are you missing a using directive or an assembly reference?)
```

**Closed** 2024-01-08 17:56 UTC
Labels: bug, P1

**Comment by nilsmehlhorn** [comment] 2024-02-01 08:20
@jviau would it be possible to get a new release of `Microsoft.Azure.Functions.Worker.Extensions.DurableTask`? Or am I missing something and this fix is already available otherwise for the isolated worker mode?

**Comment by prashantagrawalcrowe** [comment] 2024-02-01 08:24
@nilsmehlhorn Fix is already released in Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.1

**Comment by jsabev** [comment] 2024-03-06 21:21
@nilsmehlhorn @jviau We are experiencing the issue with quotes added to string parameters in activity functions in Java. Our existing orchestration broke out of the blue and digging around I found this issue. 

In our case, it seems to be happening only when testing locally on windows (the orchestration works on a linux app service plan in azure).

**Comment by Diegobar** [comment] 2024-03-22 20:45
Hi, the problem still exists in Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.1.
When using an Activity function's string parameter for argument in a binding, i.e.:

public async Task Run(
    [ActivityTrigger] string xyz
    [BlobInput("input-{xyz}", Connection = "MyStorage")] BlobContainerClient blobContainer)

Blob's path become "input-"abc""
