### ISSUE TITLE
Performance issues using Durable Entities

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-functions-durable-extension#1447] opened 2020-08-24 19:24 UTC
**Problem**
Given a relative simple flow we experience sudden spikes in response times which disappear after restarten the function app (hosted on a consumption plan). We encounter response times of 10 to 20 seconds versus ~600 ms when things go fine, under relatively low load.

**Scenario**

Using Azure Durable Functions/Entities we update a Durable Entity using an http request as the initiator.

So, currently we have 

1. an HttpTriggered Azure Function (RequestActivation) that calls an
2. OrchestrationTriggered Orchestrator function (RequestActivationOrchestration) that in turns calls a
3. Durable Entity (License) to modify some state:

The entity is called using a proxy.

```csharp
[FunctionName(nameof(RequestActivationOrchestration))]
public static async Task<ActivationResult> RequestActivationOrchestration(
    [OrchestrationTrigger] IDurableOrchestrationContext context)
{
    var request = context.GetInput<ActivationRequest>();
    
    var id = new EntityId(nameof(License), "someid");
    var proxy = context.CreateEntityProxy<ILicense>(id);

    return await proxy.RequestActivation(request);
}
```

and the call to the orchestration function is done in a request/response manner like this:

```csharp
[FunctionName(nameof(RequestActivation))]
public async Task<HttpResponseMessage> RequestActivation(
    [HttpTrigger(AuthorizationLevel.Function, "post", Route = "activations")] HttpRequestMessage request,
    [DurableClient] IDurableOrchestrationClient client)
{
    var activationRequest = await request.Content.ReadAsAsync<ActivationRequest>();
    var instanceId = await client.StartNewAsync(nameof(RequestActivationOrchestration), activationRequest);

    var timeout = TimeSpan.FromSeconds(30);
    var retryInterval = TimeSpan.FromMilliseconds(200);

    var response = await client.WaitForCompletionOrCreateCheckStatusResponseAsync(request, instanceId, timeout, retryInterval);
    var activationResult = await response.Content.ReadAsAsync<ActivationResult>();
    return CreateResponseMessage(request, activationResult, HttpStatusCode.OK);
}
```

**Analysis**

normally response times are perfectly fine given this 2 hrs period as an example:

![image](https://user-images.githubusercontent.com/11960665/91085740-3046b800-e64e-11ea-9f82-1f68bdb0f6d1.png)

but after some time response times dramatically increase given this 2hr period as an example:

![image](https://user-images.githubusercontent.com/11960665/91085678-186f3400-e64e-11ea-8768-96b5b54ec7f3.png)

We can see the orchestration function and entity function don't take much time, so it seems it is a scheduling issue like a [start delay](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestration-start-delays)  but given the relatively low load I wonder if that is the issue. On average we have 3 rps for the http triggered function.

**Questions**

- How can I rule out or confirm that _Backlogged control queues_ and/or _Back off polling delays_ are the bottlenecks? Do mind that stopping/starting the function plan takes away the performance problems for up to a day.
- Given the request count above, are we hitting some limits already or do we do something wrong codewise?

**Comment by mpaul31** [comment] 2020-08-24 23:04
wondering if you check the performance blade / roles metrics if the orchestration start message caused a server instance to spin up and a cold start is skewing the averages?

**Comment by Expecho** [comment] 2020-08-25 07:18
> wondering if you check the performance blade / roles metrics if the orchestration start message caused a server instance to spin up and a cold start is skewing the averages?

It does indeed seems to be caused by new instances being spinned up, but the thing is, it does not recover from the scaling. Affter the scaling the response times keeop being high!

![image](https://user-images.githubusercontent.com/11960665/91144033-bba66480-e6b3-11ea-9549-724d6c1be6d5.png)

**Comment by olitomlinson** [comment] 2020-08-25 13:37
@Expecho There is a new partitioning strategy arriving in 2.3.0 which is expected to be released in the next week or so. I hypothesize that this will fix a whole bunch of _weirdness_ around durable entities, may be this issue too!

**Comment by Expecho** [comment] 2020-08-26 07:42
> @Expecho There is a new partitioning strategy arriving in 2.3.0 which is expected to be released in the next week or so. I hypothesize that this will fix a whole bunch of _weirdness_ around durable entities, may be this issue too!

@olitomlinson I hope so. For now I prevented scaling out operations by setting WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT to 1 ([docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#website_max_dynamic_application_scale_out)) and so far so good.

**Comment by olitomlinson** [comment] 2020-08-26 08:02
@Expecho 

From what I understand, configuring the DurableTask `partitionCount` to 1 in the `host.json` might be a better supported way of limiting your scale out. If I remember correctly `WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT ` doesn't always guarantee just 1 worker.

But if it works for you then great :)

**Comment by sebastianburckhardt** [comment] 2020-08-26 16:12
Given that this starts happening only after running for some time another guess would be a memory leak. Have you had a chance to look at the metrics to see if the memory size is creeping up?

**Comment by Expecho** [comment] 2020-08-27 14:28
> Given that this starts happening only after running for some time another guess would be a memory leak. Have you had a chance to look at the metrics to see if the memory size is creeping up?

@sebastianburckhardt I've taken a look at the metrics but it remains around ~120mb, it doesn't vary much over time.

**Comment by cgillum** [comment] 2020-08-27 20:06
Hey @Expecho - I'm interested in taking a look to see what might be going on. However, I didn't see anything in the issue that can help me uniquely identity your function app. I used the timestamp from your screenshot and the function name to see if I could find more information. Is your function app name start with "func-mij***"?

**Comment by cgillum** [comment] 2020-08-27 21:05
@Expecho Assuming I found the right function app, I can confirm that the app did scale out to additional instances right before the slowness started. I looked at a handful of the slow instances, and it looks like they are being impacted by [start delays](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestration-start-delays) as you suggested. Specifically, I think it's the queue polling latency that is causing the delays. I didn't see any execution problems.

As far as your question:

> How can I rule out or confirm that Backlogged control queues and/or Back off polling delays are the bottlenecks? Do mind that stopping/starting the function plan takes away the performance problems for up to a day.

I'm not sure what the best way to rule out control queue lengths other than to periodically check these lengths yourself. The reason that stopping/starting the function app takes away the problem is because stopping/starting will cause your app to scale back down to a single instance, and queue polling delays do not exist for a single instance. Scale-out likely happens when our infrastructure detects a spike of traffic to your app.

> Given the request count above, are we hitting some limits already or do we do something wrong codewise?

I don't think you're hitting any limits or doing anything wrong codewise. This is just an unfortunate side-effect of how the platform works.

There are a few workarounds you could consider:
* Decrease the queue polling interval as described [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#queue-polling). The downside is that this will increase your storage transaction costs if your app has lots of idle time. This might be the most practical approach if your app is latency-sensitive.
* Set `WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT` to `1` to prevent scale-out. The downside of this is that you won't get more compute if you need it.
* Use an App Service plan with a plan size of 1. Same disadvantage of the previous suggestion, and it could potentially increase your costs further if you're not constantly under heavy load (which I assume you aren't because you otherwise wouldn't be experiencing queue polling delays).

**Comment by Expecho** [comment] 2020-08-31 14:35
@cgillum 

> Is your function app name start with "func-mij***"?

Yes, you found the one :-)

We have applied the 2nd workaround (WEBSITE_MAX_DYNAMIC_APPLICATION_SCALE_OUT is set to 1) and while it does solve our problem right now it is something I don't like it due to the most obvious reason, the limitation to scale out. But even with just one instance the performance varies from 300ms to just over a second. We try to keep the function kind of warm by hitting it every 5 minutes with a dummy request, but I am not sure of the effect).

Decreasing the queue polling interval is certainly a good option. I am not that much worried about the costs but still, but it will take some time to tweak the interval and we probably want to adjust it when traffic gets higher (we are in the early fase of our application so we expect higher traffic in a couple of weeks)

I do wonder what the sweet spot in terms of traffic must be to not get into this performance issue. Too low traffic will result in start delays but how many rps should we need at a minimum to reduce long start delays?

**Closed** 2020-09-14 19:26 UTC
Labels: Needs: Attention :wave:, performance
