### ISSUE TITLE
DI Activation exception, but status of execution still marked as running.

### ISSUE THREAD

**Issue by jkerak** [Azure/azure-functions-durable-extension#1099] opened 2019-12-10 23:29 UTC
### Description
I attempted to start my durable function using an http trigger, and it appeared to succeed, but the state kept saying "running" forever. I checked application insights and found there was an error activating a dependency. The bug in my own code was that I injected a concrete class (that I had not registered) instead of an interface (which I did) into the constructor of my orchestrator function.
### Expected behavior
When I inject a concrete class into the constructor of my orchestrator function without a DI registration, the instance state goes to "failed" and the stack trace of the exception I saw in app insights is shown.

### Actual behavior
When I inject a concrete class into the constructor of my orchestrator function without a DI registration, instance state stays in "running" status, even though there was an exception.

### Relevant source code snippets
My starter function:
```
      [FunctionName("ManagerStarter")]
        public async Task<IActionResult> Start(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)]
            HttpRequest req,
            [DurableClient] IDurableOrchestrationClient starter
        )
        {
            int batchSize = Convert.ToInt32(Environment.GetEnvironmentVariable("USER_BATCH_SIZE"));
            int taskBatchSize = Convert.ToInt32(Environment.GetEnvironmentVariable("TASK_BATCH_SIZE"));

            string instanceId = await starter.StartNewAsync("Orchestrators-ScheduledCommunication", new {batchSize, taskBatchSize});
            return starter.CreateCheckStatusResponse(req, instanceId);
        }
```

Top of my orchestrator function, including the constructor which is incorrectly injecting a concrete class instead of an interface I defined:
```
        private readonly ActivityService _activityService;

        public ScheduledCommOrchestrator(ActivityService activityService)
        {
            _activityService = activityService;
        }

        [FunctionName("Orchestrators-ScheduledCommunication")]
        public async Task ScheduledCommunicationOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {

            dynamic progress = new ExpandoObject();
            progress.StartTime = context.CurrentUtcDateTime;
            context.SetCustomStatus(progress);
. . . 
```

My Startup.cs, where I register the interface:

```
[assembly: WebJobsStartup(typeof(Startup))]
namespace MyOrg.MyNameSpace
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            string mailgunApiKey = Environment.GetEnvironmentVariable("MAILGUN_API_KEY");
            string mailgunUri = Environment.GetEnvironmentVariable("MAILGUN_URI");


            builder.Services.AddHttpClient<MailgunService>(c =>
            {
                c.BaseAddress = new Uri(mailgunUri);
                c.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic",
                    Convert.ToBase64String(Encoding.UTF8.GetBytes($"api:{mailgunApiKey}")));
            });
            
            var azureServiceTokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient =
                new KeyVaultClient(
                    new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
            
            builder.Services.AddSingleton(keyVaultClient);
            
            builder.Services.AddSingleton<IActivityService, ActivityService>();
            builder.Services.AddSingleton<ILoggingService, LoggingService>();

        }
    }
}
```

### Known workarounds
I look in application insights instead of seeing the error message in the instance state

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
Result from statusQueryGetUri, stays this way forever:
![image](https://user-images.githubusercontent.com/16009979/70577855-145fbc80-1b7a-11ea-94c9-6b32f23bc017.png)

The exception in AI:
![image](https://user-images.githubusercontent.com/16009979/70578379-871d6780-1b7b-11ea-98a6-f3ae4aee61ee.png)

### If deployed to Azure

- **Timeframe issue observed**: 12/10/2019, 6:03:08 PM (Local time) - EST
- **Function App name**: would rather not say
- **Function name(s)**:  Orchestrators-ScheduledCommunication 
- **Azure region**: Central US
- **Orchestration instance ID(s)**: 39ca3de385014b44a26ef65b2bb3e6ad, 57627a2bda4c4591977aa1448be4b349
- **Azure storage account name**: would rather not say

**Comment by cgillum** [comment] 2019-12-12 02:10
This is a duplicate of https://github.com/Azure/azure-functions-durable-extension/issues/1081 (though a slightly different variant).

**Closed** 2019-12-13 06:00 UTC
Labels: duplicate
