### ISSUE TITLE
Purge HTTP APIs always return HTTP 404 "Not Found"

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#707] opened 2019-04-16 00:51 UTC
The root cause is that the Azure Functions host does not permit HTTP verbs other than `GET` and `POST`. An update needs to be made to the host to support this.

**Comment by kashimiz** [comment] 2019-04-17 00:33
The next Functions runtime release should contain azure/azure-functions-host#4311, which fixes this.

**Comment by ConnorMcMahon** [comment] 2019-05-10 22:27
It looks like we missed Functions V1 runtime. Opened a new PR to address this: https://github.com/Azure/azure-functions-host/pull/4408.

**Comment by ConnorMcMahon** [comment] 2019-06-04 17:45
This was fixed in the latest [Functions V1 runtime](https://github.com/Azure/azure-functions-host/tree/v1.0.12491) release.

**Closed by ConnorMcMahon** 2019-06-04 17:45 UTC
Labels: bug, external, fix-ready

**Comment by beckettk** [comment] 2019-08-23 01:02
According to the release notes for [Azure Functions Runtime v2.0.12427](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12427) DELETE should be accepted in in extension webhook routes. That may have been the case (I didn't try it then), but now I am finding that the current runtime in use by Azure App Service (Consumption) will not allow DELETE requests.

I have confirmed that my function app is running under runtime version 2.0.12641.0. When I make the following GET request, I get back a 200 OK with the history for 4 instances.

`https://weudfnaphbgiieppcorchdev01.azurewebsites.net/runtime/webhooks/durabletask/instances?taskHub=weudfnaphbgiieppcorchdev01&connection=Storage&code=...&createdTimeFrom=2019-01-25T17:00Z&createdTimeTo=2019-01-25T18:00Z`

But when I make a DELETE request of the same URI, I get back a 404 Not Found

**Comment by beckettk** [comment] 2019-08-23 16:37
Apologies, I've got this working now. Updating all of my application's nuget dependencies resolved the issue.
