### ISSUE TITLE
Durable function execution not scaling / shutting down

### ISSUE THREAD

**Issue by withinboredom** [Azure/azure-functions-durable-extension#1249] opened 2020-02-25 09:47 UTC
I ran into a bug where `IDurableEntityClient.ListEntitiesAsync()` kept getting the same entities over and over again (a separate issue?), which then called a function on each of those entities. It took me about an hour to figure out that it was an infinite loop. However, once the issue was fixed, thousands of entity calls are queued up, running (what appears to be) one at a time. However, the function host is not scaling up, and will shut down if I don't call the API at a regular interval. It would be nice if the function host saw these nearly 100k items in the queue and would scale up or at least not shut down.

#### Investigative information

Please provide the following:

- Timestamp: 2/25/20 10:41 AM CST
- Function App version (1.0 or 2.0): 2.0
- Function App name: handshake-batch
- Function name(s) (as appropriate): host-entity
- Invocation ID: thousands
- Region: West Europe

#### Repro steps

1. Fire thousands of entity invocations with durable functions.
2. Do a deployment while processing those invocations.
2. Wait for host to shut down before finishing those invocations and not scale up.

#### Expected behavior

I'd expect the host to scale up to handle the invocations in a reasonable time or to not turn off while handling those invocations.

#### Actual behavior

Host shuts down while doing entity invocations.

#### Known workarounds

I'm not sure how to manually scale the function host, but setting an api endpoint to be called every few minutes seems to keep at least one server up.

**Comment by cgillum** [comment] 2020-03-02 23:57
The `ListEntitiesAsync` issue is probably caused by the same problem as https://github.com/Azure/azure-functions-durable-extension/issues/1174.

I'm glad that you were able to work around the lack of scaling issue by clearing your queues, but I'd like to better understand what was causing the problem. I'll look into the telemetry for your function app to see if anything interesting shows up.

**Comment by cgillum** [comment] 2020-03-03 00:38
I ran the analysis. It looks like you're running into #1179, and there is a good chance that it will happen again.  See the end of the discussion on that issue for the details about how to apply the fix for this problem (it will be permanently fixed in the v2.2.0 release).

**Comment by withinboredom** [comment] 2020-03-05 19:40
Thanks for looking into it!

**Comment by ConnorMcMahon** [comment] 2020-03-21 00:27
Fixed in 2.2.0

**Closed by ConnorMcMahon** 2020-03-21 00:27 UTC
Labels: duplicate
