### ISSUE TITLE
`GetTimeLine` failure in Chirper sample

### ISSUE THREAD

**Issue by hazelnutsgz** [Azure/azure-functions-durable-extension#1074] opened 2019-11-28 07:50 UTC
### Description
I followed the [README](https://github.com/Azure/azure-functions-durable-extension/tree/dev/samples/entitites-csharp/Chirper) on `Chirper` sample to validate the behaviour of the entity function.

To be more exact, after the server setup at localhost, I executed the following commands:
```
curl -d "Alice's first message" http://localhost:7071/user/alice/chirps -H Content-Type:application/text
curl -d "Alice's second message" http://localhost:7071/user/alice/chirps -H Content-Type:application/text
curl -d "Alice's third message" http://localhost:7071/user/alice/chirps -H Content-Type:application/text

curl -d "Bob's first message" http://localhost:7071/user/bob/chirps -H Content-Type:application/text
curl -d "Charlie's first message" http://localhost:7071/user/charlie/chirps -H Content-Type:application/text
curl -d "Bob's second message" http://localhost:7071/user/bob/chirps -H Content-Type:application/text

curl -d "" http://localhost:7071/user/doris/follows/alice
curl -d "" http://localhost:7071/user/doris/follows/bob
curl -d "" http://localhost:7071/user/doris/follows/charlie
```
The stuff worked as expected. But when I executed the last command to fetch the timeline of a user:
```curl http://localhost:7071/user/doris/timeline```
I didn't get the expected result, but caused an exception in the backend. This is the 
```
[11/28/2019 07:40:25] doris: Function 'GetTimeline (Orchestrator)' failed with an error. Reason: System.ArgumentNullException: Invalid entity id: entity key must not be null.
[11/28/2019 07:40:25] Parameter name: entityKey
[11/28/2019 07:40:25]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.EntityId..ctor(String entityName, String entityKey) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\EntityId.cs:line 27
[11/28/2019 07:40:25]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableEntityProxyExtensions.CreateEntityProxy[TEntityInterface](IDurableOrchestrationContext context, String entityKey) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\DurableEntityProxyExtensions.cs:line 63
[11/28/2019 07:40:25]    at Chirper.Service.GetTimeline.RunOrchestrator(IDurableOrchestrationContext context) in /Users/hashibami/code_misc/azure-functions-durable-extension-dev/samples/entitites-csharp/Chirper/Chirper.Service/Orchestrations/GetTimeline.cs:line 27
[11/28/2019 07:40:25]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments)
[11/28/2019 07:40:25]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 84. IsReplay: False. State: Failed. HubName: SampleHubVS. AppName: . SlotName: . ExtensionVersion: 2.0.0. SequenceNumber: 44.
[11/28/2019 07:40:25] Executed 'GetTimeline' (Failed, Id=5aad0e28-57d7-4f17-b82a-5eb4a1f0bc0b)
[11/28/2019 07:40:25] System.Private.CoreLib: Exception while executing function: GetTimeline. System.Private.CoreLib: Orchestrator function 'GetTimeline' failed: Invalid entity id: entity key must not be null.
[11/28/2019 07:40:25] Parameter name: entityKey.
```

### Known workarounds
> I do check the userid existed in the storage. But the error `Invalid entity id: entity key must not be null.` is quite confusing.

@sebastianburckhardt

**Comment by markerichmond** [comment] 2019-12-02 20:03
This issue emerged when Microsoft.Azure.WebJobs.Extensions.DurableTask" changed from Version 2.0.0-beta3 to Version 2.0.0

**Comment by sebastianburckhardt** [comment] 2019-12-03 15:51
Thanks for reporting this.

The problem is in the Http trigger for `UserTimelineGet`, in the call
```csharp
await client.StartNewAsync(nameof(GetTimeline), userId);
```

The `userId` argument is meant to be the input to the orchestration, but as of recent changes (#991 / #986) is now interpreted as the instance id. Then the input is null which causes the null exception inside the orchestration. 

The solution is to add a type parameter that clarifies that the second argument is an input:
```csharp
await client.StartNewAsync<string>(nameof(GetTimeline), userId);
```

**Comment by hazelnutsgz** [comment] 2019-12-03 16:30
Thanks :D

**Comment by cgillum** [comment] 2019-12-06 01:30
The fix for this was merged into the dev branch. It will go into master as part of our 2.1.0 release.

**Closed by cgillum** 2019-12-06 01:30 UTC
Labels: bug, fix-ready
