### ISSUE TITLE
HTTP API returns Internal Server Error (500) when instance failed

### ISSUE THREAD

**Issue by karrocon** [Azure/azure-functions-durable-extension#632] opened 2019-03-05 16:33 UTC
I'm using the HTTP API to check an instance status and i'm getting 500 response. Response body seems nice and indicates thta instance execution failed due to inner exception.

Is this a known issue? I think that an OK response should be returned by the server in this case because the status request was succesful.

**Comment by cgillum** [comment] 2019-03-05 18:21
This is by design. We used to return HTTP 200, but we changed the behavior to this because clients such as Logic Apps did not correctly detect failures unless we actually returned an HTTP failure status code.

Closing for now since it's by design (and changing it would be breaking), but let us know if you think there is a strong case to change it back to 200 in a future release.

**Closed by cgillum** 2019-03-05 18:21 UTC
