### ISSUE TITLE
Orchestration termination reason not shown

### ISSUE THREAD

**Issue by markheath** [Azure/azure-functions-durable-extension#130] opened 2018-01-11 22:00 UTC
I tried calling the `terminatePostUri` method passing in a `reason` query string parameter of "oops". It successfully terminated my orchestration, but the reason doesn't appear either in the reponse to the `statusQueryGetUri` or anywhere in the logs (I'm testing locally). 

Here's how I called the terminate uri:

```
Invoke-WebRequest -Method Post "http://localhost:7071/admin/extensions/DurableTaskExtension/instances/00
57dcd4b7be4ebc902716d609e665f4/terminate?reason=oops&taskHub=DurableFunctionsHub&connection=Storage&code=7LsL56Ro1sQHneX
F9Ei1OSAi8MVyIoj5v5CzswPCASlWAMDa3TRElw=="
```

The termination message in the logs just shows a blank reason:

```
[11/01/2018 21:42:18] 0057dcd4b7be4ebc902716d609e665f4: Function 'ProcessVideoOrchestrator (Orchestrator)', version '' was terminated. Reason: . State: Terminated. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.1.0.0.
```

It would be nice for this reason at least to appear in the logs, and also could be useful to be in the response to the `getStatusUri`. Is there something different I should be doing?

**Comment by cgillum** [comment] 2018-01-11 22:13
That's odd. I would have expected it to show up. Do you at least see it in the Azure Storage table?

**Comment by markheath** [comment] 2018-01-11 22:24
hmm, struggling to find it in local table storage either in the logs or in the hub history table

**Comment by cgillum** [comment] 2018-01-19 21:07
Sorry for the delay. I've confirmed that the issue is a query string parsing bug. Thanks for reporting this, it will be fixed in the next release. As a workaround, you can use the `TerminateAsync` API directly, like this:

```csharp
[FunctionName("Terminate")]
public static async Task Terminate(
    [HttpTrigger(AuthorizationLevel.Anonymous, "POST")] TerminatePayload payload,
    [OrchestrationClient] DurableOrchestrationClient client)
{
    await client.TerminateAsync(payload.InstanceId, payload.Reason);
}

public class TerminatePayload
{
    public string InstanceId { get; set; }
    public string Reason { get; set; }
}
```

**Closed** 2018-03-02 01:00 UTC
Labels: bug
