### ISSUE TITLE
Wanings after upgrading from 2.7.2 to 2.8.1 

### ISSUE THREAD

**Issue by GasparViannaSage** [Azure/azure-functions-durable-extension#2322] opened 2022-11-22 12:06 UTC
### Description
> After upgrading from the 2.7.2 version we got lots of DF0113 warnings (orchestrator deterministic code constraint) when using dependency injection.

### Expected behavior
No warning

### Actual behavior
![image](https://user-images.githubusercontent.com/100562905/203309307-dd33a903-b321-46db-aa8b-51ca197901d7.png)

### Relevant source code snippets
```csharp
namespace DummyProject
{
    public class DummyOrchestrator
    {
        private readonly ILogger log;
        private readonly IDummy dummy;

        public DummyOrchestrator(ILogger<DummyOrchestrator> log, IDummy dummy)
        {
            this.log = log;
            this.dummy = dummy;
        }

        [FunctionName("SimpleTest")]
        public Task<string> SimpleTest(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var eventData = context.GetInput<DummyImput>();
            var safeLog = context.CreateReplaySafeLogger(log);
            var test = dummy.ReturnHelloWorld();
            safeLog.LogInformation($"BEGIN {test}. eventData: {eventData.MyProperty}");
            return Task.FromResult("Return stuff");
        }
    }

    public class DummyImput
    {
        public int MyProperty { get; set; }
    }

    public interface IDummy
    {
        public string ReturnHelloWorld();
    }

    public class Dummy
    {
        public string ReturnHelloWorld() => "Hello World";
    }
}
```

### Known workarounds
Downgrading again to 2.7.2

### App Details

- **Durable Functions extension version v2.8.1**:
- **Azure Functions runtime version 2.0**:
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

**Comment by cgillum** [comment] 2022-11-22 19:39
Dependency injection is strongly discouraged in orchestrator functions because there's no way for us to know whether those dependency methods are deterministic. If you know they are safe for replay, my recommendation is to suppress the warnings.

FYI @amdeel

**Comment by GavinOsborn** [comment] 2022-11-23 03:22
I suspect this is a duplicate of the analyzer issue I reported in [2289](https://github.com/Azure/azure-functions-durable-extension/issues/2289).

**Closed** 2022-11-24 13:22 UTC
Labels: Needs: Author Feedback

**Comment by idg10** [comment] 2022-11-28 07:24
> Dependency injection is strongly discouraged in orchestrator functions

Wow! That's quite a constraint.

>there's no way for us to know whether those dependency methods are deterministic. If you know they are safe for replay, my recommendation is to suppress the warnings.

Is there any possibility of providing a way for us to tag things as known-deterministic? The problem with suppressing the things is that it adds a lot of noise in the logic of the orchestration itself.
