### ISSUE TITLE
Entity is losing events

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1094] opened 2019-12-06 16:47 UTC
Uk South
DF 2.0.0
Consumption Plan
---

**background**

I start with 3000 service bus messages across 3 queues.

![image](https://user-images.githubusercontent.com/4224880/70331888-4ef2ed80-1838-11ea-99a9-64fa9d768e5b.png)

These payloads are signalled towards 1000 entities, that have never been activated before.

Each Entity receives 1 message from each queue. So each entity receives 3 messages in total.

On receipt of each message, the Entity saves the event to its state, runs a little bit of logic, and generates a projection of data.

This projection of data is simply written to an Azure Storage Table row. So I end up with 1000 rows in Azure storage that matches my 1000 Entities. The rows are operating on an `InsertOrReplace` behaviour. So each Table row is essentially refreshed 3 times.

When an Entity receives each message, it can project more state and the row becomes fuller/ more-complete over time.

---

The problem I'm having is that when I check my projected output in Azure Storage Table I notice that there is a bunch of data missing, here you can see the holes in the data. I've ran this many times, and I end up with about 10-20 incomplete rows out of the 1000 on all the test runs.

![image](https://user-images.githubusercontent.com/4224880/70332711-105e3280-183a-11ea-97aa-2a07da3bbb9c.png)

All of the service bus messages are consumed andthere are no messages incomplete on the control queues, so I know all the events are being at least consumed by the App. I have no exceptions in my App Insights that suggests some of the Entity operations are not completing successfully.

I initially thought this might be a problem with using Azure Storage Table, so I swapped over to using a Cosmos Table (still using the `Microsoft.Azure.Cosmos.Table` SDK) and the problem persists.

So I then drilled into the durable functions state (TaskHubInstances) of one of the affected Entites, and I can see that there is data missing that I would expect to be there after processing of an event from a `Signal`

So where are they?

Execution Id of an affected Entity : `671494aa681a483e836e5cbc93cb5dde`

Approx UTC time : 2019-12-06 14:58

---

**The kicker** : When I run this DF function App **locally** (where the Task Hub is in local emulation) all my projected data is saved perfectly and all the events exist in the state of the Entity.

 So this appears to be an issue with running in an Azure environment.

---

host.json

```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "MessagesTaskHub",
      "storageProvider": {
        "partitionCount": 1
      }
    }
  },
  "logging": {
    "logLevel": {
      "Function": "Warning"
    }
  }
}

```

**Comment by olitomlinson** [comment] 2019-12-06 19:01
I've done some more digging.

I added an appInsights `CustomEvent` as the last step of every Entity method, so I could be sure the Entity was receiving all events.

I've found that when I discover an Entity which looks to be incomplete due to a missing event, the event is actually handled on a different instance from the others

**Example 1** : Here I was missing the 'G' Event in my Azure Table for this partictular Entity. Notice how the G event here is on a different Host

![image](https://user-images.githubusercontent.com/4224880/70348125-f5031f80-1859-11ea-95b2-8f15089c1c7d.png)

**Example 2** : Here I was missing the 'D' Event in my Azure Table for this particular Entity. Notice how the D event here is on a different Host.

![image](https://user-images.githubusercontent.com/4224880/70348289-4f9c7b80-185a-11ea-9d4b-567266e73513.png)

**Comment by cgillum** [comment] 2019-12-06 19:14
Hi @olitomlinson. I'm looking into this but I'm seeing some numbers that don't match what you're describing. I'm looking at a time window between 14:50 UTC and 15:05 UTC and I'm seeing 3,502 entity operations scheduled (corresponding to SignalEntityAsync). In your description you mentioned just 3,000 so I'm wondering if I'm looking at the right time range.

**Comment by olitomlinson** [comment] 2019-12-06 19:40
there may have been other people using the environment and generating traffic at the time, I can't be sure, but my tests only take a few minutes.

I suppose you may get more than 3000 signals if the `ServiceBusTrigger` replays a few messages, which is entirely possible, although I've not seen any exceptions that would indicate that a function lost its lock/timed out and had to redeliver etc.

![image](https://user-images.githubusercontent.com/4224880/70350286-55945b80-185e-11ea-817b-10a71a0999fd.png)

---
I did another test from 17:35 UTC

![image](https://user-images.githubusercontent.com/4224880/70350479-bc197980-185e-11ea-8567-46e82248b847.png)

Heres a couple more affected Entities, for this range:

Execution Ids : `2289806ef2aa4fa697e19aeca9ce69e7` , `29eb9b2e9a9741abb4b0b0a7055f4255` , `b2653e7f8c78442c93be1dec0d6d648b`

timings for execution Id `b26...`

![image](https://user-images.githubusercontent.com/4224880/70351142-3696c900-1860-11ea-9b9e-f3c359a5823d.png)

**Comment by olitomlinson** [comment] 2019-12-06 20:10
as I'm looking through the telemetry I'm more convinced that it's loosing Entity state/events when the Entity migrates between Hosts.

---

Another example

![image](https://user-images.githubusercontent.com/4224880/70352638-7ad79880-1863-11ea-838c-64b711c1390d.png)

With this entity, only received one D event exists in Entity state, despite telemetry saying it saw 2, and the G event doesn't exist in the entity state at all.

Execution Id : `b97aa5ab852b4291a0d82c88989b3d12`

**Comment by sebastianburckhardt** [comment] 2019-12-06 23:13
I did just find some issues in the DTFx AzureStorage implementation that could be responsible for this. The problem is related to "split-brain" situations, where there are two sessions for the same instances. This can happen when migrating control partitions between hosts. The implementation is meant  to detect and resolve these situations via storage conflicts, but those conflicts were not handled right in all cases.

I have a fix (azure/durabletask#345) which may resolve this issue. Hopefully we can get it into 2.1.

**Comment by olitomlinson** [comment] 2019-12-06 23:25
Wow! Such a speedy response! Thanks so much @sebastianburckhardt !

I’m more than happy to spend some testing a pre-release this weekend if you need me too 👍🏻

**Comment by jublair** [comment] 2019-12-13 00:57
Thanks @olitomlinson for following this up! I believe this is the root cause that has been impacting our eternal durable orchestration functions, so I'm excited to see this fix rolled out.

**Comment by cgillum** [comment] 2019-12-18 03:13
Closing this issue as we are wrapping up release activities for v2.1.0. Do let us know if you're still encountering issues in v2.1.0.

**Closed by cgillum** 2019-12-18 03:13 UTC
Labels: fix-ready
