### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException with concurrent orchestration starts

### ISSUE THREAD

**Issue by asos-AdamCox** [Azure/azure-functions-durable-extension#1730] opened 2021-03-15 09:16 UTC
### Description
Hi,

When running performance tests we're often seeing many Microsoft.WindowsAzure.Storage.StorageException's.

Here's an example of one of them logged in App Insights:
> TaskOrchestrationDispatcher-15bd1c1a85b6407abeb62d9b009819af-0: Unhandled exception with work item 'dc215680-ce01-4b2c-a242-c4e4eb1f65d6': Microsoft.WindowsAzure.Storage.StorageException: Element 4 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UploadHistoryBatch(String instanceId, String sanitizedInstanceId, String executionId, TableBatchOperation historyEventBatch, StringBuilder historyEventNamesBuffer, Int32 numberOfTotalEvents, Int32 episodeNumber, Int32 estimatedBatchSizeInBytes, String eTagValue, Boolean isFinalBatch) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1408
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1197
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1114
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 561
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 191
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 375
Request Information
RequestID:cc2b40a6-c002-006e-6c5a-179d98000000
RequestDate:Fri, 12 Mar 2021 16:08:54 GMT
StatusMessage:4:The specified entity already exists.
ErrorCode:
ErrorMessage:4:The specified entity already exists.
RequestId:cc2b40a6-c002-006e-6c5a-179d98000000
Time:2021-03-12T16:08:55.3894733Z
>
>Backing off for 10 seconds until 5 successful operations

When we see these exceptions the performance is badly affected.

Our use case is we have two asb triggers both of which attempt to start the same orchestration if it's not already running and then raise an event to it.

Our suspicion is because these messages are handled so close together both triggers end up queuing the work item to start the orchestration and when the second work item is picked up it results in this exception. It looks like when there have been a number of these around the same time it then causes the code to back off and this is what affects the performance. Having said that we're not intimately familiar with the code this may not be correct.

### Expected behavior
> If we attempt to start the same orchestration from two different triggers at around the same time this should be handled.

### Actual behavior
> The exception is unhandled and it looks like this causes the runtime to backoff and the performance is affected.

### Known workarounds
> No known workarounds

### App Details

- **Microsoft.Azure.Functions.Extensions Version="1.1.0"**
- **Microsoft.Azure.WebJobs.Extensions.DurableTask Version="2.4.1"**
- **Microsoft.Azure.WebJobs.Extensions.ServiceBus Version="4.2.1"**
- **Microsoft.NET.Sdk.Functions Version="3.0.11"**
- **Programming language used**: C#

**Comment by cgillum** [comment] 2021-03-24 15:59
Hi @asos-AdamCox, sorry for the delay. Do you have any additional information that can help us locate the orchestration instance where this exception was encountered? For example, and approximate date/time, and instance ID, and/or an Azure region?

**Comment by asos-AdamCox** [comment] 2021-03-25 15:15
Hi @cgillum, I believe the information you requested has been provided separately but if you need anything else let me know.

**Comment by cgillum** [comment] 2021-03-25 20:56
@asos-AdamCox yep, I got it. I also learned that you actually have two apps using the same storage account and task hub in an active-active configuration. This may complicate things a bit, but I'm taking a look at the execution data we have to try and understand what's going on.

**Comment by cgillum** [comment] 2021-03-25 21:22
@asos-AdamCox I'm not yet sure if this is related to the exception you're seeing, but I did notice a potential problem with your configuration. You currently have two apps using the same storage account and task hub. We primarily support this configuration in [Active-Passive deployments](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-disaster-recovery-geo-distribution#scenario-1---load-balanced-compute-with-shared-storage). We have a feature which automatically selects one app to be the "active" and another to be the "passive".  Looking at our telemetry around the time you observed this problem, I see that your "North EU" app is currently assigned as the "passive" while your "West EU" app is currently assigned as the "active". However, I'm also seeing that orchestrations are being started in your "passive" "North EU" app. This makes me think that you're likely not aware that you're actually running in Active-Passive mode.  If you truly intend both apps to be active, then you need to specify [`"useAppLease": false` in the host.json file](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#durable-functions-2-0-host-json) for both of your apps (also, make sure you have the exact same copy of the code on both apps at all times or you may experience failures or other unpredictable outcomes).

Again, I'm not sure if this is related. However, this may be problematic for other reasons, including the potential for higher than expected network egress costs and higher latency since your storage account and the active app instance are running in different datacenters (North EU and West EU respectively).

**Comment by olitomlinson** [comment] 2021-03-25 23:02
@cgillum 

Is active-active via `useAppLease: false` a actually a fully supported configuration? I was under the impression that having multiple Fn Apps integrates against the same TaskHub would nearly always result in issues and is not recommended?

If there are certain aspects that are, and are not, supported in active-active, please can you share what these are?

**Comment by cgillum** [comment] 2021-03-25 23:05
@olitomlinson your impression is correct, we don't actually support active-active. It's too easy for things to go wrong, as you mentioned. I should have been more clear.

**Comment by cgillum** [comment] 2021-03-25 23:17
@asos-AdamCox I took a closer look at the source of the errors you encountered. The root cause is exactly as you suggested: there is a race condition that occurs when you try to start two instances of an orchestration with the same instance ID at the same time.  For example, this was the case with an orchestration with instance ID **50dac0a6-fabb-4935-89b6-7caa44394610**. At approximately 2021-03-12 16:07:18, there were two simultaneous requests to start it. The result was that both concurrent requests saw that no such instance existed and then both tried to start it. Our backend does not handle this well currently and the failures cause the dispatcher to go into a "backoff mode" that slows down processing for all orchestrations on that node.

Until we have a fix for this, the workaround is to either design the system to not ever try to start the same orchestration instance concurrently, or build some kind of distributed locking mechanism to protect against this case. For example, using a blob lease or a Durable entity to serialize the start requests. I recognize that this is not an ideal workaround.

**Comment by olitomlinson** [comment] 2021-03-25 23:59
OP mentions he is using Azure Service Bus as the trigger.

Given ASB, an alternative solution is to enable`Sessions` on this queue, and setting the `messageID` to what would be the conflicting orchestration ID, this would generate a demultiplexed stream of messages to be consumed by the ASB trigger, which would enforce single concurrency for each would-be orchestration ID and make this race condition go away*

https://dev.to/azure/ordered-queue-processing-in-azure-functions-4h6c


*Assuming that when `StartNewAsync` returns successfully, the TaskHub is in the correct ‘Running’ state.

**Comment by cgillum** [comment] 2021-03-29 23:39
Service Bus sessions is definitely a great tool to use in cases like this. But in case that may not be possible, I'm also working on a fix for this race condition, you should see a PR link associated with this issue soon. Fixing it is long overdue.

**Closed** 2021-03-31 22:29 UTC
Labels: bug, dtfx

**Comment by cgillum** [comment] 2021-03-31 22:34
I made a fix for this in the Durable Task Framework's Azure Storage backend. If all goes well, we should be able to reliably de-duplicate start messages starting in the next extension release.

**Comment by asos-AdamCox** [comment] 2021-07-12 12:43
> @asos-AdamCox I'm not yet sure if this is related to the exception you're seeing, but I did notice a potential problem with your configuration. You currently have two apps using the same storage account and task hub. We primarily support this configuration in [Active-Passive deployments](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-disaster-recovery-geo-distribution#scenario-1---load-balanced-compute-with-shared-storage). We have a feature which automatically selects one app to be the "active" and another to be the "passive". Looking at our telemetry around the time you observed this problem, I see that your "North EU" app is currently assigned as the "passive" while your "West EU" app is currently assigned as the "active". However, I'm also seeing that orchestrations are being started in your "passive" "North EU" app. This makes me think that you're likely not aware that you're actually running in Active-Passive mode. If you truly intend both apps to be active, then you need to specify [`"useAppLease": false` in the host.json file](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#durable-functions-2-0-host-json) for both of your apps (also, make sure you have the exact same copy of the code on both apps at all times or you may experience failures or other unpredictable outcomes).
> 
> Again, I'm not sure if this is related. However, this may be problematic for other reasons, including the potential for higher than expected network egress costs and higher latency since your storage account and the active app instance are running in different datacenters (North EU and West EU respectively).

Hi @cgillum, apologies for resurrecting this thread but this seemed to be the best place to ask some follow-on questions about this stuff - after the above reply you say our current configuration isn't supported and I just wondered why that is? Why is having the same function in two regions (using the same storage & task hub) different to having multiple instances of the function running in one region?

Do you have plans to support the setup we currently have? What are the risks associated with our current setup? What are the risks around setting the useAppLease flag to false?

Also I was curious - if EUN was passive at that time why did it still start orchestrations?

**Comment by cgillum** [comment] 2021-07-12 16:55
Hi @asos-AdamCox 

> Why is having the same function in two regions (using the same storage & task hub) different to having multiple instances of the function running in one region?

There are two specific problems that can occur:

1. It's often not practical to ensure that copies of your code in all regions have the same functions defined. If there is a difference, say, because you are practicing safe deployment practices and deploying to one region at a time, this can cause orchestrations to behave badly if the code changes between apps in different regions cause any incompatibilities (because we can't guarantee determinism). Multiple functions in a single app don't have this problem since they are all deployed together as a unit.
2. As I mentioned earlier, two copies of an app in two regions sharing a storage account in one of those regions can result in higher egress costs. There's no issue if you're okay with these costs, but not everyone properly considers this.

As for whether we'll formally support it - I think it depends on how common and/or critical the scenario is for customers. The current design of the Durable Task Framework makes it impractical to support multiple app instances with different code sharing the same storage resources.

> Also I was curious - if EUN was passive at that time why did it still start orchestrations?

The app lease will prevent the execution of orchestrations but not the starting/scheduling of orchestrations. There is no safety concern with starting orchestrations from multiple regions - only with trying to execute them.
