### ISSUE TITLE
CleanEntityStorageAsync throws NullReferenceException when using Dependency Injection

### ISSUE THREAD

**Issue by Ozzian** [Azure/azure-functions-durable-extension#1920] opened 2021-08-17 08:29 UTC
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

The DurableEntityClient created via dependency injection passes null for config object that results NullReferenceException ("Object reference not set to an instance of an object") when calling for example CleanEntityStorageAsync.

### Expected behavior
> A clear and concise description of what you expected to happen.

No exceptions and the entity storage should be cleaned.

### Actual behavior
> A clear and concise description of what actually happened.

Exception is thrown and I can still see the empty entities in the table storage.

### Relevant source code snippets
```csharp
   public class EntityManager 
   {
        private readonly IDurableEntityClient entityClient;

        // IDurableEntityClient  from Dependency Injection
        public EntityManager(IDurableEntityClient entityClient)
        {
            this.entityClient = entityClient;
        }

        // Throws "Object reference not set to an instance of an object" -expection
        public Task CleanUpAsync() => 
            entityClient.CleanEntityStorageAsync(
                removeEmptyEntities: true,
                releaseOrphanedLocks: true,
                default);
   }
```

The problematic part is originated from [here](https://github.com/Azure/azure-functions-durable-extension/blob/d8186d84c51a982929debf7b5b6186ca236d4822/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClientFactory.cs#L84).
And the part that throws exception is in [here](https://github.com/Azure/azure-functions-durable-extension/blob/d8186d84c51a982929debf7b5b6186ca236d4822/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L561)

Stacktrace:
```
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.<Microsoft-Azure-WebJobs-Extensions-DurableTask-IDurableEntityClient-CleanEntityStorageAsync>d__55.MoveNext() in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 561
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

### Known workarounds
> Provide a description of any known workarounds you used.

Using the default injection for a timer trigger.

```csharp
        [FunctionName(nameof(CleanUp))]
        public async Task CleanUp(
            [TimerTrigger("0 * * * * 1-5")] TimerInfo myTimer,
            [DurableClient(TaskHub = "MyTaskHubName")] IDurableEntityClient durableEntityClient,
            ILogger log)
        {
            log.LogInformation($"Cleaning Entities executing at: {DateTimeOffset.UtcNow}");
            await durableEntityClient.CleanEntityStorageAsync(
                removeEmptyEntities: true,
                releaseOrphanedLocks: true,
                default);
        }
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
2.5.1
- **Azure Functions runtime version (1.0 or 2.0)**:
v3
- **Programming language used**:
c#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

Happens at least on local machine (visual studio)

**Comment by sebastianburckhardt** [comment] 2021-11-04 14:45
PR with the fix was merged.

**Closed by sebastianburckhardt** 2021-11-04 14:45 UTC
Labels: bug

**Comment by Ozzian** [comment] 2021-11-11 11:25
I tested this out, and while it doesn't throw, the entities are not cleaned from the table storage (atleast locally when using Azurite & storage explorer). Am I missing something?

![image](https://user-images.githubusercontent.com/8628769/141290185-bb5a4f01-3645-44f1-a640-059903e89592.png)

**Comment by Ozzian** [comment] 2021-11-11 15:28
That makes sense! But, now that i ran it again it throws an exception. Microsoft.WindowsAzure.Storage.StorageException : Bad Request.

Perhaps this is a different problem related to the new Azurite (replacement for storage account emulator) shipped with VS 2022 - Preview 1.0. Should I create a separate issue for this? Does it belong into this repository?

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Enqueue ---> DurableTask.AzureStorage.Storage.DurableTaskStorageException : Bad Request ---> Microsoft.WindowsAzure.Storage.StorageException : Bad Request
   at async Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd,IRetryPolicy policy,OperationContext operationContext,CancellationToken token)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName,String account,AzureStorageOrchestrationServiceSettings settings,Func`3 operation,AzureStorageOrchestrationServiceStats stats,String clientRequestId)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](??) at /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs : 121
   End of inner exception
   at async DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](??) at /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs : 121
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.Storage.Table.ExecuteAsync(TableOperation operation,String operationType) at /_/src/DurableTask.AzureStorage/Storage/Table.cs : 113
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.Storage.Table.DeleteAsync(DynamicTableEntity tableEntity) at /_/src/DurableTask.AzureStorage/Storage/Table.cs : 80
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.DeleteAllDataForOrchestrationInstance(OrchestrationInstanceStatus orchestrationInstanceStatus) at /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs : 663
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.PurgeInstanceHistoryAsync(??) at /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs : 691
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProvider.PurgeInstanceHistoryByInstanceId(String instanceId) at D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\AzureStorageDurabilityProvider.cs : 129
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.<>c__DisplayClass58_0.<Microsoft-Azure-WebJobs-Extensions-DurableTask-IDurableEntityClient-CleanEntityStorageAsync>g__DeleteIdleOrchestrationEntity|0(??) at D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs : 596
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft-Azure-WebJobs-Extensions-DurableTask-IDurableEntityClient-CleanEntityStorageAsync(??) at D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs : 622 
```

**Comment by sebastianburckhardt** [comment] 2021-11-11 16:55
Based on the call stack, I can tell that the Azure Storage call that throws the BadRequest exception looks like this:
```csharp
await this.InstancesTable.DeleteAsync(new DynamicTableEntity
                    {
                        PartitionKey = orchestrationInstanceStatus.PartitionKey,
                        RowKey = string.Empty,
                        ETag = "*"
                    });
```
Not sure how that would cause a BadRequest.

Do you get the same error when running on the Azure Storage Emulator?

**Comment by sebastianburckhardt** [comment] 2021-11-11 19:31
This is likely a duplicate of #2007. We may be able to use the snippet above to create a repro.
