### ISSUE TITLE
Bug: No error if activity not found..

### ISSUE THREAD

**Issue by ackava** [Azure/azure-functions-durable-extension#527] opened 2018-11-22 07:08 UTC
I made mistake in naming my function, let's say function was "F2_Process",

```javascript
const df = require("durable-functions");

module.exports = df.orchestrator(function*(context){

    const sites = yield context.df.callActivity("F1_GetConstructionSites", "ny");

    const tasks = [];

    if (sites.length === 0) {
        console.log(`No sites to process`);
    }

    for (const site of sites) {
        console.log(`Queued: ${site.url}`);
        tasks.push(context.df.callActivity("F1_Process", JSON.stringify(site)));
    }

    yield context.df.Task.all(tasks);

    console.log("Success");

    return 0;
});
```

Notice that in my `callActivity` to process site, I wrongly named function name as "F1_Process" instead of "F2_Process", I never received any error saying that no such function exist, instead it just hung up and I never see "Success". After investigating Live Metrics Stream in Application Insights, I found that call to start orchestration function completed with result as null;

Error to reproduce is to simply make a call to activity which is not present and see what happens.

**Comment by cgillum** [comment] 2018-11-22 16:01
This is likely the same root cause as https://github.com/Azure/azure-functions-durable-extension/issues/516, which is that orchestrator failures and not being properly handled in JavaScript. We're working on a fix for this.

**Closed** 2019-01-14 00:32 UTC
Labels: bug
