### ISSUE TITLE
Activity function triggered multiple times.

### ISSUE THREAD

**Issue by praveena-m** [Azure/azure-functions-durable-extension#386] opened 2018-07-11 19:38 UTC
Orchestrator function **KMA-Orch-DataRefreshOrchestration** calls suborchestration **KMA-Orch-DataRefreshSubOrchestration** which in turn calls activity function **KMA-Product**

Problem: **KMA-Product** activity function called multiple times. Can someone help me to troubleshoot the issue. Note that the activity functions are long running tasks and may take anywhere between 20 mins to16 hrs.

> Azure runtime version : 1.0
> FUNCTIONS_EXTENSION_VERSION : ~1
> Region : Central US
> Hosting Plan : Standard
> Orchestration PartitionKey/InstanceId : 247431466bb646c096c9f19a2dddc154
> Orchestration Name : KMA-Orch-DataRefreshOrchestration
> Suborchestration PartitionKey/InstanceId : c3dbdc2055cd428d840108001e15afe9:2
> SubOrchestration Name : KMA-Orch-DataRefreshSubOrchestration
> 1st time trigger started at 2018-07-11 08:00:43,379 and abruptly ended somewhere after 2018-07-11 14:28:15,704
> 2nd time trigger started at 2018-07-11 14:32:57,461 and still running.

> **Note Below** : 
> At 2018-07-11 14:26:18.804 there is Startup Request log in D:\home\LogFiles\kudu\trace\2018-07-11T14-26-18_b086b3_001_Startup_GET__0s.xml
> At 2018-07-11 14:28:21.795 there is a Process Shutdown log in D:\home\LogFiles\kudu\trace\2018-07-11T14-28-21_7cd1d0_002_Shutdown_0s.xml

Did the activity function process was killed due to this above event? If Yes how to prevent it? 
```
[FunctionName("KMA-Orch-DataRefreshOrchestration")]
public static async Task DataRefreshOrchestration([OrchestrationTrigger]DurableOrchestrationContext ctx)
{
	try
	{
		var parallelTasks = new List<Task>();

		// Get list of active clients.
		logger.Info(ctx, "Get list of active clients.");
		var clients = await ctx.CallActivityAsync<List<int>>("KMA-GetAllClients", null);
		logger.Info(ctx, $"Number of clients found: {clients.Count()}.");

		foreach (var clientId in clients)
		{
			var orchTask = ctx.CallSubOrchestratorAsync("KMA-Orch-DataRefreshSubOrchestration", clientId);
			parallelTasks.Add(orchTask);
			logger.Info(ctx, $"Started orchestration for clientId: {clientId}.");
		}

		// Wait till the data refresh completes for all clients.
		await Task.WhenAll(parallelTasks);
		logger.Info(ctx, $"Orchestration completed for all clients.");	  
	}
	catch (Exception ex)
	{
		logger.LogAllExceptions(ex);
	}
	finally
	{
		logger.Info("DataAsync OrchestrationTrigger completed.");
	}
}

[FunctionName("KMA-Orch-DataRefreshSubOrchestration")]
public static async Task DataRefreshSubOrchestration([OrchestrationTrigger]DurableOrchestrationContext ctx)
{
	var clientId = ctx.GetInput<int>();
	var today = ctx.CurrentUtcDateTime.Date;
	var productTasks = new List<Task>();
	var orderTasks = new List<Task>();
	var advertisingTasks = new List<Task>();
	var parallelTasks = new List<Task>();

	try
	{
		logger.Info(ctx, $"Started data refresh for ClientID: {clientId} with InstanceId: {ctx.InstanceId}.");

		// Get list of active clients.
		logger.Info(ctx, $"Get list Seller MarketPlaces for ClientID: {clientId}.");
		var sellers = await ctx.CallActivityAsync<List<QueueMessage>>("KMA-GetAllSellerMarketPlaces", clientId);

		foreach (var seller in sellers.GroupBy(x => x.SellerId))
		{
			// Get seller info.
			var sellerInfo = seller.FirstOrDefault();			

			// Trigger product api for once after report api completes for all marketplaces.
			logger.Info(ctx, $"Calling KMA-Product activity trigger for ClientID: {sellerInfo.ClientId}, SellerId: {sellerInfo.SellerId}.");
			var productTask = ctx.CallActivityAsync<Task>("KMA-Product", new QueueMessage(sellerInfo.ClientId, sellerId: sellerInfo.SellerId, mwsAuthToken: sellerInfo.MWSAuthToken));
			productTasks.Add(productTask);
		}

		await Task.WhenAll(productTasks);
		logger.Info(ctx, $"Product completed for ClientID: {clientId}.");
	}
	catch (Exception ex)
	{
		logger.LogAllExceptions(ex);
	}
	finally
	{
		logger.Info($"Completed data refresh for ClientID: {clientId} with InstanceId: {ctx.InstanceId}.");
	}
}

[FunctionName("KMA-Product")]
public static async Task Run([ActivityTrigger]DurableActivityContext ctx)
{
	try
	{
		// call long running operation asynchronously and wait for completion.
	}
	catch
	{

	}
	
 }
```

[2018-07-11T14-26-18_b086b3_001_Startup_GET__0s.txt](https://github.com/Azure/azure-functions-durable-extension/files/2186062/2018-07-11T14-26-18_b086b3_001_Startup_GET__0s.txt)
[2018-07-11T14-28-21_7cd1d0_002_Shutdown_0s.txt](https://github.com/Azure/azure-functions-durable-extension/files/2186063/2018-07-11T14-28-21_7cd1d0_002_Shutdown_0s.txt)
![history](https://user-images.githubusercontent.com/1097942/42597019-46e2b212-850c-11e8-8218-403bfe3df6ef.png)
![instances](https://user-images.githubusercontent.com/1097942/42597021-46ffc096-850c-11e8-960d-376e594a7856.png)

**Comment by cgillum** [comment] 2018-07-30 16:09
The problem is likely because of the host shutdown events. If an activity function runs for an extended period of time, then it's very likely that an activity function's execution could be terminated and replayed later.

A couple recommendations I will make:
1. Always ensure your activity functions are idempotent. We guarantee **at least once** messaging, so multiple executions are possible in certain (though hopefully rare) situations.
2. Use [cancellation tokens](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#cancellation-tokens) in your activity functions to handle host shutdown events gracefully. This way re-execution in these kinds of cases will not be a surprise.

There is no way to prevent host shutdowns, unfortunately, because they may need to be reclaimed for reasons of monthly service updates, security patches, etc. The general recommendation is to simply write your code to handle them.

I'm going to close this issue for now. If you are seeing this with high frequency and suspect something else may be going on, we can re-open and investigate further to see if there may be a bug.

**Closed by cgillum** 2018-07-30 16:09 UTC

**Comment by SwamyNallamalli** [comment] 2018-12-28 23:20
Has someone used the cancellation tokens inside durable functions. Please provide an example of the same. I have a job that is taking around 10 minutes, but I am seeing the same activity getting triggered every ~8 minutes and am assuming that is slowing down everything.
