### ISSUE TITLE
Eternal orchestrations stopped randomly

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/azure-functions-durable-extension#529] opened 2018-11-26 10:00 UTC
I start to see my eternal orchestration code is stopped randomly without known issue, it supposed to keep running forever every 5 minutes.

Within the metrics of applications insight, everything seems ok, no exception or whatever.

What might be the cause that eternal orchestration stopped working? Where to debug this?

**Comment by cgillum** [comment] 2018-11-26 17:59
Can you share the instance ID of your eternal orchestration and the region so we can take a look?

**Comment by andrew-vandenbrink** [comment] 2018-11-26 19:03
its in west europe, {"InstanceId":"3cc1c5ec6db64bf487e70807704b35e8","ExecutionId":"aa27dc11590a494aac59856d3c70401d"}
![image](https://user-images.githubusercontent.com/12871379/49035505-48f21780-f1b5-11e8-8172-c2fe21395906.png)

**Comment by andrew-vandenbrink** [comment] 2018-11-26 19:04
Its stopped at 5am, and then i realize its dead then I re-run it again at 9 am

**Comment by andrew-vandenbrink** [comment] 2018-11-26 19:40
The staging thing is caused by this issue here, for whatever reason traffic manager hit my staging instead of production
https://github.com/Azure/Azure-Functions/issues/1024

Thanks for your help!

**Comment by pksorensen** [comment] 2019-05-10 15:27
@cgillum - I am experiencing the same thing on https://ascendwammoradaringestor.azurewebsites.net (west europe). 

I copied out the application insights information from the last run of my eternal function, hope it has the information you need to investigate.
```

Event time | 10/05/2019, 17:17:59 |  
-- | -- | --
Device type | PC |  
Message | Mirrow Queue Function Time=05/10/2019 15:17:59 SwipeTime=05/10/2019 15:17:48 +00:00 SpeedBoost=False, T1=05/10/2019 15:17:59 T2=05/10/2019 15:17:59 |  
Severity level | Warning |  
Sample rate | 1 |  
Telemetry type | trace |  
SDK version | azurefunctions: 2.0.12438.0 |  
Cloud role name | ascendwammoradaringestor |  
Cloud role instance | 4c2321bf0b63eea59d794031f4bf283f0c96f3086b0325025a732f563dde2dbc |  
Client IP address | 0.0.0.0 |  
Operation name | MirrorQueueFunction |  
Operation Id | bd48814d5a151242b734afe18331cd71 |  
Parent Id | \|bd48814d5a151242b734afe18331cd71.055a68f5af657f4d.

```

**Comment by pksorensen** [comment] 2019-05-12 20:28
Abit of more context that I found odd, given my eternal function here where I set custom activity a few places to find out where it gets stuck.

Every time it's stuck, it's with a custom status {started=...} - Not getting past the activity call nor is it an error status from the catch block. 

![image](https://user-images.githubusercontent.com/2718591/57587441-1a6abd80-7505-11e9-9e18-f9bab6b492c0.png)

**Comment by andrew-vdb** [comment] 2019-05-13 07:16
You should put your ContinueAsNew in finally block

**Comment by pksorensen** [comment] 2019-05-13 07:19
I will do that and test it right away, but since there is not thrown any exceptions (nothing logged atleast) i am guessing it wont solve the problem?

**Comment by pksorensen** [comment] 2019-05-13 07:54
Moving to the finally block did not change anything.

**Comment by pksorensen** [comment] 2019-05-13 13:16
my current implementation:

```
        [FunctionName(nameof(MirrorQueueFunction))]
        public async Task MirrorQueueFunction([OrchestrationTrigger] DurableOrchestrationContext context, ILogger logger)
        {
            var input = context.GetInput<MirrorQueueFunctionInput>();

            var t1 = context.CurrentUtcDateTime;
            var entity = new MirrorQueueFunctionActivityOutput { SwipeTime = input.SwipeTime, Count = 0, SpeedBoost = false };// item;
             
            if (!context.IsReplaying) logger.LogWarning("Mirrow Queue Function Starting {Time}", t1);

            try
            {
                entity = await context.CallActivityWithRetryAsync<MirrorQueueFunctionActivityOutput>(
                        nameof(MirrorQueueFunctionActivity), new RetryOptions(TimeSpan.FromSeconds(1), 3),
                        new MirrorQueueFunctionActivityInput { RadarId = input.RadarId, LastSwipe = input.SwipeTime, Time = context.CurrentUtcDateTime });
                                 
                var t2 = context.CurrentUtcDateTime;

                if (!context.IsReplaying) logger.LogWarning("Mirrow Queue Function Time={Time} SwipeTime={SwipeTime} Count={Count} SpeedBoost={SpeedBoost} Duration={Duration}",
                    context.CurrentUtcDateTime, entity.SwipeTime, entity.Count, entity.SpeedBoost, t2.Subtract(t1));
                 
                if (!entity.SpeedBoost)
                {
                    DateTime next = context.CurrentUtcDateTime.Add(TimeSpan.FromSeconds(2.5));
                    await context.CreateTimer(next, CancellationToken.None);
                }
                 
            }
            catch (Exception ex)
            {
                if (!context.IsReplaying) logger.LogError(ex, "Mirrow Queue Function Time={Time}, Result={@State}", context.CurrentUtcDateTime, new { error = ex.Message });

                context.SetCustomStatus(new { error = ex.Message });
               
            }
            finally
            {
                context.ContinueAsNew(new MirrorQueueFunctionInput { RadarId = input.RadarId, SwipeTime = entity?.SwipeTime });
            }

        }
```

If i remove the call to the activity, it seems to run forever. But with it as in the code above, there is no exceptions thrown, it just seems to go silent at some random time.

**Comment by pksorensen** [comment] 2019-05-13 15:11
Talked with a support engineer that told me to increase function timeout, `"functionTimeout": "00:10:00",` given that he had seen some timeouts:

```
•	IngestNMinute Timeout value of 00:05:00 was exceeded by function (56 times)
•	IngestOneMinute Timeout value of 00:05:00 was exceeded by function (26 times)
•	IngestData Timeout value of 00:05:00 was exceeded by function (10 times)
```

All of thse functions exists in the same function project, but are not related to the eternal orc function. Can they still play a role in this?

My architecture is as follows, might be usefull for context:

MirrorStarter : Function that starts the eternal orc `MirrorQueueFunction`
MirrorQueueFunction: Eternal function that calls `MirrorQueueFunctionActivity` with 2.5 seconds in between.
MirrorQueueFunctionActivity: Activity for eternal function that looks up data and populate a storage queue (using storage SDK).

IngestData: Queue triggered function that pulls item of a queue (same queue that the `MirrorQueueFunctionActivity` fills up. The function raises events to `IngestOneMinuteBatcher` (and creates the orhestrator if it do not exists yet). I had to implement a storage account backed sempahore to avoid multiple starts of orchestrator. (would be nice if there was something build in here).
IngestOneMinuteBatcher:  The batcher function waits for events and if no events surfaced within 10secs it will execute its activity function to batch the result of the given minute. 
```
   [FunctionName(nameof(IngestOneMinuteBatcher))]
        public async Task IngestOneMinuteBatcher(
            [OrchestrationTrigger] DurableOrchestrationContext ctx,
            [OrchestrationClient] DurableOrchestrationClient starter,
            ILogger logger)
        {
            var input = ctx.GetInput<IngestOneMinuteBatcherResult>();
            var time = RadarContext.FromTrim(ctx.InstanceId.Split("_").Last());
            if (!ctx.IsReplaying && input.Count == 0)
            {
                logger.LogWarning("Starting {InstanceID} Time={Time} Count={Count}", ctx.InstanceId, time, input.Count);

            }


            try
            {
                var eventData = await ctx.WaitForExternalEvent<string>(MirrorQueueFunctionHost.EntityBroadcastEventName, TimeSpan.FromSeconds(10));

                input.Count++;
                if (!ctx.IsReplaying) logger.LogDebug("EventRaized {InstanceID} Time={Time} Count={Count}", ctx.InstanceId, time, input.Count);
                ctx.ContinueAsNew(input, true);


            }
            catch (TimeoutException)
            {
                ctx.SetCustomStatus(new { listenering = false });

                if (!ctx.IsReplaying) logger.LogWarning("Batch completed with Count={Count}", input.Count);


                var output = await ctx.CallActivityWithRetryAsync<IngestOneMinuteOutput>(nameof(IngestOneMinute), new RetryOptions(TimeSpan.FromSeconds(1), 3), input);



                if (!ctx.IsReplaying) logger.LogWarning("Finishes {InstanceID} EventCount={EventCount} Swipes={Swipes} ObservationCount={ObservationCount} Time={Time} Duration={Duration1}/{Duration2}", ctx.InstanceId, input.Count, output.Count, output.ObservationCount, time, output.LoadTime, output.ExecutionTime);



            }



        }
```
IngestOneMinute : The activity that batches data of the given min.


IngestNMinuteBatcher: Same idea as minute batcher, just with different timespan settings and triggered form completed one min batches.
IngestNMinute: activity
CalcStats:activity

**Comment by cgillum** [comment] 2019-05-13 16:58
One piece of critical info that I need is an orchestration instance ID. Can you share that? I see you have several in the format of `test_XXXX99999999`, but I need one which ran into the "stopped" problem that you mentioned.

**Comment by pksorensen** [comment] 2019-05-13 17:01
The latest one is :
```
{"name":"MirrorQueueFunction","instanceId":"durabletest17","runtimeStatus":"Running","input":{"$type":"Ascend.Wammo.RadarIngestorFunction.MirrorQueueFunctionInput, Ascend.Wammo.RadarIngestorFunction","RadarId":"test","SwipeTime":"2019-05-13T16:27:25.7159848+00:00"},"customStatus":null,"output":null,"createdTime":"2019-05-13T16:27:34Z","lastUpdatedTime":"2019-05-13T16:27:34Z"}
```

All the test__ are not eternals.

**Comment by cgillum** [comment] 2019-05-13 19:45
Thanks - I found it. And I think I see why your orchestration is getting stuck - the response message from your activity function is being deleted because it think your orchestration instance doesn't exist. I'm currently trying to dig a bit deeper to find out why it thinks this.

**Comment by pksorensen** [comment] 2019-05-13 19:45
Want me to email you the full code?

**Comment by pksorensen** [comment] 2019-05-13 19:48
or thats actually not really anything to do with my code, the orchestration instance should exist :) But maybe there is some overlap with the ContinueAsNew in eternal loop. But thinking about it, that should not happen either.

**Comment by cgillum** [comment] 2019-05-13 20:19
Hmm...I'm wondering if this could be a bug related to a change that was recently made in the ContinueAsNew behavior in the Durable Task Framework. A behavior change was introduced in `v1.8.0` that was supposed to make ContinueAsNew execute faster, but there are some side effects of this which might be impacting you. Are you able to reproduce this "stuck" behavior if you roll back to `v1.7.2` of the durable extension?

**Comment by pksorensen** [comment] 2019-05-13 20:20
Could you remind me of the steps to roll back? just target nuget package and redeploy?

**Comment by cgillum** [comment] 2019-05-13 20:23
Correct, just target that nuget package and redeploy.

**Comment by pksorensen** [comment] 2019-05-13 20:24
will give it a go and report back, noticed that i dont have the  `ctx.ContinueAsNew(input, true); ` So might loose a few events, but can work around that if it works for now.

**Comment by pksorensen** [comment] 2019-05-13 20:29
Looks like it stopped also with 1.7.2. 

```
{"instanceId":"durabletest18","runtimeStatus":"ContinuedAsNew","input":{"$type":"Ascend.Wammo.RadarIngestorFunction.MirrorQueueFunctionInput, Ascend.Wammo.RadarIngestorFunction","RadarId":"test","SwipeTime":"2019-05-13T20:25:26.0523889+00:00"},"customStatus":null,"output":{"$type":"Ascend.Wammo.RadarIngestorFunction.MirrorQueueFunctionInput, Ascend.Wammo.RadarIngestorFunction","RadarId":"test","SwipeTime":"2019-05-13T20:25:28.5729084+00:00"},"createdTime":"2019-05-13T20:25:33Z","lastUpdatedTime":"2019-05-13T20:25:36Z"}
```

i will try a few more

**Comment by pksorensen** [comment] 2019-05-13 20:31
durabletest19 also stopped rather fast.

**Comment by cgillum** [comment] 2019-05-13 20:34
According to our telemetry, both of those two tests are still using `v1.8.1` of the nuget package.

**Comment by pksorensen** [comment] 2019-05-13 20:36
hmm, live stream shows 1.7.1. i will try to backtrace what i did wrong.

![image](https://user-images.githubusercontent.com/2718591/57652286-81ed3f80-75cf-11e9-9834-5220ac4c5898.png)

**Comment by pksorensen** [comment] 2019-05-13 20:39
also the output dll /release that visual studio deployed has 1.7.1
![image](https://user-images.githubusercontent.com/2718591/57652468-ec05e480-75cf-11e9-8123-41ace68de43f.png)

I am using Run as zip, if it matters.

Any suggestion to what might have gone wrong?

**Comment by pksorensen** [comment] 2019-05-13 21:02
I stopped, redeployed and started the function app again.  I can see in livestream that a orchestrator is running, but i cant see which instanceid it has i think.

I will see if it stops and then start a new one.

**Comment by pksorensen** [comment] 2019-05-13 21:17
killing everything and doing a new test in a few.

According to your tweet, https://twitter.com/cgillum/status/1128045887308029953 - what does that mean to eternal functions? do they also get stopped and one need to restart them?

**Comment by pksorensen** [comment] 2019-05-13 21:22
durabletest21 is running now. Will see how long it runs and report back

**Comment by pksorensen** [comment] 2019-05-13 23:09
Looks like it has stopped now:
{"instanceId":"durabletest21","runtimeStatus":"Running","input":{"$type":"Ascend.Wammo.RadarIngestorFunction.MirrorQueueFunctionInput, Ascend.Wammo.RadarIngestorFunction","RadarId":"test","SwipeTime":"2019-05-13T23:05:35.8283667+00:00"},"customStatus":null,"output":{"$type":"Ascend.Wammo.RadarIngestorFunction.MirrorQueueFunctionInput, Ascend.Wammo.RadarIngestorFunction","RadarId":"test","SwipeTime":"2019-05-13T23:05:35.8283667+00:00"},"createdTime":"2019-05-13T23:05:42Z","lastUpdatedTime":"2019-05-13T23:05:43Z"}

**Comment by pksorensen** [comment] 2019-05-13 23:32
I have seperated the project out in two projects to make sure that the eternal orc function is not terminated due to timeout or noise from the other functions.

The eternal function is now running on ascendwammoradarmirrorfunctions.azurewebsites.net using hubname wammomirrorfunctions. 

Will report back with instanceId if/when it stops.

**Comment by pksorensen** [comment] 2019-05-14 07:17
Been running for 8 hours now without a problem. 

![image](https://user-images.githubusercontent.com/2718591/57678094-bf31eb80-7628-11e9-85cc-2d01f078c987.png)

Everything is fine if there is avg 24 swipes/min :)


  You want me to go back to 1.8.1 of durable tasks to confirm that it is a problem? Do you need any more tests to help identify the problem if its with 1.8.1? Otherwise, I will see if I can get things shipped here :)

**Comment by cgillum** [comment] 2019-05-14 16:33
I would say stick with 1.7.2 for now if it's working for you. I have an idea about what might be wrong with 1.8.x. I need to spend some time debugging the Durable Task Framework code to figure out what the right fix is.

**Comment by pksorensen** [comment] 2019-05-15 08:42
Feels like there is another problem with 1.7.2 and events that beeing raized.

My storage queues start accumulating retries. Wiping them to get things going again.

But since i moved that part to a seperate project, i will try to use 1.8 for that and just have 1.7 for the one with eternal function

![image](https://user-images.githubusercontent.com/2718591/57761542-05a54a00-76fe-11e9-8ce5-c5c40ff860c8.png)

**Comment by prabhu87** [comment] 2022-04-25 05:56
Hi Team, We are facing similar issues for DurableFunction, Please let us know what is the solution.

**Comment by davidmrdavid** [comment] 2022-04-25 21:20
Hi @prabhu87: can you please create a new issue thread describing your specific incident? That should help us in case your issue isn't 100% related to this thread, thanks!

**Comment by lilyjma** [comment] 2022-08-10 05:22
@prabhu87 - could you please create a new issue thread as David mentioned if you're still experiencing the problem? This will help increase visibility. Thanks!

**Closed** 2022-08-17 06:02 UTC
Labels: bug, Needs: Author Feedback, no-recent-activity
