### ISSUE TITLE
beta3: ContinueAsNew doesn't continue

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-functions-durable-extension#182] opened 2018-03-09 20:59 UTC
I'm trying to create an eternal orchestration where items are being retrieved in batches for processing. When all items are processed the orchestration is finished and will exit. Today I was experimenting with differenent batch sizes and I noticed that sometimes the `ContinueAsNew` doesn't continue but finishes the orchestration as Succeeded.

I've created a example where this happens:
https://gist.github.com/mlankamp/55949beaf3bb26b783c7a719c154b7c5

**Comment by cgillum** [comment] 2018-03-09 23:29
The orchestration should always finish as Succeeded, but it's not expected that it fails to start running again. Is this running in Azure? If so, can you tell me the region?

Also, I noticed you depend on a static variable which only gets initialized in your HTTP trigger. That seems a little risky because it's possible that midway through your function could get moved to another worker, in which case any continuations will no longer have the static data. Could that be related to this issue?

**Comment by mlankamp** [comment] 2018-03-10 12:40
This example is running in the emulator, that is why I used a statis variable. I'll create an example that will run in Azure (West-Europe), in that example that static is replaced by Cosmos DB.
When I have the example runnning I will share the source and let you know.

**Comment by mlankamp** [comment] 2018-03-13 18:44
@cgillum I've send you an email with a solution and a description to reproduce the issue

**Comment by cgillum** [comment] 2018-03-17 06:11
Thanks for sending me the info. From the traces and from your storage account, I can see that the ContinueAsNew message was inadvertently deleted due to a logic bug in the **DurableTask.AzureStorage** package.  I don't understand how your orchestration ran into this issue while I was unable to reproduce it, but as part of my investigation I also found some bugs in the tracing code that made it difficult for me to fully reason about how this happened.

In any case, I will work on a fix to **DurableTask.AzureStorage** which contains a fix for the ContinueAsNew issue as well as fixes for the tracing bugs. It would be great if you could test it out for me when it's ready to help confirm. :)

**Comment by mlankamp** [comment] 2018-03-23 15:12
Always glad to help!

**Comment by cgillum** [comment] 2018-04-01 00:06
I have a potential fix for this in [DurableTask.AzureStorage v1.1.3-beta](https://www.nuget.org/packages/DurableTask.AzureStorage/1.1.3-beta) (commit: https://github.com/Azure/durabletask/commit/2822d1b727c97182e498fce2f1c4e5bef7799b3d). Could you try it out and let me know if it works for you?

Also, the **dev** branch now references this updated package, so this fix will go out with the next release.

**Closed by cgillum** 2018-04-01 00:06 UTC
Labels: bug, dtfx
