### ISSUE TITLE
Orchestration Replay calls activities twice

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-durable-extension#231] opened 2018-04-05 23:44 UTC
_From @AMSoftwareNL on April 5, 2018 0:27_

#### Investigative information

Please provide the following:

- Timestamp: 2018-04-05 02:25:00 (CET)
- Function App version (1.0 or 2.0-beta): 1.0
- Function App name: amsdurablefunctiontest
- Function name(s) (as appropriate): FunctionStarter, OrchestrationStart, DoFanOut, ForceReplay
- Invocation ID:
- Region: west europe

#### Repro steps

Provide the steps required to reproduce the problem:

Step 1: Start a durable function orchestration
Step 2: Fan-out to a 100 activities
Step 3: The activity writes a record to table storage using IASyncCollector (with a predetermined PartitionId and RowKey)
Step 4: Add a fan-in activity after the fan-out to force a replay of the orchestration

#### Expected behavior

The fan-out activity adds a TableEntity to table storage
The fan-in activity is executed and the orchestration completes

#### Actual behavior

The fan-out activity adds a TableEntity to table storage
The fan-in activity triggers a replay of the orchestration and instead of 'skipping' the fan-out activity and just taking the result (which is void), the fan-out activity is executed again and tries to write new entities to table storage. 
Result is errors in the log (HTTP 409 Entity already exists) as PartitionId and RowKey are fixed. 

The orchestration continues and completes succesfully. 
**NOTE:** If not a fixed rowkey is used some records are created twice.

#### Known workarounds

None

#### Related information 

* Programming language used is C# (VS2017 - 15.6.4)
```csharp
public class TestTableEntity : TableEntity
{
    public string Name { get; set; }
}

public static class FunctionAwaiterTest
{
    [FunctionName("FunctionStarter")]
    public static async Task Run(
        [HttpTrigger]HttpRequestMessage req,
        [OrchestrationClient] DurableOrchestrationClient starter,
        TraceWriter log)
    {
        int awaitCounter = await req.Content.ReadAsAsync<int>();
        string instanceId = await starter.StartNewAsync("OrchestrationStart", awaitCounter);
        log.Info($"Started orchestration with ID = '{instanceId}'.");
    }

    [FunctionName("OrchestrationStart")]
    public static async Task RunOrchestrationStart(
        [OrchestrationTrigger] DurableOrchestrationContext context,
        TraceWriter log)
    {
        log.Info($"Entering function 'OrchestrationStart'.");

        int awaiterCount = context.GetInput<int>();

        List<Task> awaiters1 = new List<Task>();
        for (int i = 0; i < awaiterCount; i++)
        {
            Task awaiter = context.CallActivityAsync("DoFanOut", i);
            awaiters1.Add(awaiter);
        }
        await Task.WhenAll(awaiters1);

        await context.CallActivityAsync("ForceReplay", null);
    }

    [FunctionName("DoFanOut")]
    public static async Task RunDoFanOut(
        [ActivityTrigger] DurableActivityContext context,
        [Table("test")] IAsyncCollector<TestTableEntity> tableEntities,
        TraceWriter log)
    {
        log.Info($"Entering function 'DoFanOut'.");

        int counter = context.GetInput<int>();

        TestTableEntity t = new TestTableEntity()
        {
            PartitionKey = context.InstanceId,
            //RowKey = $"{context.InstanceId}_{counter:00#}",
            RowKey = $"{Guid.NewGuid()}",
            Name = $"Awaiter {counter:00#}"
        };
        await tableEntities.AddAsync(t);

        log.Info($"Exiting function 'DoFanOut'.");
    }

    [FunctionName("ForceReplay")]
    public static async Task RunForceReplay(
        [ActivityTrigger] DurableActivityContext context, TraceWriter log)
    {
        log.Info($"Entering function 'ForceReplay'.");

        await Task.Delay(1);

        log.Info($"Exiting function 'ForceReplay'.");
    }
}
```

_Copied from original issue: Azure/azure-functions-host#2629_

**Comment by AMSoftwareNL** [comment] 2018-04-06 08:36
As far as I can determine it's the replay, but I'm not a 100% sure. But even if it isn't the replay, shouldn't the Durable Task Framework make sure that activities are only called once. Even if the queue message is delivered a second time the framework should already have a result for the activity in the history table and could act the same as in replay. So skip the execution and use the result in history.

Otherwise there should be the possibility to check this in the activity. Because I now get the error because I write to table-storage, but if I for example would call an external API I have no way to determine if it's a duplicate call.

It is also really consistent. Schedule 50 .. no problem, schedule 90 .. no problem, schedule 100 .. problem. The problem also seems very consistent. With a 100 scheduled it seems like it is always record 98 and 99 which are duplicate.

Also I didn't notice the error in the logs while running online, but it jumped out whilst running locally on my dev-environment.

**Comment by cgillum** [comment] 2018-04-06 13:14
Thanks for the additional info - it confirms what I think the problem is. There is clearly a bug though it's not related to replay. I suspect the magic number is 97 or 98 parallel actions. I'll try to get a fix out in the next couple days.

**Comment by cgillum** [comment] 2018-04-07 01:13
Sure enough, there was a simple logic bug in [DurableTask.AzureStorage v1.1.3-beta](https://www.nuget.org/packages/DurableTask.AzureStorage/1.1.3-beta) that was causing history events to get dropped when more than 98 actions are scheduled concurrently. The result was that on replay, we would re-execute a certain number of durable actions, which is exactly what you described. Our testing missed this because our fan-out/fan-in activity functions either didn't have side-effects or were idempotent, thus this was never noticed. I was able to easily reproduce the issue using a test similar to yours (writing rows to table storage and counting the number of rows created).

We'll release an update hopefully by next week which will address this. If you'd like, I can publish a new version of **DurableTask.AzureStorage** early that you can try out?

**Comment by cgillum** [comment] 2018-04-12 00:06
This is fixed in [DurableTask.AzureStorage v1.1.4-beta](https://www.nuget.org/packages/DurableTask.AzureStorage/1.1.4-beta), which will be an explicit dependency in the next release (that or possibly a newer version).

**Closed by cgillum** 2018-04-12 00:06 UTC
Labels: bug, dtfx, fix-ready

**Comment by AsifulNobel** [comment] 2020-02-25 10:18
> * Instance ID: **db4a17f1389548eea8b3ef237406434c**
> 
> Event	FunctionType	FunctionName	count_
> FunctionScheduled	Orchestrator	OrchestrationStart	1
> FunctionStarting	Orchestrator	OrchestrationStart	1
> FunctionScheduled	Activity	DoFanOut	**100**
> FunctionAwaited	Orchestrator	OrchestrationStart	10
> FunctionStarting	Activity	DoFanOut	**102**
> FunctionCompleted	Activity	DoFanOut	**102**
> FunctionScheduled	Activity	ForceReplay	1
> FunctionStarting	Activity	ForceReplay	1
> FunctionCompleted	Activity	ForceReplay	1
> FunctionCompleted	Orchestrator	OrchestrationStart	1

@cgillum How did you produce this data? Is there a specific query? Can you share it, if possible?

**Comment by Kavitha-Desu-Caci** [comment] 2022-10-13 04:39
@cgillum - I am also seeing the same issue that has been reported here which is activity is executing twice instead of taking it from history.  Can you please confirm whether this issue has been released which i think it might have been but would like to know why this is happening? and also  please provide me the query to prouce the data

Event FunctionType FunctionName count_
FunctionScheduled Orchestrator OrchestrationStart 1
FunctionStarting Orchestrator OrchestrationStart 1
FunctionScheduled Activity DoFanOut 100
FunctionAwaited Orchestrator OrchestrationStart 10
FunctionStarting Activity DoFanOut 102
FunctionCompleted Activity DoFanOut 102
FunctionScheduled Activity ForceReplay 1
FunctionStarting Activity ForceReplay 1
FunctionCompleted Activity ForceReplay 1
FunctionCompleted Orchestrator OrchestrationStart 1

**Comment by cgillum** [comment] 2022-10-13 18:21
@Kavitha-Desu-Caci are you seeing this consistently or just occasionally? If just occasionally, the problem is more likely to be some intermittent failure that is causing repeat execution of some activities. We have at-least-once execution guarantees for activities, so things like an unexpected process crash can cause repeat executions like this.

If you're seeing it consistently, then please open a new issue on GitHub (or an Azure support request) and provide an orchestration instance ID, a date range for when this was observed, and the Azure region you observed it in. That will allow us to determine the root cause of any repeat executions.

**Comment by Kavitha-Desu-Caci** [comment] 2022-10-14 03:54
@cgillum - Thanks for your immediate response. I have created a separate issue https://github.com/Azure/azure-functions-durable-extension/issues/2290 which details the issue and my findings. I can consistently reproduce this issue when i run concurrent requests.
