### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by mizrael** [Azure/azure-functions-durable-extension#1451] opened 2020-08-27 14:18 UTC
### Description
I am having an issue with the latest version of the Nuget package `Microsoft.Azure.WebJobs.Extensions.DurableTask`. Basically, every time I try to inject a class that's referencing `Microsoft.CodeAnalysis.Scripting`, I get this exception:

`FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.7.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.`

In my .csproj file I'm already referencing `Microsoft.CodeAnalysis.CSharp.Scripting` version 3.7.0

### Expected behavior
normal program execution, no exceptions thrown

### Actual behavior
`FileNotFoundException` is thrown

### Relevant source code snippets
```csharp
using System;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;

namespace MyFunctionEntities
{
    public class ScriptParser : IScriptParser 
    {
        private static readonly ScriptOptions Options;

        static ScriptParser()
        {
            Options = ScriptOptions.Default
                .AddReferences(typeof(ScriptExecutionContext).Assembly, typeof(DateTime).Assembly)
                .AddImports("System");
        }

        public Task<Predicate<TenantActionExecutionContext>> ParseAsync(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                throw new ArgumentNullException("Value cannot be null or whitespace.", nameof(text));
            return CSharpScript.EvaluateAsync<Predicate<ScriptExecutionContext>>(text, Options);
        }
    }
}
```

The class `ScriptExecutionContext` is a simple DTO. 
The class `ScriptParser` is registered in Startup.cs like this

```csharp
public override void Configure(IFunctionsHostBuilder builder)  {         
    builder.Services.AddSingleton<IScriptParser, ScriptParser>();
}
```

the issue occurs as soon as the DI container tries to create an instance of `ScriptParser`

### Known workarounds
moved back  Nuget `Microsoft.Azure.WebJobs.Extensions.DurableTask` to version `2.2.2`

### App Details
- Durable Functions extension version: 2.3.0
- Azure Functions runtime version: 3.0
- Programming language used: C#
- IDE: Visual Studio 16.7.2

**Comment by cgillum** [comment] 2020-08-27 14:37
I’m guessing this has something to do with our project dependencies conflicting with yours. Functions startup code might be using the same assembly load context as the Durable extension. Because the problem is related to Roslyn assemblies, my guess is that our analyzer update might be causing this.

As potential workarounds, could you try updating your dependencies to match those of the Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers nuget package? Or, could you try explicitly adding a reference to our previous analyzer package version (0.2.2)?

**Comment by mizrael** [comment] 2020-08-27 15:02
Hi Chris, thanks for replying so quickly. When using `Microsoft.Azure.WebJobs.Extensions.DurableTask` version 2.3.0 I can't install the previous analyzer version due to a version mismatch:
```
Detected package downgrade: Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers from 0.3.0 to 0.2.3. Reference the package directly from the project to select a different version. 
 BatchOrchestration.Core -> Microsoft.Azure.WebJobs.Extensions.DurableTask 2.3.0 -> Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers (>= 0.3.0) 
 BatchOrchestration.Core -> Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers (>= 0.2.3)	
```

what are the dependencies of the analyzer ? I see only .NETStandard 2.0

**Comment by mizrael** [comment] 2020-08-27 15:28
ok, let me take a step back. I got confused with the updates, the issue has nothing to do with `Microsoft.Azure.WebJobs.Extensions.DurableTask`. 
The `Microsoft.NET.Sdk.Functions` package is causing it. Version 3.0.3 works fine, the issue shows up starting from v3.0.4.
Sorry for the confusion.

**Comment by ConnorMcMahon** [comment] 2020-08-27 16:39
@mizrael, have you opened a ticket against that repository yet? If not, we can transfer this issue.

**Comment by mizrael** [comment] 2020-08-27 16:40
@ConnorMcMahon not yet. Can you please transfer it?

**Comment by ConnorMcMahon** [comment] 2020-08-27 16:43
Just as a quick catch before I transfer the issue, does the issue still pop up on Version 3.0.9?

**Comment by anthonychu** [comment] 2020-08-27 16:55
This was also reported and discussed here. https://github.com/Azure/azure-functions-host/issues/6512#issuecomment-675608694

**Comment by ConnorMcMahon** [comment] 2020-08-27 22:09
@mizrael, I'm going to close this issue on this repo so that it is only being tracked in one place. I would recommend following up in the thread Anthony posted and if possible sharing a reproduction to help the team resolve that issue.

**Closed by ConnorMcMahon** 2020-08-27 22:09 UTC
Labels: Needs: Attention :wave:

**Comment by mizrael** [comment] 2020-08-28 00:45
thank you @ConnorMcMahon . Sorry for the late reply. 
And yes, it does show up in v3.0.9
