### ISSUE TITLE
Orchestrations freezing mid-execution

### ISSUE THREAD

**Issue by fiddlerpianist** [Azure/azure-functions-durable-extension#2207] opened 2022-06-09 23:00 UTC
### Description
We are still occasionally experiencing  large gaps in time between the scheduling and the starting of durable orchestrations. In this case, all durable orchestrations got "stuck" and would not start until a complete restart of the Function App. There is virtually no load on the Function App when this occurs, and it's not clear that scaling events are related to the issue.

### Expected behavior
We expect that, under no load, there should not be more than a few seconds of a gap between an orchestration or sub-orchestration being scheduled and started.

### Actual behavior
We saw a 2-minute gap for one part of a sub-orchestration and then a complete freeze of the rest of the orchestration that appeared to be indefinite and was only resolved by completely restarting the Function App.

### Relevant source code snippets
This is my host.json. If one of these parameters is ill advised, please let me know. We were guessing on some of these.
```json
{
    "version": "2.0",
    "extensions": {
        "durableTask": {
          "hubName": "EgressHub",
          "storageProvider": {
            "useLegacyPartitionManagement": false,
            "maxQueuePollingInterval": "00:00:01"
          }
        }
      },
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        },
        "logLevel": {
          "Default": "None"
        }
    }
}
```

### Known workarounds
Restarting the Function App (3.5 hours later) immediately resolved the backlogged work.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.7.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: .NET (C#)

### Screenshots
This screenshot of our Kibana instance (where all times all *US Central*, so -5 hours off Zulu) shows a 1.5-minute gap between a sub-orchestration being scheduled and being run. (Note that "Orchestration started" is a few ms after completed. They are out-of-order but you can ignore that, as we are using an activity function to log to Kibana and that sometimes happens. I checked to make sure that the two correlate.)
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5559537/172958290-f64f944f-c151-4574-ae4e-18d0eeb6b253.png">

This sub-orchestration had three nested sub-orchestrations, each of which is labeled here as an `Action orchestration` and were executed in parallel.
<img width="908" alt="image" src="https://user-images.githubusercontent.com/5559537/172957791-7236628e-dac0-4f19-aafa-33a47e4957d6.png">

- **Timeframe issue observed**: June 9th, 2022, 08:00:00 GMT through 11:30:00 GMT
- **Function App name**:  connectx-egress-stg
- **Function name(s)**: RunWorkflowOrchestration
- **Azure region**: US East
- **Orchestration instance ID(s)**: b1da195c78254fec9bcc60e11f74b803
- **Azure storage account name**: strgecnctxstgegress

**Comment by fiddlerpianist** [comment] 2022-06-13 21:49
@cgillum had suggested that a workaround may be to minimize host scale-out events. We are on a Premium plan (EP1) and have rolled out a 4-instance minimum for this app on that plan. It's hard to say if that will make a difference, as this is hard to reproduce.

**Comment by fiddlerpianist** [comment] 2022-06-13 22:08
I went back and filled in a few more details and context that may have made some of this unclear. Please let me know if anything needs further clarification.

**Comment by cgillum** [comment] 2022-06-13 22:22
Thanks @fiddlerpianist, I'm taking a look.

I see that you're almost fully up-to-date on the extension version (the latest is v2.7.2 and you're on v2.7.1), which means you should have all the fixes we made around partition management, which is good. I'll take a look at the instance ID you provided (b1da195c78254fec9bcc60e11f74b803) to see if I can find more clues as to what's going on.

**Comment by cgillum** [comment] 2022-06-13 22:58
It looks like this might be a new version of some of the lease management issues we've been seeing. FYI @amdeel / @davidmrdavid.

 In particular, your sub-orchestration (2798b7e982a44f4b981da5d2a69eb736:4) was scheduled to run on the queue/partition `egresshub-control-00`, but for some reason we were unable to correctly acquire a lease on `egresshub-control-00`, which caused a ~90 second delay between the time this sub-orchestration was scheduled and when it started running. It seems to me that it self-healed in this case, but the problem in general is consistent with your description of occasionally needing to restart your function app.

We'll need to dive deeper to figure out how this happened.

**Comment by fiddlerpianist** [comment] 2022-06-19 03:22
Any updates?

**Comment by cgillum** [comment] 2022-07-11 19:06
@amdeel were you still planning to look into this?

**Comment by amdeel** [comment] 2022-07-13 17:49
The issue you're experiencing is a shutdown related issue that unfortunately I don't have the answer for right now. It seems to occur when a worker that previously was listening to a control queue shuts down. When a new worker picks up that control queue, it is also in the shutdown state and immediately stops listening for messages. It's possible drain mode being enabled is related to this issue.

It's unfortunately tricky to investigate. And Linux customers don't currently have a feature enabled to take a memory dump.

I know that this happened to you during the affected timeframe, but I'm curious if this has happened to you since the original timeframe and, if so, how often?

**Comment by fiddlerpianist** [comment] 2022-07-14 03:43
Since we originally started reporting this issue (back when we were using 2.6.1), we have had 2 complete freezes which required a full restart: one in one of our production environments and one in our staging environment. These freezes are *very* worrisome, as we are an application whose durable tasks need to be timely to be at all relevant. And it sounds like there is little to nothing that we can do about them.

To be honest, we never expected we would have these kinds of issues when we first implemented the solution using Durable Tasks. Should we be considering an alternative at this point? If so, what would you recommend? If not, should we be considering a different implementation of Durable Tasks (such as Netherite)? Would that even help in this case, or wouldn't that matter?

**Comment by cgillum** [comment] 2022-07-14 16:10
@fiddlerpianist the issues you're seeing are specific to the Azure Storage backend, which unfortunately has a complicated design due to natural limitations with Azure Storage itself. We have plans to redesign the partition management system to make it more robust and debuggable in the coming months (this is something @sebastianburckhardt plans to help look into). This issue is very serious to us.

You do have the option of looking at one of our [existing alternate backends](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-storage-providers) (MSSQL and Netherite), which are more likely to be immune to these types of problems (especially the MSSQL backend) but those have their own limitations, including being not yet supported on the Azure Functions Consumption plan (Consumption plan support will be deployed in the coming months).

A Windows-based plan may provide a certain degree of improved reliability since some of the process startup and shutdown behaviors are more well understood by the larger team, and of course provides the options for capturing memory dumps, but we realize this may not be a convenient option for everyone.

**Comment by a3y3** [comment] 2022-07-14 16:30
@cgillum we'll try out both of them to see if it helps with this issue, although personally I would be a little worried of deploying preview engines in production environments.

**Comment by a3y3** [comment] 2022-07-25 15:30
@cgillum I should probably asked you this earlier - sorry about that - but is there a reason we should choose MSSQL over Netherite to test if they help with the issue?

**Comment by lilyjma** [comment] 2022-07-26 22:41
@a3y3 - Chris isn't available at the moment (he's on vacation). But we believe MSSQL doesn't have partition management so it would prevent worker change shut down errors.

**Comment by fiddlerpianist** [comment] 2022-10-01 15:23
> We have plans to redesign the partition management system to make it more robust and debuggable in the coming months (this is something @sebastianburckhardt plans to help look into). This issue is very serious to us.

Could you give me an update on this? I realize that "in the coming months" could mean anything from "This is nearing completion" to "We'll look at this next year." We are on a premium plan and have pinned our minimum instances high enough in our production environment that we haven't seen this problem, but obviously that is suboptimal and not a cost-effective solution the long term. An update would be helpful because it would help us determine if we should spend time pursuing an alternative.

**Comment by cgillum** [comment] 2022-10-03 16:42
@fiddlerpianist we're finalizing our plans now, but my understanding is that this will be done in the current semester, meaning sometime between now and early next calendar year (@lilyjma can correct me on the dates).

**Comment by amdeel** [comment] 2022-10-03 17:56
@fiddlerpianist I'm currently working with another customer to make progress on the investigation of this bug who seems to be running into this issue more frequently. Unfortunately for now I don't have any updates on this investigation but I hope to make progress on it soon. As for the partition manager changes that Chris mentioned, I'm planning work to refactor our partition manager, but I don't necessarily expect this work to resolve this issue. I hope to figure this bug out as soon as possible as I know it does completely stop message processing on the affected partitions. I'll update this issue when I have something to report from my investigation.

**Comment by dev-td** [comment] 2023-01-13 16:07
Hello, I’m facing the exact same issue with Durable Function under Consumption Plan. Azure support told me this thread was the main thread regarding the resolution of this issue. Just wanted to know if some progress have been made since Oct-22.
Rgds

**Comment by lilyjma** [comment] 2023-02-13 21:38
@dev-td - apologies for the delayed response. If you're asking about the support for MSSQL, we've released general availability for this storage provider earlier last month: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/new-storage-providers-for-azure-durable-functions-now-generally/ba-p/3719623

**Comment by mazlinho** [comment] 2023-07-17 11:26
@cgillum @amdeel We are facing similar problems (orchestrators are stuck in state pending) and are trying to do anything to find the root cause. During our investigation, we found this issue. The only workaround that currently works for us is to restart our FuncApps every hour.

Do you think this could be related?
What are your plans regarding that issue?

**Comment by cgillum** [comment] 2023-07-17 19:53
@mazlinho there are many possible reasons why an orchestration might get into a stuck state. We unfortunately need to look at each case on a case-by-case basis. Every hour seems pretty extreme. Can you please open an Azure Support case?

@fiddlerpianist just as an update - the work to redesign the partition manager is complete and will be shipped in a preview form in the next extension release (v2.10). Keep an eye out for more information on this.

I suggest others that come across this GitHub issues similarly open support requests, or at a minimum open a new GitHub issue. We really do need to look at each of these cases individually. I'm going to go ahead and close this issue for now given how old it is.

**Closed by cgillum** 2023-07-17 19:53 UTC
Labels: Needs: Investigation :mag:

**Comment by mazlinho** [comment] 2023-07-18 07:53
@cgillum We already created one but only got general answers that were very unsatisfying. Since this is a very business-critical problem for us right now, do you see any chance to get in contact individually? I could provide you our Azure Support case id as well...

**Comment by davidmrdavid** [comment] 2023-08-04 16:42
Hi @mazlinho, apologies for the late response, I'm just now catching up with a long list of github notifications. If you could link us to the github issue you created, we can try to take another look / engage the team again. The Azure Support case ID would also be helpful.
