### ISSUE TITLE
Some Durable Functions instances stay in Pending state when tested at scale, and scale stops at 7 servers

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-functions-durable-extension#412] opened 2018-08-27 14:38 UTC
While concurrently running hundreds of identical orchestrations (600 instances in our case) using Azure Durable Functions, a customer has observed that the server failed to scale beyond seven instances and some insteances stay in the Pending state. 

Other runs yielded similar results. Here are the results of one of the runs:
* Around 400 of them completed with Success (top level Try Catch didn’t catch an exception).
* Around 10-20 of them completed with Fail ( top level Try Catch caught an exception)
* 2 of them Failed with RuntimeStatus = Fail
* 2 of them are still Pending
* Around 150 were still Running

Pending orchestrations for Durable Functions should eventually run rather than remain stuck in a pending state, and servers should scale beyond 7.

**Comment by nzthiago** [comment] 2018-08-28 14:12
Update: all the tests were done using Consumption Plan

**Comment by nzthiago** [comment] 2018-08-28 14:14
Another note; after 3 days from a total of 600 parent instances there were 88 Running, 2 Pending and 2 Failed parent instances (didn’t count the subs instantiated). There are no more queue messages in any of the control queues, so it looks like all the running and **pending** ones are orphans at this point.

**Comment by cgillum** [comment] 2018-10-29 23:51
Closing this as a duplicate of https://github.com/Azure/azure-functions-durable-extension/issues/460.

**Closed by cgillum** 2018-10-29 23:51 UTC
Labels: needs-investigation
