### ISSUE TITLE
Entities running new and old code after release

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#1873] opened 2021-06-14 15:52 UTC
I'm seeing some strange behavior after deployments where one of my entities with the new code running sends a signal to another entity with the old code running causing deserialization issues **_before_** the entity operation is able to execute. In this case we added a new _enum_  value so the receiving entity is unable to deserialize the input value. This was not a one time thing and seems to occur quite frequently. 

I've already tripled-checked and the task hub is **_not_** being shared between any other apps, including stage slot. I've open a MS ticket and it went no where. I was told to just wait 10 minutes after the deployment before performing the swap ;)

Thank you and please let me know if there is anything else you need!

- **DF Version**: 2.5.0
- **Timeframe issue observed**: 6/10/2021, 10:39:37 AM EST
- **Function App name**: auction-etr-int-purchases-east-prod
- **Function name(s)**: Purchase
- **Azure region**: EAST US
- **Orchestration instance ID(s)**: @purchase@site-id@14@sale-line-id@228758561379621@block-dtm@20210610T103912000 
- **Azure storage account name**: etrdfxeastprod

**Comment by cgillum** [comment] 2021-06-14 16:50
My knowledge on this is a bit fuzzy, but this _may_ a behavior of the Azure Functions platform where we don't guarantee atomic deployments/swaps.

Can you share more details about how you are able to reproduce the problem? For example, do you see this after doing a deployment or does it involve slot swapping? Also, how are you doing your deployments? Are you publishing zip files or loose files?

**Comment by mpaul31** [comment] 2021-06-14 17:07
> My knowledge on this is a bit fuzzy, but this _may_ a behavior of the Azure Functions platform where we don't guarantee atomic deployments/swaps.
> 
> Can you share more details about how you are able to reproduce the problem? For example, do you see this after doing a deployment or does it involve slot swapping? Also, how are you doing your deployments? Are you publishing zip files or loose files?

We first noticed this when we added a new value to an **_enum_** and noticed our entity failed with a json deserialization exception which was strange because one entity was able to signal another entity using the new enum value and the receiving entity then failed to deserialize the payload containing the value. The response in the MS ticket (2104120040006532) said the instance was told by the scale controller to shut down but it did not. This leads me to believe the task hub listener keeps on reading messages from the queue after the slots swaps and thus old and new code is running. This is hard for me to believe, as to why I wanted to mention it here.

This issue happens **_after_** the slow swapped is performed and we are also using zip files.

**Comment by ConnorMcMahon** [comment] 2021-06-22 21:44
Do your slots each have their own taskhub name and/or storage account, and if so, how do you have that configured with your slots (hard-coded, app settings, sticky app settings)?

**Comment by mpaul31** [comment] 2021-06-22 22:21
Each slot uses their own task hub name (same storage) using sticky app settings.

**Comment by ConnorMcMahon** [comment] 2021-06-23 22:52
Ok, with those settings, I believe you would expect that your new code would have to be backwards compatible with your old code (because after the slot swap, your new code would be running on a task hub with entities from your old code). It sounds like you are anticipating this, but the issue is with your old entities not being forward compatible with your new entity messages (which is very understandable!).

Do you know how long you were experiencing this behavior? Unfortunately, as Chris mentioned, I believe this is somewhat expected behavior, as we don't guarantee atomic swaps. I believe the order looks like this:

1. Spin up staging slot with production slot settings.
2. Swap HTTP traffic from production slot to staging slot, and vice versa.
3. Shut down new staging slot (which used to be production slot), and restart with the staging slot settings.

I can see how if there is a time gap between 1 and 3, you would have some new entity messages processed by your old code.

In general, I wouldn't recommend making your task hub names sticky. In general, you only ever want one version of code running on a TaskHub, otherwise you have to worry about backwards (or in the race condition above, forwards) compatibility which can be a huge headache. Instead, I recommend making the task hub names normal app settings.

If you use our HTTP APIs or an HTTP triggered function with the DurableClient binding, this should just work seamlessly with your current slot swap workflow. If you have an external client that is sending entity messages, then this becomes slightly trickier, as you would no longer have a static TaskHub name for your client to utilize. However, this can be fairly easily worked around by exposing an endpoint on your function app that returns the current task hub value of the application. Then, your clients can periodically ping this endpoint on the production slot so they are aware when they should start routing traffic to the new TaskHub. This is slightly more work for the clients, but it keeps your TaskHubs free from the risk of multiple versions running in parallel.

**Comment by mpaul31** [comment] 2021-06-23 23:12
Hmm...I have to re-read this again and let it sink it but does your thought process change at all if my func app did not have any HTTP triggers? All the client functions happen from service bus triggers.

**Comment by sebastianburckhardt** [comment] 2021-06-24 12:36
Seems like a tricky and interesting problem, with no really easy solution at the moment.

At the moment it appears that the only way to do this is to remain backwards compatible throughout the update. In the situation you describe, this could perhaps be achieved by updating the app in two stages; in the first update, add the new enum value and update the entities so they can *receive and handle* the new enum value, but *do not send* it yet; then update the app again with the final code where entities can both receive and send the new type of message.  

To make this easier in the future, we may want to think about supporting some kind of versioning and provide a "causally consistent update" which would mean we prevent TaskMessages sent by a newer version to be processed on the older version. Perhaps, when code running the older version detects an incoming message with a newer version it could just stop processing and wait to be replaced.

**Comment by mpaul31** [comment] 2021-06-24 12:52
Yeah, this is all confusing and unexpected IMO. I found an issue where others have seen the same type of behavior so I wouldn't want to rule out it's a HOST thing, but what I'm hearing here is it's expected.

https://github.com/Azure/azure-functions-host/issues/7017

I still can't for the life of me reason why after a slot deployment where everything was successful old code in the production slot is still running. All the documentation around azure function slot swapping mentions how all the instances are first shut down before proceeding and if any one/thing fails it stops. My gut tells me this one is going to be tough to solve and work through.

**Comment by sebastianburckhardt** [comment] 2021-06-24 13:56
Just to be clear, let's distinguish the following two situations:

1. During a live update, some hosts are running new code and some hosts are running old code. 
2. Even after the update completes successfully, there are still some hosts around that run the old code.

Like you say, situation 2. does not make sense. I agree with you that this sounds like a bug that should be fixed.

On the other hand, situation 1. is somewhat unavoidable, as we cannot "simultaneously" update a cluster of machines. Though it may be possible for us to provide some better guarantees in the future by controlling communication between old and new hosts.

**Comment by mpaul31** [comment] 2021-06-24 14:11
OK, for situation 1, we are using slot deployments with a different task hub name and ALL our function triggers are disabled so the new code deployed to the staging slot will not run. Am I misunderstanding what you are saying by "live update"?

I first thought maybe this had to do with the graceful shutdown flag but I saw the same behavior with it on and off.

**Comment by olitomlinson** [comment] 2021-06-24 21:10
@mpaul31 assuming you use app insights. can you look at the telemetry at the time of deployment/swap and group it by `cloudRole_instanceId` 

You should be able to see a clear time when production operations moved over to the new alternative instance.

I would anticipate that the deserialisation exceptions are happening only on the outgoing instance? If that’s the case, then I think that may confirm the swap isn’t atomic.

If you’re seeing the exception on the incoming instance then that sounds suspicious…

Rightly or wrongly, I’ve learned to assume that swaps/deployments aren’t atomic (as this is what I’ve mostly seen in my career, even outside of Azure) and have always treated things like this as a breaking change, so a 2 stage change (as Sebastian described), where you make consumers/handlers compatible in the first change, before you publish/enable new commands/events in the second change.

Getting into the habit of 2 stage releases is *generally* a good thing if you’re in the world of distributed systems / High Availability. Although it might feel like a chore, it’s a great habit to form. This way of thinking also helps with story splitting and mainline CI, which is a great secondary benefit!

Back to topic, I agree more explicit documentation on this would be prudent if it doesn’t already exist!

**Comment by mpaul31** [comment] 2021-06-25 16:36
@olitomlinson Good idea let me dig into the telemetry and see what I find. I'm just surprised I have not seen any other reports on this.

**Comment by mpaul31** [comment] 2021-07-01 13:05
OK, so we were able to reliably create this issue in one of our lower environments and it appears to be an issue with our function app name being longer (including slot name) than 32 characters. Our organization uses conventions when naming our resources, so they can get quite long.

We found the a warning within the function apps DAS blade and talked with Microsoft about this and they confirmed this **_WILL_** cause issues with deployments with slots. So after this change we have not seen any occurrences of old code running after a release.

However, I **_do understand_** the benefits of the 2-stage approach when it comes to versioning (which we do in all our systems), but this seems to be a little different in this scenario when working with entities and can definitely catch you off guard.

**Comment by mpaul31** [comment] 2021-07-01 19:56
I'm sure @cgillum remembers helping me with turning our DF settings and nothing seemed to change! ;)

**Comment by ConnorMcMahon** [comment] 2021-07-07 00:21
Sorry for the incorrect information earlier. I forget that entities and orchestrations have somewhat different goals when it comes to upgrades (orchestrations having a clean history is far more convenient, while entities you want persistence across upgrades).

I think I'm going to close this issue in favor of #320, which I have already added notes to elaborate on entities vs orchestrations in the pros/cons for each approach.

**Closed by ConnorMcMahon** 2021-07-07 00:21 UTC
Labels: Needs: Attention :wave:

**Comment by mpaul31** [comment] 2021-07-08 12:30
@cgillum I am really blow away by the scaling results after **_only_** making the app func name smaller to fit into the 32 character limit. Our app has never been able to run on one instance during business hours for a sustained period of time.

Before change:
![image](https://user-images.githubusercontent.com/206767/124920874-cb762100-dfc5-11eb-8ab3-dc224551598d.png)

After change:
![image](https://user-images.githubusercontent.com/206767/124920948-e0eb4b00-dfc5-11eb-9503-54f2af474a79.png)

I did notice the function app was put onto a new platform version when I recreate the application. I saw this when I was looking into some new tracing logs regarding DrainMode. It feels like the scale controller was not able to properly vote with the old longer app name. Do you have any insight or metrics on your end that would be able to tell if this was caused by the app name change or the platform version?

**Comment by ConnorMcMahon** [comment] 2021-07-12 21:19
So it turns out that DrainMode is only enabled for new consumption apps at the moment, which is likely part of why you are seeing such remarkable improvements.

I'll see if there is any way to turn it on for existing applications.

**Comment by mpaul31** [comment] 2021-07-13 13:07
@ConnorMcMahon What makes you think it has to do with _DrainMode_ as opposed to the app name change? From what I can gather, _DrainMode_ only comes into play during a scale-in.

**Comment by ConnorMcMahon** [comment] 2021-07-13 17:23
So to my knowledge, the app name change is tied to [this issue](https://github.com/Azure/azure-functions-host/issues/2015), which is more for locking mechanisms for things like timer triggers. I don't believe the scale controller relies on the host ID, but I could be wrong.
